copy q1 from 'q1.tbl' delimiter '|';
copy q2 from 'q2.tbl' delimiter '|';
copy q2_supplier from 'q2_supplier.tbl' delimiter '|';
copy q3 from 'q3.tbl' delimiter '|';
copy q4 from 'q4.tbl' delimiter '|';
copy q6 from 'q6.tbl' delimiter '|';
copy q7 from 'q7.tbl' delimiter '|';
copy q8 from 'q8.tbl' delimiter '|';
copy q9 from 'q9.tbl' delimiter '|';
copy q10 from 'q10.tbl' delimiter '|';
copy q11 from 'q11.tbl' delimiter '|';
copy q12 from 'q12.tbl' delimiter '|';
copy q14 from 'q14.tbl' delimiter '|';
copy q15 from 'q15.tbl' delimiter '|';
copy q16 from 'q16.tbl' delimiter '|';
copy q17 from 'q17.tbl' delimiter '|';
-- copy q18 from 'q18.tbl' delimiter '|';
-- copy q19 from 'q19.tbl' delimiter '|';
