let%expect_test "" =
  Abslayout.of_string_exn
    {|
         ahashidx(dedup(
                            select([c_nationkey],
                              alist(join((l_orderkey = o_orderkey),
                                      join((c_custkey = o_custkey), customer, orders),
                                      lineitem),
                                atuple([ascalar(0.c_nationkey)], cross)))),
                   filter((0.c_nationkey = c_nationkey),
                     alist(join((l_orderkey = o_orderkey), join((c_custkey = o_custkey), customer, orders),
    lineitem),
                       atuple([ascalar(0.c_custkey), ascalar(0.c_name),
                               ascalar(0.c_address), ascalar(0.c_nationkey),
                               ascalar(0.c_phone), ascalar(0.c_acctbal),
                               ascalar(0.c_mktsegment), ascalar(0.c_comment),
                               ascalar(0.o_orderkey), ascalar(0.o_custkey),
                               ascalar(0.o_orderstatus), ascalar(0.o_totalprice),
                               ascalar(0.o_orderdate), ascalar(0.o_orderpriority),
                               ascalar(0.o_clerk), ascalar(0.o_shippriority),
                               ascalar(0.o_comment), ascalar(0.l_orderkey),
                               ascalar(0.l_partkey), ascalar(0.l_suppkey),
                               ascalar(0.l_linenumber), ascalar(0.l_quantity),
                               ascalar(0.l_extendedprice), ascalar(0.l_discount),
                               ascalar(0.l_tax), ascalar(0.l_returnflag),
                               ascalar(0.l_linestatus), ascalar(0.l_shipdate),
                               ascalar(0.l_commitdate), ascalar(0.l_receiptdate),
                               ascalar(0.l_shipinstruct), ascalar(0.l_shipmode),
                               ascalar(0.l_comment)],
                         cross))),
                   s2.n_nationkey)
   |}
  |> Layout_to_depjoin.annot |> Abslayout.pp Fmt.stdout;
  [%expect
    {|
       depjoin(dedup(
                 select([c_nationkey],
                   depjoin(join((l_orderkey = o_orderkey),
                             join((c_custkey = o_custkey), customer, orders),
                             lineitem), select([0.c_nationkey], ascalar(0 as x2))))),
         select([0.c_nationkey, c_custkey, c_name, c_address, c_phone, c_acctbal,
                 c_mktsegment, c_comment, o_orderkey, o_custkey, o_orderstatus,
                 o_totalprice, o_orderdate, o_orderpriority, o_clerk,
                 o_shippriority, o_comment, l_orderkey, l_partkey, l_suppkey,
                 l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax,
                 l_returnflag, l_linestatus, l_shipdate, l_commitdate,
                 l_receiptdate, l_shipinstruct, l_shipmode, l_comment],
           filter((0.c_nationkey = s2.n_nationkey),
             filter((0.c_nationkey = c_nationkey),
               depjoin(join((l_orderkey = o_orderkey),
                         join((c_custkey = o_custkey), customer, orders), lineitem),
                 select([0.c_custkey, 0.c_name, 0.c_address, 0.c_nationkey,
                         0.c_phone, 0.c_acctbal, 0.c_mktsegment, 0.c_comment,
                         0.o_orderkey, 0.o_custkey, 0.o_orderstatus, 0.o_totalprice,
                         0.o_orderdate, 0.o_orderpriority, 0.o_clerk,
                         0.o_shippriority, 0.o_comment, 0.l_orderkey, 0.l_partkey,
                         0.l_suppkey, 0.l_linenumber, 0.l_quantity,
                         0.l_extendedprice, 0.l_discount, 0.l_tax, 0.l_returnflag,
                         0.l_linestatus, 0.l_shipdate, 0.l_commitdate,
                         0.l_receiptdate, 0.l_shipinstruct, 0.l_shipmode,
                         0.l_comment], ascalar(0 as x1))))))) |}]
