(* open Castor *)
(* open Ast *)
(* open Collections *)
(* module A = Abslayout *)

(* let row_store r = *)
(*   (\* Relation has no free variables that are bound at runtime. *\) *)
(*   let scope = Fresh.name Global.fresh "s%d" in *)
(*   let scalars = *)
(*     Schema.schema r |> Schema.scoped scope |> List.map ~f:A.scalar_name *)
(*   in *)
(*   Some (A.list (strip_meta r) scope (A.tuple scalars Cross)) *)

(* let row_store = *)
(*   of_func_pre row_store ~pre:Is_serializable.annotate_stage ~name:"to-row-store" *)
