INSERT INTO public.partsupp VALUES (11648, 1649, 757, 901.64, 's. furiously special instructions affix evenly fluffily regular deposits. ironic, special deposits cajole slyly. regular, ironic theodolit');
INSERT INTO public.partsupp VALUES (183576, 1131, 60, 447.32, 'xpress dependencies. regular, bold packages haggle finally ruthlessly regular foxes. ironic instructions ');
INSERT INTO public.partsupp VALUES (183576, 8613, 7624, 910.40, 'e quickly ironic packages. even, ruthless foxes wake carefully ironic escapades. even, regular deposits cajole among the carefully');
INSERT INTO public.partsupp VALUES (191052, 6091, 430, 21.33, 'sly special packages wake quickly against the slyly special accounts. ironic deposits kindle. fluffily regular ideas along the blithely special packages promise fluffily regular, express foxes. ac');
INSERT INTO public.partsupp VALUES (68969, 3982, 3618, 549.39, 'ess asymptotes. permanently regular theodolites use blithely silent packages. furiously unusual foxes are quickly. slyly bold ideas above the quickly even requests wake fluffily idle instructions.');
INSERT INTO public.partsupp VALUES (68969, 8970, 726, 688.81, 'uests haggle carefully above the even deposits? carefully sp');
INSERT INTO public.partsupp VALUES (126135, 1160, 9425, 679.59, 'inal accounts. furiously express accounts sleep carefully after the blithely specia');
INSERT INTO public.partsupp VALUES (173430, 5948, 6703, 702.30, '. furiously ironic requests use bold requests. quickly regular packages nag slyly against the regu');
INSERT INTO public.partsupp VALUES (148696, 1211, 3300, 267.57, 'c packages. slyly regular deposits haggle blithely carefully special accounts. carefully regular deposits are slyly dolphins. ironic theodolites are slyly furiously even accou');
INSERT INTO public.partsupp VALUES (148696, 3725, 7044, 843.80, 'lets. carefully regular deposits sleep according to the even, express p');
INSERT INTO public.partsupp VALUES (5722, 3223, 5899, 426.65, ' requests sleep carefully. daringly regular requests cajole. regular ideas sleep slyly slyly regular ideas. pending dependencies haggle fluffily; express packages cajole slyly among ');
INSERT INTO public.partsupp VALUES (44211, 4212, 931, 632.79, 'st the blithely ironic requests. carefully final foxes haggle slyly against the fluffily silent deposits; slow requests are quickly finally unusual accounts--');
INSERT INTO public.partsupp VALUES (44211, 9220, 2930, 467.63, 'rouches. carefully express dugouts sleep slyly across the furiously regular asymptotes. blit');
INSERT INTO public.partsupp VALUES (62610, 129, 8004, 793.59, 'asymptotes wake slyly about the carefully pending account');
INSERT INTO public.partsupp VALUES (140739, 740, 2246, 458.49, 'e quick asymptotes. furiously special instructions use fluffily. finally ironic deposits according to the slyly bold ideas cajole carefully express, even packages. quickly ironic deposits solve s');
INSERT INTO public.partsupp VALUES (140739, 8282, 5957, 963.57, 'g the carefully regular pinto beans. express packages a');
INSERT INTO public.partsupp VALUES (62747, 7760, 5777, 13.85, 'y after the regular requests. express requests nag blithely after the furiously regular dependencies. regular, even requests affix. packages wake carefully quic');
INSERT INTO public.partsupp VALUES (35667, 3177, 5399, 194.60, 'ly at the final, pending requests: carefully ironic packages sleep blithely even pinto beans. ideas sleep blithely. furiously even deposits boost furiously. slyly even accounts impress alon');
INSERT INTO public.partsupp VALUES (192589, 2590, 9002, 487.09, 'ently express ideas nag along the blithely final deposits. regular ideas print blithely. quickly regu');
INSERT INTO public.partsupp VALUES (127942, 455, 8155, 442.46, 'uriously across the slyly final pinto beans. furiously regular platelets along the slyly ironic foxes wake requests. quickly express requests haggle evenly across the blithely even ');
INSERT INTO public.partsupp VALUES (127942, 2967, 4507, 134.47, 'unts according to the final, regular instructions sleep a');
INSERT INTO public.partsupp VALUES (44137, 1650, 99, 626.00, 'uffy, pending courts eat-- slow, regular packages kindle regular instructions. accounts around the ironically express tithes are unusual, unusual theodol');
INSERT INTO public.partsupp VALUES (121186, 1187, 4228, 440.96, 'pecial instructions. ironic accounts beneath the even, special instructions sleep blithely according to the requests. dinos a');
INSERT INTO public.partsupp VALUES (179269, 4304, 5882, 803.28, 'thout the carefully regular ideas. carefully ruthless accounts boost daringly accoun');
INSERT INTO public.partsupp VALUES (57029, 4545, 1732, 309.00, ' packages cajole quickly even sheaves. carefully even excuses according');
