INSERT INTO public.partsupp VALUES (64536, 7043, 7400, 518.07, 'ess sentiments. slyly silent packages are above the slyly express foxes. carefully regular excuses among the slyly regular in');
INSERT INTO public.partsupp VALUES (156475, 8991, 7536, 552.98, 'ut the furiously special ideas boost doggedly among the boldly bold foxes? th');
INSERT INTO public.partsupp VALUES (168637, 8638, 6868, 911.97, 'avely bold deposits. final, unusual ideas integrate carefully');
INSERT INTO public.partsupp VALUES (176396, 3948, 7758, 392.89, 'wake blithely after the blithely ironic theodolites. final requests wake');
INSERT INTO public.partsupp VALUES (176396, 6397, 604, 884.44, 'nusual packages hang carefully against the regular, ironic pinto beans. regular accounts ');
INSERT INTO public.partsupp VALUES (106135, 3666, 1878, 456.18, 'ng the regular packages. furiously express foxes haggle fluffily final, unusual dependencies. blithely even accounts cajole according t');
INSERT INTO public.partsupp VALUES (174153, 4154, 6, 347.16, 'y ironic packages. ironic deposits wake carefully slyly');
INSERT INTO public.partsupp VALUES (174153, 6671, 8013, 684.95, ' express ideas. carefully final theodolites grow slyly special theodolites. bold deposits integrate blithely ac');
INSERT INTO public.partsupp VALUES (113464, 998, 3664, 181.21, 'ccounts cajole regular, pending foxes. slyly final accounts according to the pending platelets hag');
INSERT INTO public.partsupp VALUES (133268, 3269, 2634, 950.09, ' accounts. slyly thin accounts detect. furiously express deposits are carefully about the furiously ironic braids-- carefully enticing');
INSERT INTO public.partsupp VALUES (93609, 1137, 4273, 356.70, 'ar requests was fluffily furiously even waters. regular requests sleep furiously! slyly regular packages sleep blithely. quickly regular waters nag. final, ironic frays among the furiously final id');
INSERT INTO public.partsupp VALUES (92675, 2676, 1458, 452.27, 'e fluffily. fluffily unusual theodolites haggle instructions. ideas sleep carefully ironic requests. regular, express pinto beans can boost blithely slyly special pinto beans.');
INSERT INTO public.partsupp VALUES (142540, 2541, 1556, 867.44, 'ffily about the carefully bold multipliers. blithely ironic d');
INSERT INTO public.partsupp VALUES (100874, 8405, 7500, 969.04, 'ites. quiet, ironic gifts nag careful foxes. regular, pending excuses affix above the ironic deposits. carefull');
INSERT INTO public.partsupp VALUES (79127, 4142, 4525, 51.75, 'gle idly above the fluffily even deposits. final ideas cajole carefully after the carefully regular pinto beans. carefully regular packages shall haggle slowly even p');
INSERT INTO public.partsupp VALUES (79127, 6649, 2870, 915.42, 'ndle blithely. courts sleep carefully after the quickly unusual courts. carefully final theodolites wake slyly along the final accounts. regular deposi');
INSERT INTO public.partsupp VALUES (34880, 4881, 8265, 265.09, 'r packages dazzle stealthy ideas. blithely unusual requests wake furiously across the carefully final packages. even accounts above the quickly unusual accounts wake fluffily according to');
INSERT INTO public.partsupp VALUES (101631, 4142, 4555, 124.07, 'ges. dependencies detect fluffily. ruthless requests haggle. special pinto beans haggle slyly above the blithely regular deposits. regular, even platelets cajole. dependencies sleep carefully blit');
INSERT INTO public.partsupp VALUES (101631, 6652, 9111, 632.38, 'ven grouches haggle carefully carefully bold theodolites. bold, regular ideas boost carefully from the quickly pending excuses. bold packages sleep always. ir');
INSERT INTO public.partsupp VALUES (101631, 9162, 2965, 165.21, 'requests. slyly regular warhorses nag express platelets. furiously silent deposits nag about the pinto beans. ironic, ironic packages cajole slyly slyly pending ideas.');
INSERT INTO public.partsupp VALUES (196833, 6834, 2606, 993.80, '-- carefully ironic deposits among the blithely special foxes are carefully along the accounts. quiet pinto beans against the carefully ironic instructions will boos');
INSERT INTO public.partsupp VALUES (172740, 2741, 5519, 969.81, 'ly across the fluffily bold accounts. carefully regular deposits across the evenly final pinto beans use above the blithely even dependencies. even accounts should affix. quickly pendi');
INSERT INTO public.partsupp VALUES (6488, 1489, 2578, 318.38, ' dependencies. ironic instructions use slyly furiously even notornis. furiously regular packages nag slyly unusual pinto beans. bold pinto beans haggl');
INSERT INTO public.partsupp VALUES (114235, 4236, 4878, 172.63, 'ut the final, unusual packages doze even accounts. enticingly silent requests sleep furiously pending pinto beans. furiously slow deposits');
INSERT INTO public.partsupp VALUES (99259, 6787, 5946, 921.12, 'ong the ironic epitaphs. quickly final instructions boost. silent, even acc');
INSERT INTO public.partsupp VALUES (133591, 1131, 9935, 253.46, 'lyly silent requests haggle blithely slyly express theodolites. express requests above the blithely regular dependencies detect silent dolp');
INSERT INTO public.partsupp VALUES (133591, 8618, 5034, 761.55, 'rding to the blithe, special accounts. blithely even requests boost ');
