INSERT INTO public.partsupp VALUES (169293, 1810, 5411, 408.55, 'mpress across the quickly regular packages. slyly express deposits sublate slyly quickly regular dependencies. furiously final deposits haggle furiously according to the');
INSERT INTO public.partsupp VALUES (16355, 8857, 7832, 54.15, 'ts about the carefully regular realms haggle slyly pending ideas? multipliers nag blithely. even packages sleep according t');
INSERT INTO public.partsupp VALUES (171152, 1153, 9019, 351.62, 'gedly slow excuses cajole furiously. express accounts are slyly. packages cajole! blithely regular instructions boost slowly. ');
INSERT INTO public.partsupp VALUES (141365, 1366, 1683, 802.96, '. frays nag. fluffily ironic asymptotes after the even packages use furiously after the blithely ');
INSERT INTO public.partsupp VALUES (141365, 8908, 4061, 992.08, 'requests nag quickly according to the accounts. carefully bold packages about the slyly even requests are ironic foxes. quickly bold pinto');
INSERT INTO public.partsupp VALUES (181540, 4059, 7371, 573.99, 'ckly accounts. furiously special requests haggle fluffily final packages. quietly even platelets affix furiously unusual');
INSERT INTO public.partsupp VALUES (29153, 4158, 4867, 787.92, 'usly even sentiments are blithely requests. regular packages at the even frets haggle slyly stealthily special ideas. ironic foxes against the deposits use carefully slyly unusual reque');
INSERT INTO public.partsupp VALUES (29153, 9154, 6903, 692.54, 'ress excuses sleep fluffily! pending theodolites breach ironically. silent, final sheaves na');
INSERT INTO public.partsupp VALUES (46058, 3571, 9393, 429.33, 'c platelets would doze carefully bold requests. special packages according to the accounts play furiously acc');
INSERT INTO public.partsupp VALUES (72177, 4685, 2928, 69.03, 'lar deposits haggle. blithely regular instructions sleep blithely. carefully enticing dolphins cajole furiously final, even foxes. blithely unusual deposits print carefully ironic accounts. ');
INSERT INTO public.partsupp VALUES (13245, 3246, 7282, 817.05, 'even instructions among the furiously final foxes haggle fluffily across the slyly ironic dependencies. slyly pending');
INSERT INTO public.partsupp VALUES (13245, 8248, 8774, 103.96, 'nding asymptotes cajole fluffily according to the carefully regular theodolites. regular decoys across the ');
INSERT INTO public.partsupp VALUES (136674, 1701, 4475, 468.63, 'sly pending deposits wake unusual excuses. slyly regular pinto beans wake blit');
INSERT INTO public.partsupp VALUES (77145, 4667, 2794, 344.95, 'onic packages. unusual multipliers haggle fluffily. furiously bold platelets boost furiously--');
INSERT INTO public.partsupp VALUES (193267, 3268, 9574, 947.01, ' dolphins. packages haggle carefully. always silent platelets doubt blithely express, pending requests. pending foxes along the slyly silent foxes breach after the blithely un');
