INSERT INTO public.partsupp VALUES (97079, 7080, 205, 839.77, 'olites detect slyly. ironic, bold instructions believe ruthlessly around the requests. bo');
INSERT INTO public.partsupp VALUES (97079, 9589, 1976, 314.00, ' wake about the quickly ironic instructions. regular requests boost furiously final packages. instructions above the slyly even ideas cajole');
INSERT INTO public.partsupp VALUES (76842, 4364, 3252, 78.09, 'express foxes wake even foxes. blithely regular theodolites nag blithely. blithely pending deposits are quickly even accounts. ruthlessly special deposits cajole carefully requests. final, un');
INSERT INTO public.partsupp VALUES (67035, 7036, 9427, 369.94, ' idly ironic accounts. final, silent warthogs wake furiously. deposits affix furiously ');
INSERT INTO public.partsupp VALUES (103557, 1088, 5000, 874.96, '. slyly even requests according to the slyly pending accounts boost blithely final accounts. ironic platelets sleep fluffily ');
INSERT INTO public.partsupp VALUES (61780, 9299, 8135, 301.67, '. slyly final foxes poach boldly across the regular accounts. quickly final p');
INSERT INTO public.partsupp VALUES (70541, 8063, 790, 516.64, 'lent packages! furiously regular requests poach furiously unusual packages. pending, regular instructions sleep fluffily. deposits boost quickly silent requests. quickly regul');
INSERT INTO public.partsupp VALUES (59441, 1947, 9688, 260.10, 's wake quickly even, ironic ideas. blithely permanent deposits detect requests. final deposits about the ironic deposits grow ironic pinto b');
INSERT INTO public.partsupp VALUES (59441, 6957, 9422, 774.08, 'ironic requests nag according to the slyly bold requests. regular ideas cajole slyly above the ironic sheaves. bold, ironic deposits are carefully. express ideas cajole after the pending pe');
INSERT INTO public.partsupp VALUES (108896, 3917, 9901, 119.72, 'ar dependencies. furiously ironic packages wake after the blithely ironic dependencies. slyly special asymptotes alongside of the special accounts use after the slyly i');
INSERT INTO public.partsupp VALUES (108896, 8897, 9087, 84.74, 'dencies. closely even packages boost slyly. final dependenci');
INSERT INTO public.partsupp VALUES (175532, 3084, 7128, 118.01, 'Tiresias. carefully pending platelets after the quietl');
INSERT INTO public.partsupp VALUES (50768, 8284, 2069, 628.13, 'inal accounts. slyly final requests are according to the furiously iro');
INSERT INTO public.partsupp VALUES (6342, 6343, 4579, 624.85, 'ages. express foxes detect. ironic excuses about the furiously regular theodolites haggle blithely final packages. always pending excuses play slyly bol');
INSERT INTO public.partsupp VALUES (62617, 136, 6422, 613.58, 'e unusual foxes. ironic, idle packages cajole carefully. special theodolites boost quickly car');
INSERT INTO public.partsupp VALUES (99383, 1893, 3591, 11.27, 'al, pending theodolites mold fluffily regular, ironic requests. slyly special excuses wake fluffily even packages. carefu');
INSERT INTO public.partsupp VALUES (99383, 9384, 9715, 464.03, ' silent dinos sleep doggedly ironic deposits. enticingly bold packages wake past the re');
INSERT INTO public.partsupp VALUES (75137, 7645, 969, 426.24, 'eposits haggle carefully furiously ironic theodolites. regular, even deposits against the fluffily express deposits affix after the regular, permanent ');
INSERT INTO public.partsupp VALUES (2094, 2095, 5475, 548.58, 'l foxes. packages doze slyly. fluffily even ideas nag carefully after the carefully express requests? stealthily express deposits wake among the unusual depths. idly final requests ag');
INSERT INTO public.partsupp VALUES (2094, 7095, 8321, 278.27, 'telets haggle furiously? slyly bold courts boost quietly blithely even requests. bold packages hang slyly ironic, final instructions. bold p');
INSERT INTO public.partsupp VALUES (2094, 9595, 6044, 769.63, 'ickly. bold, express platelets after the requests are carefully across the carefully express deposits. bold pla');
INSERT INTO public.partsupp VALUES (46416, 3929, 5653, 283.39, 'otornis along the furiously ruthless packages dazzle blithely ironic requests. ironic, final asymptotes among the e');
INSERT INTO public.partsupp VALUES (114859, 9882, 1685, 825.22, 'egular foxes wake at the furiously express accounts. quickly special excuses detect carefully. furiously brave dolphins cajole among the carefully final deposits-- sp');
INSERT INTO public.partsupp VALUES (152116, 9662, 6676, 726.24, 'e blithely even excuses cajole slyly according to the blithely iron');
INSERT INTO public.partsupp VALUES (198896, 6454, 7849, 796.27, 'en instructions are among the ironic, bold packages. slyly bold deposits sleep above the slyly pending packages. slyly regu');
INSERT INTO public.partsupp VALUES (198896, 8897, 9486, 888.17, 'd ideas nag. quickly bold epitaphs affix carefully according to the carefully regular accounts. carefully regul');
INSERT INTO public.partsupp VALUES (198090, 610, 4454, 973.06, 'longside of the blithely even deposits. blithely regular foxes sleep acros');
INSERT INTO public.partsupp VALUES (17827, 7828, 6264, 54.98, 'egular, special foxes haggle bold, even asymptotes. bold packages within t');
INSERT INTO public.partsupp VALUES (42302, 4807, 6806, 593.42, ' frets. blithely bold foxes to the accounts sleep furiously along the ironic instructions? pinto beans integrate quickly. ironic, special dinos haggle slyly against the blithely unusual theodolites.');
INSERT INTO public.partsupp VALUES (159479, 1995, 3021, 86.64, 're across the blithely even accounts. regularly bold tithes wake carefully');
INSERT INTO public.partsupp VALUES (159479, 4510, 8177, 792.65, 'y quickly final asymptotes. unusual pinto beans wake. regular theodolites about th');
INSERT INTO public.partsupp VALUES (135104, 131, 6783, 20.09, 'unts shall have to integrate. slyly regular foxes about the regular warthogs sleep except the iro');
INSERT INTO public.partsupp VALUES (176823, 6824, 5706, 702.35, 'aggle alongside of the final requests. packages toward the regular requests use carefully regular, final packages. regular realms nag carefully final ideas. furiously ');
INSERT INTO public.partsupp VALUES (167623, 140, 9324, 804.02, 'ideas wake. blithely express packages wake blithely. blithely even pinto beans affix. boldly regular instructions before the furiously regular foxes dazzle quickly special asymptotes');
INSERT INTO public.partsupp VALUES (167623, 5172, 3518, 313.27, 'st. quickly special tithes wake carefully slyly final ideas. fluffily even courts sleep busil');
INSERT INTO public.partsupp VALUES (164416, 6933, 68, 19.38, ' patterns. bold foxes sleep quickly about the regular requests. slyly regular accounts about the carefully final ideas wake accounts. r');
INSERT INTO public.partsupp VALUES (66678, 1691, 7746, 151.29, 'sts cajole enticing, final theodolites. carefully express deposits above the packages nod');
INSERT INTO public.partsupp VALUES (193342, 900, 9233, 386.66, 's are according to the ironic accounts. ironic, final pinto beans use. final');
INSERT INTO public.partsupp VALUES (1348, 1349, 7996, 70.89, 'aggle regular theodolites. slyly bold instructions about the r');
INSERT INTO public.partsupp VALUES (1348, 6349, 4257, 282.75, ', express deposits. unusual accounts haggle. courts nag among the unusual accounts. ironic packages across the packages would cajole furiously blithely special dependencies. slyly r');
INSERT INTO public.partsupp VALUES (33406, 5910, 9942, 387.02, 'l deposits. regular instructions haggle across the final theodolites. furiously special courts during the blith');
INSERT INTO public.partsupp VALUES (33406, 8413, 8464, 395.70, 'es. bold Tiresias kindle quietly. slyly regular deposit');
INSERT INTO public.partsupp VALUES (166378, 3927, 9314, 80.12, 'have to boost furiously. furiously unusual theodolites in place of the furiously regular pinto beans use fluffily about the slyly regular packages. furiousl');
INSERT INTO public.partsupp VALUES (31082, 8592, 3883, 552.13, 'ly express foxes across the final dolphins haggle carefully across the final accounts. fur');
INSERT INTO public.partsupp VALUES (166436, 1469, 1116, 28.91, 'ggle pending, regular ideas. furiously pending excuses cajole after th');
INSERT INTO public.partsupp VALUES (6063, 6064, 8968, 682.28, 'nto beans should haggle asymptotes. fluffily special deposits use blithely. never final warthogs about the quickly ironic f');
INSERT INTO public.partsupp VALUES (139598, 7138, 7789, 921.58, ' the bold, final requests. slyly even deposits after the bold packages haggle fluffily about the slyly ironic accounts. ironic, final asymptotes sleep final ideas. furiously final packages solv');
INSERT INTO public.partsupp VALUES (167654, 171, 4294, 784.97, 'express platelets boost fluffily pinto beans. foxes haggle ca');
INSERT INTO public.partsupp VALUES (167654, 7655, 5970, 407.97, 's across the regularly unusual requests affix quickly final courts. slyly ironic accounts detect always quickly unusual theodolites. fluffily ironic deposits nag along the sl');
INSERT INTO public.partsupp VALUES (147193, 9708, 9359, 957.52, 'according to the furiously express epitaphs. requests can use furiously. slyly expr');
INSERT INTO public.partsupp VALUES (93093, 8112, 7044, 408.59, ' special packages sleep across the packages! slyly express theodolites engage. regular theodolites for the carefully pending hockey players sleep slyly regular account');
