INSERT INTO public.partsupp VALUES (193267, 5787, 9658, 435.90, 'inal pearls. unusual requests use along the carefully bold forges. regular multipliers haggle furiously. doggedl');
INSERT INTO public.partsupp VALUES (30642, 3146, 7292, 374.94, 'y near the carefully final ideas. regular, bold foxes boost quickly ruthless accounts. carefully express accounts wak');
INSERT INTO public.partsupp VALUES (3045, 3046, 1969, 909.96, 's cajole above the final accounts. regular, even dolphins cajole blithely ironic patterns. ironic fo');
INSERT INTO public.partsupp VALUES (3045, 5546, 5952, 72.92, 's use furiously. packages haggle furiously even excuses. furiously ');
INSERT INTO public.partsupp VALUES (40245, 246, 2125, 195.54, 'ng to the even deposits; unusual courts breach quickly pendin');
INSERT INTO public.partsupp VALUES (40245, 2750, 2205, 977.59, 'blithely. blithely even pinto beans are. quickly express instructions haggle quickly across the even platelets. slyly ironic packages wake furi');
INSERT INTO public.partsupp VALUES (5475, 2976, 5154, 140.73, ' accounts. dependencies above the carefully unusual foxes boos');
INSERT INTO public.partsupp VALUES (5475, 5476, 7209, 461.01, 'detect carefully ideas. excuses boost carefully bold requests. slyly pending pint');
INSERT INTO public.partsupp VALUES (33724, 3725, 5114, 262.96, 'ly unusual ideas. ironic, final courts according to the slyly regular theodolites believe above the blithely final requests. sometimes regular ideas at the furiously even accou');
INSERT INTO public.partsupp VALUES (28656, 8657, 1395, 186.96, 'ss the carefully regular accounts-- fluffily express instructions alongside of the ironic deposits believe furiously regular depths. fluffily bold deposits cajole furiously bold deposits: furious');
INSERT INTO public.partsupp VALUES (32748, 258, 1728, 879.19, 'gle slyly across the furiously regular requests. r');
INSERT INTO public.partsupp VALUES (32748, 2749, 8833, 632.23, 'r dugouts. final accounts at the dolphins sleep carefully above the carefully final ideas. packages cajole furiously regular deposits. slyly regular packages cajole. slyly even ');
INSERT INTO public.partsupp VALUES (32748, 5252, 5931, 627.62, 'bold dependencies. carefully final instructions wake carefully along the pending, final theodolites-- fluffily special deposits sleep slyly. slyly ironic packages according t');
INSERT INTO public.partsupp VALUES (33546, 8553, 6143, 989.36, 'ly unusual, regular asymptotes. silent, final asymptotes affix blithely even deposits. multipliers dazzle carefully furiously ironic dugouts. carefully silent accounts boost. special, fin');
INSERT INTO public.partsupp VALUES (154129, 1675, 4299, 837.62, 'ickly even ideas along the busily ironic warthogs are quickly above t');
INSERT INTO public.partsupp VALUES (154129, 9160, 4423, 185.07, 'arly against the express, final deposits. final requests wake furiously. regular, bold pinto beans us');
INSERT INTO public.partsupp VALUES (6799, 1800, 5197, 294.77, 'mise quickly along the accounts. evenly regular requests cajole quickly against the deposits. fina');
INSERT INTO public.partsupp VALUES (45426, 5427, 5340, 518.51, 'ly. quick, regular deposits believe slyly ironic instructions. unusual, bold excuses cajole quickly above the slyly unusual requests: ironic pinto beans wake. quickly unusual deposits nod pending');
INSERT INTO public.partsupp VALUES (6131, 1132, 5846, 494.43, ' furiously bold dolphins. blithely ironic foxes doze quickly against the quickly ');
INSERT INTO public.partsupp VALUES (6131, 8632, 3774, 118.18, 'auternes unwind quickly carefully special theodolites. packages affix. silent ideas grow furiously-- ironic accounts cajole quick platelets. slyl');
INSERT INTO public.partsupp VALUES (80233, 2742, 3663, 783.49, ' pending ideas wake slyly fluffily ironic pinto beans: furiously ironic requests nag carefully ');
INSERT INTO public.partsupp VALUES (25770, 5771, 4361, 184.32, 'among the even packages. instructions about the carefully even packages are unusual accounts. furiously pending packages cajole regularly requests. fluffily even foxes wake blit');
INSERT INTO public.partsupp VALUES (35624, 5625, 45, 853.02, 's. ironic excuses against the instructions hinder ironic warthogs. quickly unusual theodolites use despite the thin depo');
INSERT INTO public.partsupp VALUES (52574, 2575, 5596, 581.40, 'wake blithely express attainments. excuses against the ironic, regular deposits boost furiously into the furiously express deposits. bli');
INSERT INTO public.partsupp VALUES (52574, 5080, 5423, 588.32, 'ly furiously final notornis. final accounts use. regular dependencies cajole carefully! ironic ');
INSERT INTO public.partsupp VALUES (142766, 2767, 9616, 389.93, 'al deposits. slyly express pinto beans are quickly before the even packages. express instructions integrate blithely final requests. qu');
INSERT INTO public.partsupp VALUES (190144, 145, 611, 288.67, 'ray slyly final dolphins. ideas poach. pending instructions haggle slowly at the special deposits. specia');
INSERT INTO public.partsupp VALUES (91214, 6233, 1108, 268.76, 'carefully blithely daring asymptotes. final dependencies against the special somas are slyly deposits. stealthily regular accounts use carefully. fluffily ironic requests impr');
INSERT INTO public.partsupp VALUES (6134, 1135, 2540, 153.03, 'ons. pending, special excuses against the carefully bold dependencies haggle even foxes. doggedly express decoys mold quickly blithely unusual packages. carefully final f');
