INSERT INTO public.partsupp VALUES (192975, 533, 8173, 495.10, 'pinto beans according to the pinto beans wake carefully blithely regular packages. ironic deposits use furiously blithely ');
INSERT INTO public.partsupp VALUES (192975, 2976, 7392, 751.77, ' ironic, bold instructions. deposits sleep never. slyly final dependencies integrate slyly special ');
INSERT INTO public.partsupp VALUES (64303, 4304, 5453, 479.42, 'ckages. blithely special ideas are carefully about the slyly unusual accounts. blithely r');
INSERT INTO public.partsupp VALUES (64303, 6810, 2295, 856.36, 'earls haggle busily slyly regular pinto beans. final idea');
INSERT INTO public.partsupp VALUES (9713, 9714, 422, 740.52, 'r deposits affix carefully express theodolites. regular, pending packages haggle slyly. regular warthogs haggle. even theodolites sleep carefully. ironic accounts cajole slyly. quickly even fox');
INSERT INTO public.partsupp VALUES (95770, 789, 935, 471.74, 'ithely. carefully silent accounts along the packages sleep slyly blithely special patterns. blithely regular accounts det');
INSERT INTO public.partsupp VALUES (95770, 5771, 8139, 956.35, 'ake carefully. slyly regular courts about the silent, even foxes use quickly across the slyly silent the');
INSERT INTO public.partsupp VALUES (182838, 2839, 5996, 820.35, 'le furiously unusual foxes. slyly pending deposits across the furiously regular requests detect above the evenly express accounts. carefully close requests integrat');
INSERT INTO public.partsupp VALUES (69409, 9410, 3059, 413.19, 'e special pinto beans. carefully even accounts run blithely even requests. carefully final packages according to the carefully r');
INSERT INTO public.partsupp VALUES (14654, 9657, 6301, 816.46, 'latelets wake around the packages. pending packages use furiously. theodolites are quickly. carefully special pinto beans sleep. special, silent packages hang blithely blithely fin');
INSERT INTO public.partsupp VALUES (190585, 5624, 6101, 521.93, ' sleep. even, regular accounts boost ironic, even deposits. unusu');
INSERT INTO public.partsupp VALUES (74455, 4456, 206, 929.24, 'le furiously ironic packages. furiously ironic sentiments sleep. express ideas haggle carefully. packag');
INSERT INTO public.partsupp VALUES (72572, 94, 344, 201.21, 'sleep slyly about the pending excuses. blithely final multipliers are doggedly slyly special requests. special, busy requests use about the slyly ');
INSERT INTO public.partsupp VALUES (72572, 5080, 6708, 190.53, 'posits. quickly special theodolites wake furiously. packages cajole slyly slyly ironic instructions. furiously regular accounts above the bold sentimen');
