INSERT INTO public.part VALUES (132108, 'spring burnished deep ivory peru', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY BRUSHED BRASS', 4, 'MED DRUM  ', 1140.10, 'deposits');
INSERT INTO public.part VALUES (78529, 'forest light coral frosted blanched', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD BURNISHED BRASS', 20, 'SM CASE   ', 1507.52, 'y final excuses. depen');
INSERT INTO public.part VALUES (174671, 'blanched drab plum maroon brown', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BRUSHED NICKEL', 38, 'WRAP PKG  ', 1745.67, ' furiously final idea');
INSERT INTO public.part VALUES (923, 'moccasin lace rose navajo forest', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD PLATED TIN', 26, 'WRAP CASE ', 1823.92, 'he packag');
INSERT INTO public.part VALUES (113071, 'pink chocolate goldenrod khaki spring', 'Manufacturer#2           ', 'Brand#22  ', 'ECONOMY BURNISHED NICKEL', 10, 'SM BOX    ', 1084.07, 'ts cajole slyly eve');
INSERT INTO public.part VALUES (45249, 'antique pale pink saddle lime', 'Manufacturer#1           ', 'Brand#12  ', 'MEDIUM BRUSHED COPPER', 32, 'WRAP CASE ', 1194.24, 'requests s');
INSERT INTO public.part VALUES (53489, 'steel olive green orange royal', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE POLISHED STEEL', 4, 'MED JAR   ', 1442.48, ' promise furiously ben');
INSERT INTO public.part VALUES (109292, 'gainsboro honeydew lime hot indian', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL ANODIZED NICKEL', 25, 'SM CASE   ', 1301.29, ' foxes. a');
INSERT INTO public.part VALUES (86394, 'powder grey dodger almond deep', 'Manufacturer#5           ', 'Brand#54  ', 'ECONOMY PLATED TIN', 20, 'JUMBO BOX ', 1380.39, 'le. slyly regular requ');
INSERT INTO public.part VALUES (52051, 'salmon goldenrod royal papaya aquamarine', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BRUSHED NICKEL', 34, 'MED BOX   ', 1003.05, '; wat');
INSERT INTO public.part VALUES (146700, 'slate grey sandy metallic hot', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL BRUSHED TIN', 17, 'SM PKG    ', 1746.70, 'ickly spec');
INSERT INTO public.part VALUES (155013, 'dim salmon lime slate blanched', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY PLATED NICKEL', 46, 'JUMBO BOX ', 1068.01, 'xes haggle blithe');
INSERT INTO public.part VALUES (168013, 'cornflower salmon tomato metallic blush', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY ANODIZED TIN', 50, 'SM CASE   ', 1081.01, 'as hagg');
INSERT INTO public.part VALUES (92218, 'goldenrod antique olive misty orchid', 'Manufacturer#3           ', 'Brand#35  ', 'LARGE BURNISHED COPPER', 45, 'LG CASE   ', 1210.21, ' carefully. fluffily');
INSERT INTO public.part VALUES (75327, 'beige saddle rosy brown misty', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM BURNISHED BRASS', 34, 'WRAP JAR  ', 1302.32, 'ies. e');
INSERT INTO public.part VALUES (102064, 'spring metallic forest black khaki', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD PLATED COPPER', 39, 'JUMBO CASE', 1066.06, 'eas are');
INSERT INTO public.part VALUES (146688, 'lawn tomato cream ivory blanched', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE BURNISHED BRASS', 21, 'WRAP PACK ', 1734.68, 'after the car');
INSERT INTO public.part VALUES (4201, 'linen indian lace chartreuse ghost', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE ANODIZED BRASS', 29, 'WRAP PKG  ', 1105.20, 'the blithely u');
