INSERT INTO public.part VALUES (164280, 'navy cornflower misty pale cyan', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE BRUSHED TIN', 21, 'SM DRUM   ', 1344.28, ' cajole across the b');
INSERT INTO public.part VALUES (143790, 'cornsilk plum burlywood turquoise beige', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY ANODIZED COPPER', 12, 'SM DRUM   ', 1833.79, 'ar platelets do');
INSERT INTO public.part VALUES (76403, 'puff slate ivory orchid papaya', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BRUSHED COPPER', 15, 'JUMBO CASE', 1379.40, 'ing accou');
INSERT INTO public.part VALUES (51945, 'bisque cream linen lawn plum', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE POLISHED COPPER', 44, 'JUMBO JAR ', 1896.94, 'tions cajole bl');
INSERT INTO public.part VALUES (175506, 'dark bisque magenta forest green', 'Manufacturer#5           ', 'Brand#55  ', 'MEDIUM BURNISHED COPPER', 20, 'WRAP BOX  ', 1581.50, 'ss accounts boost.');
INSERT INTO public.part VALUES (143966, 'lavender hot antique azure drab', 'Manufacturer#3           ', 'Brand#34  ', 'STANDARD POLISHED STEEL', 10, 'WRAP PKG  ', 2009.96, ' special p');
INSERT INTO public.part VALUES (170686, 'white red seashell plum cornflower', 'Manufacturer#1           ', 'Brand#13  ', 'LARGE POLISHED STEEL', 26, 'SM BAG    ', 1756.68, 's acc');
INSERT INTO public.part VALUES (191268, 'navy antique ghost deep coral', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE BRUSHED TIN', 33, 'MED CASE  ', 1359.26, 'dependenci');
INSERT INTO public.part VALUES (104723, 'sky goldenrod white smoke navajo', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BURNISHED TIN', 1, 'LG PACK   ', 1727.72, 'ully reg');
INSERT INTO public.part VALUES (168876, 'pale maroon moccasin blue honeydew', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY ANODIZED COPPER', 12, 'WRAP DRUM ', 1944.87, ' slyly along the s');
INSERT INTO public.part VALUES (160078, 'cornflower honeydew royal pink papaya', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE ANODIZED COPPER', 43, 'SM DRUM   ', 1138.07, 'reful, ');
INSERT INTO public.part VALUES (172360, 'beige lavender antique lawn moccasin', 'Manufacturer#2           ', 'Brand#24  ', 'MEDIUM ANODIZED NICKEL', 8, 'SM BAG    ', 1432.36, 'ys. unus');
INSERT INTO public.part VALUES (63625, 'pink cornsilk tan grey slate', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD PLATED TIN', 26, 'LG PKG    ', 1588.62, 'doggedly e');
INSERT INTO public.part VALUES (166952, 'ghost magenta salmon goldenrod blue', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM BURNISHED TIN', 23, 'JUMBO BAG ', 2018.95, 'ronic ho');
INSERT INTO public.part VALUES (40741, 'chartreuse deep lavender frosted purple', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BRUSHED STEEL', 48, 'SM CAN    ', 1681.74, 'sly busy pearls');
INSERT INTO public.part VALUES (13420, 'purple blanched puff frosted linen', 'Manufacturer#4           ', 'Brand#45  ', 'SMALL BURNISHED NICKEL', 7, 'WRAP BOX  ', 1333.42, 'about the dogg');
INSERT INTO public.part VALUES (41964, 'hot cream drab burnished steel', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD ANODIZED BRASS', 3, 'MED CASE  ', 1905.96, 'gedly ag');
INSERT INTO public.part VALUES (154800, 'orange white mint dodger cyan', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY BURNISHED BRASS', 40, 'MED BAG   ', 1854.80, ' fluffily against th');
INSERT INTO public.part VALUES (43844, 'orchid salmon orange pale frosted', 'Manufacturer#3           ', 'Brand#34  ', 'ECONOMY BRUSHED STEEL', 3, 'MED BOX   ', 1787.84, 'ans. ');
INSERT INTO public.part VALUES (149913, 'aquamarine snow spring navajo medium', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD PLATED STEEL', 38, 'JUMBO PACK', 1962.91, 'requests dazzl');
INSERT INTO public.part VALUES (49461, 'saddle chiffon brown wheat honeydew', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY BURNISHED TIN', 28, 'WRAP CAN  ', 1410.46, 'ress accoun');
INSERT INTO public.part VALUES (99013, 'coral red khaki frosted steel', 'Manufacturer#3           ', 'Brand#31  ', 'STANDARD POLISHED COPPER', 38, 'JUMBO JAR ', 1012.01, 'y regular');
INSERT INTO public.part VALUES (34768, 'khaki steel dodger misty orange', 'Manufacturer#1           ', 'Brand#11  ', 'STANDARD ANODIZED TIN', 6, 'SM PACK   ', 1702.76, 'luffily. blithe');
INSERT INTO public.part VALUES (118420, 'cornflower wheat light moccasin green', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BURNISHED TIN', 31, 'LG CASE   ', 1438.42, 'specia');
INSERT INTO public.part VALUES (185194, 'turquoise dodger thistle forest rosy', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL POLISHED STEEL', 39, 'LG CASE   ', 1279.19, 'olites. unusual,');
INSERT INTO public.part VALUES (150799, 'peru linen lawn light spring', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO POLISHED BRASS', 22, 'JUMBO PACK', 1849.79, ' ideas. ir');
INSERT INTO public.part VALUES (199120, 'almond white metallic turquoise seashell', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL BURNISHED COPPER', 20, 'WRAP JAR  ', 1219.12, 'jole across the caref');
INSERT INTO public.part VALUES (156383, 'navy moccasin dodger cream medium', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO ANODIZED NICKEL', 38, 'SM JAR    ', 1439.38, 'ake carefully sil');
INSERT INTO public.part VALUES (793, 'white chiffon blue green violet', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE POLISHED NICKEL', 28, 'JUMBO CAN ', 1693.79, 'tions. furiou');
INSERT INTO public.part VALUES (183510, 'navajo tan hot indian blanched', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE ANODIZED NICKEL', 17, 'SM JAR    ', 1593.51, 'fily special idea');
INSERT INTO public.part VALUES (46529, 'smoke chocolate black pale goldenrod', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD BURNISHED STEEL', 39, 'JUMBO CASE', 1475.52, 'uffily even excus');
INSERT INTO public.part VALUES (93574, 'saddle puff powder rose slate', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD ANODIZED COPPER', 12, 'LG CAN    ', 1567.57, 'nts. ');
INSERT INTO public.part VALUES (105875, 'antique hot goldenrod orange coral', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM ANODIZED COPPER', 3, 'MED BOX   ', 1880.87, 'above');
INSERT INTO public.part VALUES (107944, 'cyan white blanched saddle dark', 'Manufacturer#4           ', 'Brand#44  ', 'PROMO ANODIZED NICKEL', 21, 'MED BOX   ', 1951.94, 'to beans ');
INSERT INTO public.part VALUES (94756, 'deep almond gainsboro khaki medium', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL BRUSHED TIN', 20, 'MED CAN   ', 1750.75, 'quests c');
INSERT INTO public.part VALUES (25404, 'ivory navajo ghost indian snow', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM POLISHED BRASS', 37, 'LG DRUM   ', 1329.40, 'courts above ');
INSERT INTO public.part VALUES (28874, 'brown grey tomato chiffon peru', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM ANODIZED TIN', 6, 'JUMBO CAN ', 1802.87, 'lly even reques');
INSERT INTO public.part VALUES (75082, 'maroon plum blue tan navy', 'Manufacturer#1           ', 'Brand#15  ', 'MEDIUM POLISHED BRASS', 18, 'WRAP PKG  ', 1057.08, 'ges sleep eve');
INSERT INTO public.part VALUES (192676, 'plum white seashell bisque honeydew', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD ANODIZED NICKEL', 19, 'LG PACK   ', 1768.67, 'sly final ');
INSERT INTO public.part VALUES (25928, 'almond lavender violet slate lace', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL ANODIZED STEEL', 5, 'WRAP BOX  ', 1853.92, 'egular plat');
INSERT INTO public.part VALUES (112055, 'turquoise coral cornflower lemon blush', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE PLATED TIN', 24, 'SM PKG    ', 1067.05, 's. car');
INSERT INTO public.part VALUES (197782, 'spring smoke misty lawn snow', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL PLATED COPPER', 41, 'SM DRUM   ', 1879.78, 'structions. ironic ins');
INSERT INTO public.part VALUES (20023, 'thistle steel tomato grey metallic', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE POLISHED TIN', 48, 'WRAP JAR  ', 943.02, 'ely. furiously ');
INSERT INTO public.part VALUES (39582, 'powder pale violet indian chiffon', 'Manufacturer#4           ', 'Brand#41  ', 'LARGE ANODIZED NICKEL', 13, 'MED DRUM  ', 1521.58, 'equests. thinly un');
INSERT INTO public.part VALUES (179608, 'khaki black beige medium cornflower', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD BURNISHED NICKEL', 49, 'MED DRUM  ', 1687.60, ' special braids s');
INSERT INTO public.part VALUES (74454, 'sienna powder purple turquoise blanched', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY PLATED TIN', 16, 'SM PACK   ', 1428.45, 'l packages are furiou');
INSERT INTO public.part VALUES (161116, 'beige olive coral indian green', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM BURNISHED STEEL', 38, 'SM BAG    ', 1177.11, 'lyly silent depe');
INSERT INTO public.part VALUES (68435, 'lemon pale turquoise royal floral', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY ANODIZED NICKEL', 7, 'LG BOX    ', 1403.43, ' are en');
INSERT INTO public.part VALUES (118715, 'white honeydew steel hot indian', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO BRUSHED NICKEL', 7, 'MED BAG   ', 1733.71, 'rbits at');
INSERT INTO public.part VALUES (23632, 'beige violet olive coral lawn', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE BURNISHED TIN', 5, 'JUMBO JAR ', 1555.63, ' requests haggle regul');
INSERT INTO public.part VALUES (179929, 'brown chocolate orchid light green', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM PLATED STEEL', 46, 'JUMBO BAG ', 2008.92, 'pecial ideas nag ca');
INSERT INTO public.part VALUES (170596, 'olive lavender tomato moccasin forest', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL PLATED TIN', 43, 'LG DRUM   ', 1666.59, 'ges. furiously iron');
INSERT INTO public.part VALUES (192567, 'tan medium magenta thistle navy', 'Manufacturer#4           ', 'Brand#42  ', 'MEDIUM ANODIZED NICKEL', 17, 'WRAP PKG  ', 1659.56, 'g to the blithely b');
INSERT INTO public.part VALUES (64977, 'cornflower bisque papaya goldenrod grey', 'Manufacturer#3           ', 'Brand#33  ', 'PROMO ANODIZED NICKEL', 26, 'SM CAN    ', 1941.97, 'arefully ironic');
INSERT INTO public.part VALUES (62830, 'chiffon navy hot blue salmon', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE BURNISHED BRASS', 5, 'MED PKG   ', 1792.83, ' theodolites');
INSERT INTO public.part VALUES (148460, 'smoke steel moccasin burnished navy', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE POLISHED COPPER', 21, 'JUMBO DRUM', 1508.46, 'instruct');
INSERT INTO public.part VALUES (146004, 'midnight medium sky blue peru', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM ANODIZED STEEL', 42, 'LG BOX    ', 1050.00, 'y pending the');
INSERT INTO public.part VALUES (19675, 'wheat peach tan grey seashell', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD BURNISHED COPPER', 39, 'JUMBO CASE', 1594.67, '. ironic, iron');
INSERT INTO public.part VALUES (118273, 'magenta lemon sienna sky mint', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED NICKEL', 18, 'JUMBO DRUM', 1291.27, 'ole furiously ');
INSERT INTO public.part VALUES (40017, 'red chocolate cyan powder puff', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO BRUSHED BRASS', 25, 'LG DRUM   ', 957.01, 'ans. bol');
INSERT INTO public.part VALUES (26163, 'lace plum cyan linen drab', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY PLATED NICKEL', 42, 'SM PKG    ', 1089.16, 'posits nag');
INSERT INTO public.part VALUES (187884, 'misty cyan slate dark midnight', 'Manufacturer#1           ', 'Brand#13  ', 'LARGE BURNISHED BRASS', 11, 'JUMBO DRUM', 1971.88, 'l instr');
INSERT INTO public.part VALUES (108930, 'rose violet black lawn aquamarine', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD BRUSHED COPPER', 8, 'JUMBO CAN ', 1938.93, 'quests. final,');
INSERT INTO public.part VALUES (199682, 'rosy orchid blanched tan navy', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD ANODIZED COPPER', 25, 'SM CASE   ', 1781.68, 'ructions. ');
INSERT INTO public.part VALUES (96290, 'maroon violet white metallic olive', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD ANODIZED BRASS', 43, 'MED BOX   ', 1286.29, ' slyly against the');
INSERT INTO public.part VALUES (188262, 'honeydew almond blue floral dodger', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE PLATED NICKEL', 44, 'SM PACK   ', 1350.26, 'hely spe');
INSERT INTO public.part VALUES (192814, 'sienna cream blue coral midnight', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO POLISHED STEEL', 7, 'MED CAN   ', 1906.81, 'un about the sp');
INSERT INTO public.part VALUES (114237, 'snow metallic firebrick misty tan', 'Manufacturer#1           ', 'Brand#15  ', 'STANDARD POLISHED BRASS', 25, 'WRAP DRUM ', 1251.23, 's. furiously final ');
INSERT INTO public.part VALUES (99689, 'peru tan midnight cream misty', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM ANODIZED NICKEL', 37, 'LG BAG    ', 1688.68, 'equests could affix a');
INSERT INTO public.part VALUES (119656, 'metallic tan grey gainsboro pale', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE ANODIZED NICKEL', 35, 'LG CAN    ', 1675.65, 'ly abou');
INSERT INTO public.part VALUES (152342, 'dark chocolate pink chartreuse dodger', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED COPPER', 44, 'SM CAN    ', 1394.34, 'deas.');
INSERT INTO public.part VALUES (176097, 'blanched metallic goldenrod cyan dark', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO BURNISHED TIN', 28, 'WRAP CASE ', 1173.09, 'riously ');
INSERT INTO public.part VALUES (162142, 'midnight misty goldenrod lawn cyan', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD POLISHED TIN', 31, 'WRAP PACK ', 1204.14, 'its are slyly. ac');
INSERT INTO public.part VALUES (102609, 'saddle tomato dark ghost navajo', 'Manufacturer#3           ', 'Brand#32  ', 'SMALL POLISHED NICKEL', 49, 'LG PKG    ', 1611.60, 'e quickly foxes.');
INSERT INTO public.part VALUES (113013, 'goldenrod royal saddle turquoise red', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE PLATED COPPER', 23, 'MED JAR   ', 1026.01, 'arefully qui');
INSERT INTO public.part VALUES (67512, 'bisque navy sky navajo salmon', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE POLISHED NICKEL', 48, 'MED PACK  ', 1479.51, 'he requests. f');
INSERT INTO public.part VALUES (58288, 'slate grey hot light pale', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL POLISHED TIN', 17, 'SM JAR    ', 1246.28, 's cajole sl');
INSERT INTO public.part VALUES (68655, 'steel deep frosted almond beige', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE ANODIZED TIN', 47, 'LG JAR    ', 1623.65, 'ckly. blithely fi');
INSERT INTO public.part VALUES (156768, 'blanched indian smoke magenta gainsboro', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL POLISHED TIN', 28, 'JUMBO DRUM', 1824.76, 'ts. sl');
INSERT INTO public.part VALUES (79109, 'sky purple orchid chiffon cornsilk', 'Manufacturer#2           ', 'Brand#24  ', 'ECONOMY ANODIZED STEEL', 21, 'WRAP BOX  ', 1088.10, 'e? fl');
INSERT INTO public.part VALUES (134288, 'coral dodger spring lawn light', 'Manufacturer#5           ', 'Brand#53  ', 'ECONOMY ANODIZED STEEL', 29, 'SM CAN    ', 1322.28, 'ole according to');
INSERT INTO public.part VALUES (41661, 'dodger peach rosy firebrick floral', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM BURNISHED STEEL', 26, 'JUMBO PACK', 1602.66, 'arefull');
INSERT INTO public.part VALUES (198173, 'cream chartreuse sandy green turquoise', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD BURNISHED BRASS', 1, 'MED PACK  ', 1271.17, 'slyly re');
INSERT INTO public.part VALUES (182913, 'linen azure hot antique wheat', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD PLATED TIN', 27, 'WRAP BAG  ', 1995.91, 'heodolites. quickly');
INSERT INTO public.part VALUES (3819, 'mint sandy navajo chiffon ghost', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY ANODIZED BRASS', 6, 'SM BOX    ', 1722.81, 'usual excu');
INSERT INTO public.part VALUES (13220, 'turquoise azure lavender metallic white', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD BRUSHED STEEL', 50, 'LG BAG    ', 1133.22, 'packages. slyly unu');
INSERT INTO public.part VALUES (72825, 'cornsilk red indian black moccasin', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY ANODIZED TIN', 16, 'MED BOX   ', 1797.82, 's integrate blithely a');
INSERT INTO public.part VALUES (45059, 'floral aquamarine sienna black seashell', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY POLISHED COPPER', 43, 'SM CAN    ', 1004.05, 'ely along the ');
INSERT INTO public.part VALUES (90173, 'blue drab forest sky purple', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD ANODIZED TIN', 40, 'SM PACK   ', 1163.17, 'blith');
INSERT INTO public.part VALUES (25597, 'ivory linen metallic tan salmon', 'Manufacturer#3           ', 'Brand#34  ', 'STANDARD PLATED BRASS', 4, 'MED PKG   ', 1522.59, 'ise. ca');
INSERT INTO public.part VALUES (150457, 'dark cornsilk hot dodger honeydew', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD PLATED TIN', 21, 'SM JAR    ', 1507.45, 'inal accounts i');
INSERT INTO public.part VALUES (177284, 'tomato deep navy almond frosted', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE BURNISHED COPPER', 20, 'WRAP DRUM ', 1361.28, 'al accounts. ex');
INSERT INTO public.part VALUES (172258, 'aquamarine cornsilk lavender salmon blanched', 'Manufacturer#3           ', 'Brand#31  ', 'PROMO BRUSHED COPPER', 24, 'JUMBO DRUM', 1330.25, 'refully unusu');
INSERT INTO public.part VALUES (96615, 'peru aquamarine burnished chartreuse moccasin', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL BURNISHED NICKEL', 5, 'MED DRUM  ', 1611.61, 'quickly fi');
INSERT INTO public.part VALUES (104010, 'slate cyan gainsboro lemon aquamarine', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BRUSHED COPPER', 3, 'LG CASE   ', 1014.01, 'iously express,');
INSERT INTO public.part VALUES (174748, 'cornflower salmon hot maroon brown', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL POLISHED BRASS', 25, 'LG BOX    ', 1822.74, 'the blithely ironic de');
INSERT INTO public.part VALUES (180197, 'violet chartreuse wheat ghost cornsilk', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO ANODIZED STEEL', 7, 'LG JAR    ', 1277.19, 'nt accounts solv');
INSERT INTO public.part VALUES (144169, 'forest cornflower saddle aquamarine navajo', 'Manufacturer#4           ', 'Brand#42  ', 'LARGE BURNISHED BRASS', 19, 'LG BOX    ', 1213.16, ' accounts. caref');
INSERT INTO public.part VALUES (35821, 'forest puff rose tomato dim', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE ANODIZED STEEL', 29, 'SM BOX    ', 1756.82, 'ss ide');
INSERT INTO public.part VALUES (68449, 'blanched dark medium drab aquamarine', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BURNISHED NICKEL', 31, 'LG BAG    ', 1417.44, 'egular requests hag');
INSERT INTO public.part VALUES (65400, 'green grey firebrick sienna puff', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO PLATED TIN', 31, 'JUMBO CASE', 1365.40, 'nt slyly against');
INSERT INTO public.part VALUES (128145, 'lawn plum seashell cream yellow', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY PLATED STEEL', 9, 'MED CAN   ', 1173.14, 'structions');
INSERT INTO public.part VALUES (90202, 'plum peach magenta snow sky', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BRUSHED STEEL', 12, 'MED DRUM  ', 1192.20, 'g ideas: quietly final');
INSERT INTO public.part VALUES (135945, 'papaya light blanched ivory honeydew', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM ANODIZED STEEL', 1, 'JUMBO DRUM', 1980.94, 'pending, unusual th');
INSERT INTO public.part VALUES (135416, 'almond deep orchid beige steel', 'Manufacturer#2           ', 'Brand#24  ', 'MEDIUM POLISHED TIN', 14, 'WRAP PKG  ', 1451.41, 's according ');
INSERT INTO public.part VALUES (82554, 'peach burnished powder gainsboro violet', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY POLISHED STEEL', 16, 'SM CASE   ', 1536.55, 'y reg');
INSERT INTO public.part VALUES (115356, 'grey khaki saddle violet rosy', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM BRUSHED STEEL', 11, 'WRAP DRUM ', 1371.35, 'ourts caj');
INSERT INTO public.part VALUES (1015, 'cornflower brown rosy seashell mint', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM BRUSHED BRASS', 15, 'MED CAN   ', 916.01, 'ial deposits. acc');
INSERT INTO public.part VALUES (59721, 'navajo burlywood sienna olive cream', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD PLATED NICKEL', 5, 'MED JAR   ', 1680.72, 'ckly idle foxes ');
INSERT INTO public.part VALUES (31779, 'rose green pink brown yellow', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD BURNISHED COPPER', 34, 'MED PACK  ', 1710.77, 'efully pending accoun');
INSERT INTO public.part VALUES (133438, 'puff cream orchid lemon red', 'Manufacturer#2           ', 'Brand#21  ', 'ECONOMY POLISHED TIN', 35, 'SM JAR    ', 1471.43, 'de of the');
INSERT INTO public.part VALUES (84211, 'rosy saddle orchid medium olive', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO BRUSHED BRASS', 9, 'SM BOX    ', 1195.21, 'ss theodolites. slyly');
INSERT INTO public.part VALUES (109018, 'indian dim lemon linen plum', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BURNISHED NICKEL', 7, 'SM CAN    ', 1027.01, 'ld in');
INSERT INTO public.part VALUES (183085, 'blush mint burlywood red navy', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BURNISHED TIN', 2, 'SM PKG    ', 1168.08, 'ke according to');
INSERT INTO public.part VALUES (94103, 'aquamarine peru ghost pale honeydew', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE POLISHED TIN', 25, 'SM BOX    ', 1097.10, ' along ');
INSERT INTO public.part VALUES (199612, 'tomato navy drab lemon orchid', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO POLISHED STEEL', 13, 'LG PACK   ', 1711.61, 'inal pinto beans detec');
INSERT INTO public.part VALUES (105476, 'lawn ivory purple turquoise deep', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD BURNISHED STEEL', 44, 'LG PACK   ', 1481.47, ' across the ru');
INSERT INTO public.part VALUES (114070, 'light lime royal misty mint', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO BURNISHED STEEL', 41, 'JUMBO CASE', 1084.07, ' iron');
INSERT INTO public.part VALUES (15075, 'slate cyan dark salmon sky', 'Manufacturer#4           ', 'Brand#44  ', 'PROMO BURNISHED STEEL', 35, 'LG BOX    ', 990.07, 'ular accounts use af');
INSERT INTO public.part VALUES (40973, 'light cyan magenta lavender peach', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY ANODIZED BRASS', 36, 'JUMBO PKG ', 1913.97, 'cally ');
