INSERT INTO public.part VALUES (11111, 'thistle peach steel cornflower green', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD BURNISHED COPPER', 31, 'WRAP DRUM ', 1022.11, 'counts a');
INSERT INTO public.part VALUES (71, 'violet firebrick cream peru white', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD PLATED BRASS', 26, 'WRAP DRUM ', 971.07, ' packages alongside');
INSERT INTO public.part VALUES (141262, 'beige hot firebrick dark misty', 'Manufacturer#1           ', 'Brand#15  ', 'MEDIUM POLISHED STEEL', 22, 'SM JAR    ', 1303.26, 'haggle ruthlessly');
INSERT INTO public.part VALUES (117598, 'wheat cream light goldenrod dodger', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE BRUSHED NICKEL', 5, 'JUMBO PACK', 1615.59, 'sts haggle');
INSERT INTO public.part VALUES (133868, 'firebrick lawn orchid navajo floral', 'Manufacturer#3           ', 'Brand#34  ', 'MEDIUM BURNISHED COPPER', 15, 'SM PACK   ', 1901.86, 'structions. sl');
INSERT INTO public.part VALUES (36097, 'coral red seashell blanched azure', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE ANODIZED TIN', 26, 'JUMBO BAG ', 1033.09, 'ckly fi');
INSERT INTO public.part VALUES (115762, 'green papaya rosy blush grey', 'Manufacturer#1           ', 'Brand#12  ', 'MEDIUM BRUSHED COPPER', 5, 'MED BOX   ', 1777.76, 'the quickly pending fo');
INSERT INTO public.part VALUES (88487, 'cornflower metallic goldenrod blanched aquamarine', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD BURNISHED TIN', 21, 'LG CAN    ', 1475.48, 'y. pac');
INSERT INTO public.part VALUES (165476, 'yellow magenta chocolate purple spring', 'Manufacturer#5           ', 'Brand#55  ', 'SMALL ANODIZED COPPER', 50, 'JUMBO BAG ', 1541.47, 'posits use slyly af');
INSERT INTO public.part VALUES (51641, 'lemon purple misty royal peru', 'Manufacturer#2           ', 'Brand#23  ', 'MEDIUM PLATED TIN', 2, 'JUMBO DRUM', 1592.64, 'ly along the fluf');
INSERT INTO public.part VALUES (16957, 'sandy slate dim lime royal', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE POLISHED STEEL', 41, 'WRAP PKG  ', 1873.95, 'its nag');
INSERT INTO public.part VALUES (146933, 'drab medium purple chocolate pink', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL ANODIZED STEEL', 40, 'LG PACK   ', 1979.93, 'requests. blit');
INSERT INTO public.part VALUES (117971, 'honeydew sienna spring dodger green', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD BURNISHED COPPER', 41, 'JUMBO JAR ', 1988.97, 'of the');
INSERT INTO public.part VALUES (79864, 'steel frosted violet floral hot', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO BRUSHED COPPER', 10, 'MED CAN   ', 1843.86, 'platelets solve caref');
INSERT INTO public.part VALUES (181865, 'black burlywood cream khaki goldenrod', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY BURNISHED NICKEL', 13, 'LG BAG    ', 1946.86, 'ar packages. b');
INSERT INTO public.part VALUES (158907, 'frosted chocolate tomato grey puff', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM ANODIZED BRASS', 9, 'WRAP JAR  ', 1965.90, 'heodolites detect sly');
INSERT INTO public.part VALUES (83276, 'misty steel olive salmon cornsilk', 'Manufacturer#4           ', 'Brand#42  ', 'LARGE BURNISHED BRASS', 1, 'JUMBO BAG ', 1259.27, 'ly regular deposits ');
INSERT INTO public.part VALUES (49924, 'chiffon azure yellow peru olive', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE BRUSHED COPPER', 15, 'WRAP DRUM ', 1873.92, 's haggle across the bl');
INSERT INTO public.part VALUES (60449, 'purple cyan blush medium powder', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE BRUSHED NICKEL', 37, 'SM DRUM   ', 1409.44, 'posits c');
INSERT INTO public.part VALUES (184691, 'burlywood lime slate saddle snow', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY POLISHED STEEL', 8, 'MED JAR   ', 1775.69, 'y regular foxes. ');
INSERT INTO public.part VALUES (162578, 'spring chiffon azure hot honeydew', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD BRUSHED TIN', 19, 'MED BOX   ', 1640.57, 'riously final pinto');
INSERT INTO public.part VALUES (178874, 'tan dim dark slate ivory', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE BRUSHED STEEL', 31, 'LG BAG    ', 1952.87, 'efully ironic foxes.');
INSERT INTO public.part VALUES (51221, 'burlywood burnished midnight chiffon lime', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY BURNISHED NICKEL', 29, 'MED DRUM  ', 1172.22, 'eposits use ');
INSERT INTO public.part VALUES (71634, 'drab tan orange forest olive', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY ANODIZED TIN', 46, 'JUMBO PKG ', 1605.63, ' regular, final theo');
INSERT INTO public.part VALUES (1657, 'saddle azure sky burlywood lace', 'Manufacturer#3           ', 'Brand#33  ', 'PROMO PLATED TIN', 17, 'WRAP CASE ', 1558.65, 'ing to the furious');
INSERT INTO public.part VALUES (40958, 'dodger aquamarine chocolate tomato seashell', 'Manufacturer#3           ', 'Brand#34  ', 'SMALL BURNISHED NICKEL', 39, 'JUMBO BAG ', 1898.95, ' the carefully e');
INSERT INTO public.part VALUES (126526, 'cyan chiffon deep azure lemon', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL ANODIZED BRASS', 25, 'SM CAN    ', 1552.52, 'es cajole carefully. ');
INSERT INTO public.part VALUES (102939, 'lawn burnished thistle aquamarine moccasin', 'Manufacturer#3           ', 'Brand#34  ', 'SMALL BURNISHED COPPER', 8, 'LG CASE   ', 1941.93, ' slyly special depende');
INSERT INTO public.part VALUES (14146, 'lavender black orange magenta frosted', 'Manufacturer#1           ', 'Brand#13  ', 'SMALL BURNISHED NICKEL', 10, 'JUMBO CAN ', 1060.14, 'oss the ');
INSERT INTO public.part VALUES (60092, 'dark violet rose pink goldenrod', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BRUSHED COPPER', 44, 'JUMBO PACK', 1052.09, 'ic theodolite');
INSERT INTO public.part VALUES (197372, 'lime honeydew puff lace dark', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD ANODIZED NICKEL', 47, 'LG CAN    ', 1469.37, 'ly slowly final ac');
INSERT INTO public.part VALUES (98395, 'green blanched azure violet saddle', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE ANODIZED COPPER', 8, 'WRAP CASE ', 1393.39, 'ully even requests nag');
INSERT INTO public.part VALUES (54836, 'khaki peach dodger blanched ghost', 'Manufacturer#4           ', 'Brand#41  ', 'LARGE BURNISHED STEEL', 49, 'LG BOX    ', 1790.83, 'lyly brave ide');
INSERT INTO public.part VALUES (157401, 'violet steel sienna medium spring', 'Manufacturer#5           ', 'Brand#53  ', 'ECONOMY BURNISHED NICKEL', 45, 'LG DRUM   ', 1458.40, 'al foxes serve caref');
