INSERT INTO public.part VALUES (193417, 'grey navajo rose black cornflower', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL POLISHED TIN', 19, 'LG DRUM   ', 1510.41, 'nusual instruction');
INSERT INTO public.part VALUES (93774, 'frosted purple aquamarine linen light', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE PLATED COPPER', 12, 'WRAP BOX  ', 1767.77, 'hins run');
INSERT INTO public.part VALUES (17001, 'lime light salmon royal olive', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD POLISHED TIN', 19, 'WRAP JAR  ', 918.00, ' furi');
INSERT INTO public.part VALUES (164039, 'green thistle cornflower yellow light', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE PLATED TIN', 5, 'JUMBO BAG ', 1103.03, 'ss th');
INSERT INTO public.part VALUES (154689, 'dim ghost goldenrod cornsilk navajo', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD BRUSHED COPPER', 46, 'LG JAR    ', 1743.68, 'eposits');
INSERT INTO public.part VALUES (18747, 'midnight dark smoke beige metallic', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM POLISHED STEEL', 8, 'LG PKG    ', 1665.74, ' the car');
INSERT INTO public.part VALUES (155190, 'chocolate lace cornflower rosy light', 'Manufacturer#4           ', 'Brand#44  ', 'PROMO BRUSHED NICKEL', 9, 'JUMBO JAR ', 1245.19, 'sly unusual orbits use');
INSERT INTO public.part VALUES (73478, 'light hot peach peru honeydew', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM POLISHED NICKEL', 1, 'JUMBO DRUM', 1451.47, 'equest');
INSERT INTO public.part VALUES (167468, 'burnished antique sky cream blue', 'Manufacturer#4           ', 'Brand#45  ', 'SMALL BURNISHED STEEL', 40, 'JUMBO PACK', 1535.46, 'ly even asy');
INSERT INTO public.part VALUES (171986, 'sandy beige midnight lavender steel', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM BURNISHED COPPER', 47, 'SM PKG    ', 2057.98, 'requests. blithe r');
INSERT INTO public.part VALUES (140022, 'azure grey burnished lavender pale', 'Manufacturer#2           ', 'Brand#23  ', 'MEDIUM BRUSHED TIN', 29, 'MED CAN   ', 1062.02, 'sts are quickly acr');
INSERT INTO public.part VALUES (82446, 'moccasin chartreuse sienna blush tomato', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL BRUSHED BRASS', 40, 'SM PKG    ', 1428.44, 'blithely');
INSERT INTO public.part VALUES (13067, 'forest smoke orchid goldenrod navy', 'Manufacturer#4           ', 'Brand#43  ', 'PROMO ANODIZED NICKEL', 45, 'LG BAG    ', 980.06, 'ronic');
INSERT INTO public.part VALUES (62384, 'sienna honeydew frosted navajo azure', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM BRUSHED COPPER', 15, 'WRAP CAN  ', 1346.38, 'blithely. special pi');
INSERT INTO public.part VALUES (116105, 'moccasin grey saddle blue cornsilk', 'Manufacturer#1           ', 'Brand#13  ', 'LARGE PLATED COPPER', 35, 'MED PACK  ', 1121.10, ' blithely ');
INSERT INTO public.part VALUES (191652, 'orchid burlywood steel lavender wheat', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO BURNISHED BRASS', 21, 'MED BOX   ', 1743.65, 'ajole slyly about th');
INSERT INTO public.part VALUES (43652, 'navy tomato midnight pale lawn', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY PLATED NICKEL', 46, 'JUMBO PKG ', 1595.65, '. pending dep');
INSERT INTO public.part VALUES (109996, 'royal steel navajo red drab', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM BURNISHED NICKEL', 26, 'WRAP PACK ', 2005.99, 'gular requests solve');
INSERT INTO public.part VALUES (71165, 'dodger tan chiffon purple beige', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM BRUSHED BRASS', 11, 'MED CASE  ', 1136.16, 'counts detect slyl');
INSERT INTO public.part VALUES (120258, 'floral medium seashell hot grey', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD PLATED STEEL', 9, 'MED PKG   ', 1278.25, 's. spec');
INSERT INTO public.part VALUES (109844, 'blue forest floral wheat orchid', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY BURNISHED NICKEL', 16, 'JUMBO JAR ', 1853.84, ' could ');
INSERT INTO public.part VALUES (86336, 'cream cornflower peach lace red', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL BURNISHED NICKEL', 16, 'MED PACK  ', 1322.33, 'odolites ar');
INSERT INTO public.part VALUES (111022, 'sienna red seashell almond papaya', 'Manufacturer#4           ', 'Brand#43  ', 'PROMO BRUSHED COPPER', 11, 'JUMBO BAG ', 1033.02, 'uriously regular co');
INSERT INTO public.part VALUES (171374, 'tomato aquamarine papaya almond peach', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD ANODIZED STEEL', 5, 'WRAP PACK ', 1445.37, 'ies cajole quickl');
INSERT INTO public.part VALUES (74280, 'tan chartreuse light indian almond', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL POLISHED BRASS', 1, 'JUMBO BOX ', 1254.28, ' accounts detect. i');
INSERT INTO public.part VALUES (68603, 'red tomato smoke peach thistle', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL BRUSHED NICKEL', 16, 'SM CAN    ', 1571.60, 'to be');
INSERT INTO public.part VALUES (12562, 'rose tan orchid magenta lemon', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY ANODIZED BRASS', 25, 'JUMBO PACK', 1474.56, 'quickly');
INSERT INTO public.part VALUES (159991, 'dark goldenrod spring moccasin yellow', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE BRUSHED TIN', 27, 'MED CASE  ', 2050.99, 's. fluffily ');
INSERT INTO public.part VALUES (76671, 'gainsboro firebrick forest coral snow', 'Manufacturer#4           ', 'Brand#43  ', 'PROMO BRUSHED COPPER', 24, 'SM DRUM   ', 1647.67, 'nic pinto beans. i');
INSERT INTO public.part VALUES (143421, 'lavender medium chocolate aquamarine dark', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM BRUSHED COPPER', 45, 'LG PACK   ', 1464.42, ' pending tithes wil');
INSERT INTO public.part VALUES (30807, 'gainsboro cyan plum honeydew burnished', 'Manufacturer#2           ', 'Brand#24  ', 'ECONOMY POLISHED STEEL', 1, 'SM DRUM   ', 1737.80, 'ray furiously');
INSERT INTO public.part VALUES (111231, 'indian maroon khaki salmon metallic', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL POLISHED COPPER', 15, 'LG CASE   ', 1242.23, 's. blithel');
INSERT INTO public.part VALUES (23793, 'coral metallic peru gainsboro purple', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO BRUSHED NICKEL', 25, 'WRAP CASE ', 1716.79, 'ct furiously furiou');
INSERT INTO public.part VALUES (14758, 'papaya wheat blush tomato magenta', 'Manufacturer#1           ', 'Brand#11  ', 'MEDIUM ANODIZED TIN', 20, 'WRAP PACK ', 1672.75, 'counts. ir');
INSERT INTO public.part VALUES (18418, 'dodger seashell rosy smoke aquamarine', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD ANODIZED BRASS', 30, 'JUMBO PKG ', 1336.41, 'beans wake. iron');
