INSERT INTO public.part VALUES (91187, 'rosy light powder drab cyan', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD POLISHED NICKEL', 46, 'SM CAN    ', 1178.18, ' against the regu');
INSERT INTO public.part VALUES (155432, 'antique salmon steel cyan beige', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO BRUSHED TIN', 14, 'LG BOX    ', 1487.43, 'xes. fi');
INSERT INTO public.part VALUES (76016, 'peach papaya indian saddle snow', 'Manufacturer#3           ', 'Brand#34  ', 'MEDIUM POLISHED NICKEL', 15, 'MED CAN   ', 992.01, 'sual th');
INSERT INTO public.part VALUES (52770, 'navajo chiffon turquoise yellow azure', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM ANODIZED NICKEL', 44, 'SM BAG    ', 1722.77, ' cajole s');
INSERT INTO public.part VALUES (194470, 'burnished blush bisque peru cornsilk', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BURNISHED TIN', 47, 'WRAP JAR  ', 1564.47, 'ccounts. slyly');
INSERT INTO public.part VALUES (172837, 'sandy powder khaki saddle salmon', 'Manufacturer#4           ', 'Brand#44  ', 'PROMO BURNISHED BRASS', 50, 'WRAP CASE ', 1909.83, 'ns. sly');
INSERT INTO public.part VALUES (191852, 'misty ivory seashell dodger indian', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE PLATED NICKEL', 33, 'JUMBO JAR ', 1943.85, ' beans wa');
INSERT INTO public.part VALUES (134418, 'olive black purple chocolate puff', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE ANODIZED NICKEL', 47, 'JUMBO PKG ', 1452.41, 'old acco');
INSERT INTO public.part VALUES (55336, 'spring bisque grey olive firebrick', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BRUSHED NICKEL', 8, 'WRAP PACK ', 1291.33, ' special ');
INSERT INTO public.part VALUES (127104, 'ivory coral red smoke orchid', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BURNISHED TIN', 41, 'MED BAG   ', 1131.10, '. even, sp');
INSERT INTO public.part VALUES (87855, 'papaya medium lemon dodger puff', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM PLATED STEEL', 35, 'WRAP PACK ', 1842.85, 'ages affix f');
INSERT INTO public.part VALUES (11648, 'peru deep indian mint hot', 'Manufacturer#2           ', 'Brand#22  ', 'ECONOMY PLATED TIN', 17, 'SM CAN    ', 1559.64, ' carefully regular th');
INSERT INTO public.part VALUES (8834, 'metallic burnished maroon lemon forest', 'Manufacturer#2           ', 'Brand#21  ', 'ECONOMY ANODIZED BRASS', 30, 'MED CAN   ', 1742.83, ' about the sometimes ');
INSERT INTO public.part VALUES (183576, 'navajo saddle gainsboro magenta azure', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY PLATED TIN', 44, 'JUMBO JAR ', 1659.57, 'sual orbits. final, f');
INSERT INTO public.part VALUES (68969, 'royal navy beige firebrick aquamarine', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE ANODIZED BRASS', 30, 'MED CAN   ', 1937.96, 'thely slyly regular pi');
INSERT INTO public.part VALUES (191052, 'lawn ivory cream maroon spring', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM ANODIZED STEEL', 2, 'WRAP PKG  ', 1143.05, 'bold platelets. fu');
INSERT INTO public.part VALUES (126135, 'antique cornflower puff lawn firebrick', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM BURNISHED BRASS', 12, 'MED PACK  ', 1161.13, 'slyly unusual foxes ');
INSERT INTO public.part VALUES (173430, 'orchid lime dark thistle azure', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD BRUSHED STEEL', 19, 'SM DRUM   ', 1503.43, 'le furiously. car');
INSERT INTO public.part VALUES (148696, 'salmon almond powder sienna cyan', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BRUSHED BRASS', 42, 'MED DRUM  ', 1744.69, 'c reques');
INSERT INTO public.part VALUES (44211, 'khaki bisque moccasin dodger deep', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO POLISHED BRASS', 33, 'LG CASE   ', 1155.21, 'ns. carefully regul');
INSERT INTO public.part VALUES (5722, 'chiffon blanched thistle khaki puff', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BURNISHED BRASS', 45, 'WRAP BOX  ', 1627.72, 'thely pending d');
INSERT INTO public.part VALUES (62610, 'snow honeydew dim rosy tomato', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY BRUSHED NICKEL', 2, 'JUMBO JAR ', 1572.61, '. spe');
INSERT INTO public.part VALUES (140739, 'orange puff medium tomato burlywood', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM BURNISHED TIN', 35, 'WRAP PACK ', 1779.73, 'he regular pinto ');
INSERT INTO public.part VALUES (192589, 'navajo honeydew lawn brown goldenrod', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL ANODIZED TIN', 28, 'WRAP PACK ', 1681.58, 'onic, ironic excuses');
INSERT INTO public.part VALUES (35667, 'peru cornsilk deep light lime', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD PLATED TIN', 30, 'JUMBO CAN ', 1602.66, 'sly slyl');
INSERT INTO public.part VALUES (62747, 'black blush grey tomato navajo', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL POLISHED COPPER', 30, 'LG PACK   ', 1709.74, 'aggle b');
INSERT INTO public.part VALUES (44137, 'yellow dodger grey pink red', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY BURNISHED STEEL', 14, 'JUMBO DRUM', 1081.13, 'arhorses poach accordi');
INSERT INTO public.part VALUES (127942, 'drab floral chocolate brown frosted', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE ANODIZED COPPER', 5, 'MED JAR   ', 1969.94, 'uternes sleep al');
INSERT INTO public.part VALUES (179269, 'beige peru dark turquoise smoke', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE BURNISHED TIN', 40, 'WRAP BOX  ', 1348.26, 'blithe packages. ca');
INSERT INTO public.part VALUES (121186, 'drab dim mint tomato grey', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL PLATED STEEL', 2, 'JUMBO CASE', 1207.18, 'se idle requests. qui');
INSERT INTO public.part VALUES (57029, 'papaya almond lime olive royal', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO PLATED NICKEL', 40, 'WRAP DRUM ', 986.02, 'sublate car');
INSERT INTO public.part VALUES (176141, 'pale mint chocolate snow peru', 'Manufacturer#3           ', 'Brand#34  ', 'ECONOMY BRUSHED STEEL', 43, 'WRAP PKG  ', 1217.14, 'pecial theodol');
INSERT INTO public.part VALUES (10073, 'aquamarine misty papaya red lavender', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM ANODIZED COPPER', 24, 'SM PKG    ', 983.07, 'al requests. sly');
INSERT INTO public.part VALUES (7564, 'orchid coral violet powder spring', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY BURNISHED STEEL', 5, 'MED BOX   ', 1471.56, 'ly alongs');
INSERT INTO public.part VALUES (27596, 'ivory metallic lavender khaki sienna', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY ANODIZED NICKEL', 5, 'SM BOX    ', 1523.59, 'ial excuses. regu');
INSERT INTO public.part VALUES (176793, 'bisque navy black magenta sky', 'Manufacturer#2           ', 'Brand#21  ', 'ECONOMY ANODIZED COPPER', 24, 'MED JAR   ', 1869.79, 'nding p');
INSERT INTO public.part VALUES (30692, 'black burlywood lavender almond tomato', 'Manufacturer#1           ', 'Brand#15  ', 'MEDIUM BURNISHED COPPER', 35, 'SM JAR    ', 1622.69, 'ickly expres');
INSERT INTO public.part VALUES (129237, 'tomato chiffon light powder magenta', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD POLISHED TIN', 12, 'MED BAG   ', 1266.23, 'e slyly final, specia');
INSERT INTO public.part VALUES (72841, 'hot snow sandy violet goldenrod', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO ANODIZED STEEL', 20, 'WRAP PACK ', 1813.84, 's. blithely un');
INSERT INTO public.part VALUES (7194, 'dodger pink tomato sky olive', 'Manufacturer#3           ', 'Brand#34  ', 'MEDIUM POLISHED COPPER', 34, 'SM BOX    ', 1101.19, 'e even grouches. furio');
