INSERT INTO public.part VALUES (126367, 'rosy lawn lemon linen hot', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO PLATED NICKEL', 33, 'LG PACK   ', 1393.36, ' slyly eve');
INSERT INTO public.part VALUES (155731, 'tan deep green sky hot', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE BRUSHED NICKEL', 27, 'WRAP BOX  ', 1786.73, 'unts snooze ');
INSERT INTO public.part VALUES (164257, 'dim blue plum linen cornsilk', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE POLISHED NICKEL', 18, 'WRAP PKG  ', 1321.25, 'dly. ');
INSERT INTO public.part VALUES (75924, 'almond mint peru medium maroon', 'Manufacturer#4           ', 'Brand#45  ', 'SMALL BRUSHED TIN', 25, 'MED BOX   ', 1899.92, 'platelets. ir');
INSERT INTO public.part VALUES (177792, 'yellow burnished sienna midnight rose', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL PLATED BRASS', 13, 'MED CAN   ', 1869.79, ' regular');
INSERT INTO public.part VALUES (143047, 'papaya cyan metallic frosted grey', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE PLATED NICKEL', 36, 'SM CAN    ', 1090.04, 'dolites. eve');
INSERT INTO public.part VALUES (17882, 'olive sky dodger moccasin puff', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE BURNISHED NICKEL', 4, 'JUMBO PACK', 1799.88, 'sts use quickly abou');
INSERT INTO public.part VALUES (105522, 'cornsilk spring peach cream goldenrod', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL PLATED TIN', 6, 'WRAP PACK ', 1527.52, ' asymptotes amon');
INSERT INTO public.part VALUES (50811, 'khaki lawn lavender seashell pink', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM BRUSHED STEEL', 17, 'MED CAN   ', 1761.81, 'egular');
INSERT INTO public.part VALUES (176083, 'cornflower sandy orchid rose black', 'Manufacturer#3           ', 'Brand#34  ', 'SMALL PLATED STEEL', 25, 'LG CASE   ', 1159.08, 'n, re');
INSERT INTO public.part VALUES (108949, 'cyan medium light grey brown', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO POLISHED BRASS', 17, 'SM CASE   ', 1957.94, 'eodolites integrat');
INSERT INTO public.part VALUES (185668, 'navajo olive medium cornflower misty', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO POLISHED COPPER', 18, 'SM CASE   ', 1753.66, 'e bli');
INSERT INTO public.part VALUES (162989, 'snow slate moccasin black brown', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY BRUSHED STEEL', 23, 'LG BOX    ', 2051.98, 'deas. pending reque');
INSERT INTO public.part VALUES (110992, 'orange frosted magenta midnight chocolate', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD BRUSHED TIN', 37, 'WRAP PACK ', 2002.99, 'g abov');
INSERT INTO public.part VALUES (46559, 'lavender coral rosy mint papaya', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD BRUSHED TIN', 6, 'MED PACK  ', 1505.55, 'the ca');
INSERT INTO public.part VALUES (188329, 'black sky light tan wheat', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY POLISHED STEEL', 25, 'LG JAR    ', 1417.32, 'mptotes. boldly ir');
INSERT INTO public.part VALUES (64017, 'goldenrod azure lime navy orchid', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD ANODIZED TIN', 5, 'MED PACK  ', 981.01, 'lithely c');
INSERT INTO public.part VALUES (114724, 'floral antique cornsilk thistle black', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM ANODIZED BRASS', 24, 'LG PKG    ', 1738.72, 'ages. blithely car');
INSERT INTO public.part VALUES (65173, 'smoke turquoise misty drab indian', 'Manufacturer#2           ', 'Brand#21  ', 'ECONOMY PLATED BRASS', 26, 'JUMBO CASE', 1138.17, 'forges. carefully iron');
INSERT INTO public.part VALUES (158517, 'dim cream dodger maroon tomato', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM BRUSHED BRASS', 8, 'JUMBO PKG ', 1575.51, 'busy,');
INSERT INTO public.part VALUES (134305, 'peach brown burlywood pale green', 'Manufacturer#1           ', 'Brand#11  ', 'SMALL PLATED TIN', 35, 'MED PKG   ', 1339.30, ' haggl');
INSERT INTO public.part VALUES (22068, 'rosy navajo peach metallic beige', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO ANODIZED TIN', 42, 'WRAP CASE ', 990.06, 'ckly unusual package');
INSERT INTO public.part VALUES (175708, 'purple moccasin orange indian tan', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM POLISHED NICKEL', 26, 'WRAP PACK ', 1783.70, 'ose. doggedly final ');
INSERT INTO public.part VALUES (182190, 'medium rosy navy red cornsilk', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY POLISHED NICKEL', 10, 'SM PKG    ', 1272.19, 'y special req');
INSERT INTO public.part VALUES (196712, 'rosy light black pink orange', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO ANODIZED COPPER', 4, 'LG BAG    ', 1808.71, 'luffily;');
INSERT INTO public.part VALUES (8024, 'misty light saddle thistle lime', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE PLATED BRASS', 27, 'LG BOX    ', 932.02, 's use slyly e');
INSERT INTO public.part VALUES (89780, 'wheat purple slate lace cream', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY BRUSHED COPPER', 19, 'SM CAN    ', 1769.78, 'ven accounts. pen');
INSERT INTO public.part VALUES (197849, 'navajo blue red aquamarine maroon', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL ANODIZED TIN', 26, 'SM CASE   ', 1946.84, 'unusual requests.');
INSERT INTO public.part VALUES (196586, 'navy turquoise spring blanched sienna', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY BURNISHED STEEL', 38, 'JUMBO BOX ', 1682.58, 'ependencies');
INSERT INTO public.part VALUES (190407, 'cream midnight aquamarine green violet', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL PLATED NICKEL', 24, 'MED CASE  ', 1497.40, 'y iro');
INSERT INTO public.part VALUES (9775, 'papaya khaki cornsilk lawn maroon', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD BRUSHED NICKEL', 23, 'JUMBO CAN ', 1684.77, 'quiet, thi');
INSERT INTO public.part VALUES (79403, 'light antique saddle red azure', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL PLATED STEEL', 16, 'MED BAG   ', 1382.40, 'onic account');
INSERT INTO public.part VALUES (181354, 'floral dark dim seashell peach', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO BRUSHED STEEL', 8, 'MED BAG   ', 1435.35, 'g req');
INSERT INTO public.part VALUES (168208, 'rosy navy olive smoke bisque', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO PLATED TIN', 21, 'MED DRUM  ', 1276.20, 'sual ideas');
INSERT INTO public.part VALUES (176606, 'firebrick salmon saddle thistle floral', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY ANODIZED TIN', 21, 'MED DRUM  ', 1682.60, 'the fina');
INSERT INTO public.part VALUES (36550, 'cornflower cyan lime steel black', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BURNISHED COPPER', 13, 'LG JAR    ', 1486.55, 'dolites. si');
INSERT INTO public.part VALUES (192975, 'tan white puff misty deep', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO BRUSHED TIN', 26, 'JUMBO CASE', 2067.97, 'ly ironic foxe');
INSERT INTO public.part VALUES (64303, 'linen deep dark plum navy', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BRUSHED COPPER', 35, 'MED PKG   ', 1267.30, 'r the ');
INSERT INTO public.part VALUES (9713, 'cornflower coral lime plum turquoise', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL ANODIZED STEEL', 47, 'WRAP PKG  ', 1622.71, 's cajol');
INSERT INTO public.part VALUES (95770, 'maroon peach rosy rose spring', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL BURNISHED BRASS', 46, 'JUMBO JAR ', 1765.77, 'ions. sly');
INSERT INTO public.part VALUES (182838, 'dim cornsilk burlywood slate powder', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO ANODIZED TIN', 15, 'MED CAN   ', 1920.83, 'oldly q');
INSERT INTO public.part VALUES (69409, 'wheat spring plum beige honeydew', 'Manufacturer#5           ', 'Brand#53  ', 'ECONOMY ANODIZED BRASS', 36, 'JUMBO CAN ', 1378.40, 'uriously instructions.');
INSERT INTO public.part VALUES (14654, 'drab floral pink brown papaya', 'Manufacturer#4           ', 'Brand#41  ', 'LARGE BURNISHED BRASS', 42, 'LG CASE   ', 1568.65, 'g, ironic pint');
INSERT INTO public.part VALUES (190585, 'cornsilk azure cyan sienna lime', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL PLATED STEEL', 1, 'SM CASE   ', 1675.58, 'accounts.');
INSERT INTO public.part VALUES (74455, 'lawn white almond grey brown', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY POLISHED TIN', 42, 'LG PACK   ', 1429.45, 'iously bold h');
INSERT INTO public.part VALUES (72572, 'blanched steel medium orange thistle', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL PLATED NICKEL', 36, 'WRAP CAN  ', 1544.57, 'ing requests a');
INSERT INTO public.part VALUES (88996, 'moccasin cyan honeydew rosy seashell', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY PLATED TIN', 13, 'LG PKG    ', 1984.99, 'ly according to the ');
