INSERT INTO public.part VALUES (57869, 'tan cyan white saddle blue', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BURNISHED BRASS', 9, 'LG CASE   ', 1826.86, 'e carefully af');
INSERT INTO public.part VALUES (183890, 'violet lace firebrick dark blue', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO PLATED STEEL', 3, 'MED BAG   ', 1973.89, 'ly silent instructi');
INSERT INTO public.part VALUES (186953, 'spring rose midnight brown dodger', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY PLATED NICKEL', 42, 'MED DRUM  ', 2039.95, 'furiously regular');
INSERT INTO public.part VALUES (72340, 'tomato lavender medium midnight peach', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD BURNISHED COPPER', 30, 'MED PACK  ', 1312.34, 'riously ir');
INSERT INTO public.part VALUES (742, 'dodger cream snow pink floral', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD BRUSHED NICKEL', 30, 'SM PACK   ', 1642.74, 'out the furiously');
INSERT INTO public.part VALUES (56934, 'misty beige purple papaya seashell', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY BRUSHED BRASS', 4, 'JUMBO CAN ', 1890.93, 'ending instructio');
INSERT INTO public.part VALUES (97079, 'bisque brown white lavender beige', 'Manufacturer#4           ', 'Brand#43  ', 'SMALL ANODIZED TIN', 49, 'MED JAR   ', 1076.07, 'bove the i');
INSERT INTO public.part VALUES (76842, 'ghost ivory burlywood deep royal', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM ANODIZED BRASS', 17, 'MED BOX   ', 1818.84, 'ng platelets p');
INSERT INTO public.part VALUES (103557, 'lime orchid cyan blush violet', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY POLISHED STEEL', 26, 'WRAP BOX  ', 1560.55, 'slyly ironic');
INSERT INTO public.part VALUES (67035, 'thistle grey deep beige brown', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD ANODIZED STEEL', 35, 'WRAP JAR  ', 1002.03, 'sts was slyly ');
INSERT INTO public.part VALUES (61780, 'steel sienna puff light firebrick', 'Manufacturer#5           ', 'Brand#54  ', 'SMALL POLISHED COPPER', 30, 'LG PACK   ', 1741.78, 'ses w');
INSERT INTO public.part VALUES (70541, 'floral metallic green saddle burlywood', 'Manufacturer#1           ', 'Brand#13  ', 'SMALL PLATED BRASS', 25, 'MED JAR   ', 1511.54, ' deposits use quickl');
INSERT INTO public.part VALUES (108896, 'honeydew blue linen violet smoke', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE BURNISHED NICKEL', 16, 'WRAP PACK ', 1904.89, 'inal ideas along the c');
INSERT INTO public.part VALUES (59441, 'royal navy powder violet cornsilk', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO ANODIZED BRASS', 27, 'JUMBO BAG ', 1400.44, 'kages across the t');
INSERT INTO public.part VALUES (175532, 'maroon blush grey navy blue', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY BURNISHED TIN', 43, 'WRAP CASE ', 1607.53, 'sily even acco');
INSERT INTO public.part VALUES (6342, 'navy puff olive hot violet', 'Manufacturer#5           ', 'Brand#54  ', 'ECONOMY BRUSHED BRASS', 30, 'MED CAN   ', 1248.34, 'slyly unusual asymp');
INSERT INTO public.part VALUES (50768, 'lawn powder dodger peru pale', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM ANODIZED STEEL', 35, 'MED PACK  ', 1718.76, 'ng accounts in');
INSERT INTO public.part VALUES (62617, 'rose almond lime bisque tan', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD PLATED STEEL', 2, 'LG JAR    ', 1579.61, 'gainst the iron');
INSERT INTO public.part VALUES (99383, 'rosy dark goldenrod blue magenta', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM ANODIZED TIN', 30, 'WRAP DRUM ', 1382.38, 'tipliers! regular, pen');
INSERT INTO public.part VALUES (75137, 'slate cyan maroon cream metallic', 'Manufacturer#2           ', 'Brand#22  ', 'ECONOMY BURNISHED COPPER', 42, 'LG BOX    ', 1112.13, 's sentiments. pinto ');
INSERT INTO public.part VALUES (46416, 'white lace indian black peru', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD BRUSHED STEEL', 35, 'SM JAR    ', 1362.41, 'lites. blit');
INSERT INTO public.part VALUES (2094, 'cyan smoke peach violet black', 'Manufacturer#2           ', 'Brand#24  ', 'MEDIUM BRUSHED STEEL', 49, 'MED CAN   ', 996.09, 'y ironic');
INSERT INTO public.part VALUES (114859, 'bisque lemon light saddle thistle', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL POLISHED BRASS', 39, 'JUMBO CASE', 1873.85, 'egular idea');
INSERT INTO public.part VALUES (152116, 'violet papaya peach cornsilk khaki', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY BRUSHED NICKEL', 7, 'SM BOX    ', 1168.11, 'y final package');
INSERT INTO public.part VALUES (198896, 'indian linen honeydew rose cornflower', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL POLISHED COPPER', 40, 'MED CAN   ', 1994.89, 'se. quickl');
INSERT INTO public.part VALUES (198090, 'peach medium firebrick black misty', 'Manufacturer#1           ', 'Brand#11  ', 'ECONOMY PLATED STEEL', 1, 'WRAP JAR  ', 1188.09, 'al ideas. ironic, e');
INSERT INTO public.part VALUES (42302, 'turquoise orchid frosted firebrick medium', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE ANODIZED NICKEL', 13, 'SM BAG    ', 1244.30, 's. final pinto');
INSERT INTO public.part VALUES (17827, 'misty firebrick antique midnight slate', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY ANODIZED TIN', 16, 'MED JAR   ', 1744.82, 'accounts.');
INSERT INTO public.part VALUES (176823, 'pink firebrick cornflower ivory floral', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE ANODIZED BRASS', 32, 'WRAP BAG  ', 1899.82, 'anently bold packag');
INSERT INTO public.part VALUES (135104, 'gainsboro magenta hot wheat beige', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY BRUSHED TIN', 12, 'JUMBO DRUM', 1139.10, 'uests');
INSERT INTO public.part VALUES (159479, 'dark burnished grey antique chocolate', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM BRUSHED NICKEL', 24, 'WRAP BOX  ', 1538.47, 'pending theodolites. s');
INSERT INTO public.part VALUES (167623, 'papaya firebrick cyan navy dark', 'Manufacturer#2           ', 'Brand#24  ', 'ECONOMY ANODIZED TIN', 13, 'LG BOX    ', 1690.62, 'le slyly accordi');
INSERT INTO public.part VALUES (164416, 'blanched peach pink royal orange', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM PLATED TIN', 31, 'WRAP CASE ', 1480.41, 'symptotes');
INSERT INTO public.part VALUES (66678, 'black linen azure misty rosy', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY BRUSHED TIN', 2, 'SM BAG    ', 1644.67, 'xpress inst');
INSERT INTO public.part VALUES (1348, 'powder medium lace dodger honeydew', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY ANODIZED BRASS', 47, 'JUMBO BAG ', 1249.34, 'ove the regular, ironi');
INSERT INTO public.part VALUES (193342, 'dodger tomato cream grey peru', 'Manufacturer#5           ', 'Brand#55  ', 'SMALL PLATED STEEL', 37, 'WRAP BAG  ', 1435.34, 'nag qui');
INSERT INTO public.part VALUES (33406, 'forest misty puff red medium', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE PLATED TIN', 28, 'LG PKG    ', 1339.40, ' final th');
INSERT INTO public.part VALUES (31082, 'seashell coral mint khaki royal', 'Manufacturer#2           ', 'Brand#24  ', 'SMALL ANODIZED TIN', 38, 'LG CASE   ', 1013.08, 'e furiously expre');
INSERT INTO public.part VALUES (166378, 'antique drab lawn maroon ghost', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD ANODIZED TIN', 14, 'SM JAR    ', 1444.37, 'requests haggle sly');
INSERT INTO public.part VALUES (139598, 'ivory plum azure drab burnished', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY ANODIZED COPPER', 39, 'LG PKG    ', 1637.59, 'otes wake flu');
INSERT INTO public.part VALUES (6063, 'pale plum aquamarine violet cornflower', 'Manufacturer#2           ', 'Brand#23  ', 'PROMO ANODIZED TIN', 28, 'SM BAG    ', 969.06, 'y unus');
INSERT INTO public.part VALUES (166436, 'chartreuse papaya chiffon lavender cornsilk', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD BURNISHED COPPER', 10, 'LG DRUM   ', 1502.43, 'cial requ');
INSERT INTO public.part VALUES (167654, 'salmon lace frosted ivory cornsilk', 'Manufacturer#2           ', 'Brand#25  ', 'SMALL BURNISHED TIN', 48, 'JUMBO CASE', 1721.65, 'ly. slyly ironic instr');
INSERT INTO public.part VALUES (147193, 'spring midnight blush purple burlywood', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL POLISHED BRASS', 23, 'SM BAG    ', 1240.19, 'about the fluffily ');
INSERT INTO public.part VALUES (93093, 'grey lavender wheat olive medium', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY PLATED BRASS', 1, 'LG BOX    ', 1086.09, 'eposits: fur');
INSERT INTO public.part VALUES (36454, 'chocolate navajo green violet snow', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM PLATED NICKEL', 6, 'SM PKG    ', 1390.45, 'uests. carefully u');
INSERT INTO public.part VALUES (36786, 'snow azure steel smoke royal', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BURNISHED NICKEL', 25, 'LG CASE   ', 1722.78, '. blithe');
INSERT INTO public.part VALUES (150873, 'lavender smoke drab saddle almond', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL BRUSHED STEEL', 28, 'LG CASE   ', 1923.87, 'ggle furiousl');
INSERT INTO public.part VALUES (4208, 'grey linen tan blue dodger', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO PLATED STEEL', 13, 'SM CAN    ', 1112.20, 's. furiously slow');
INSERT INTO public.part VALUES (22920, 'frosted drab steel medium rosy', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL PLATED BRASS', 49, 'JUMBO CAN ', 1842.92, 'ch blithely re');
INSERT INTO public.part VALUES (46640, 'lemon rosy violet navy lavender', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD POLISHED TIN', 20, 'WRAP BOX  ', 1586.64, 'unts d');
INSERT INTO public.part VALUES (111302, 'navajo pink sandy cornsilk firebrick', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL BRUSHED COPPER', 23, 'MED PKG   ', 1313.30, 'ly silen');
INSERT INTO public.part VALUES (20379, 'gainsboro sandy ghost papaya sienna', 'Manufacturer#2           ', 'Brand#23  ', 'MEDIUM PLATED TIN', 22, 'LG DRUM   ', 1299.37, 'y final excuses. re');
INSERT INTO public.part VALUES (44090, 'ivory salmon mint spring purple', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD BURNISHED COPPER', 15, 'JUMBO DRUM', 1034.09, ' foxes. slyly even dep');
INSERT INTO public.part VALUES (192040, 'blush moccasin pink misty tan', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL ANODIZED BRASS', 45, 'WRAP PACK ', 1132.04, 'ic accounts');
INSERT INTO public.part VALUES (86100, 'magenta deep ivory cornsilk lawn', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY POLISHED NICKEL', 34, 'SM PACK   ', 1086.10, 'ly ag');
INSERT INTO public.part VALUES (176768, 'violet hot magenta grey mint', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM PLATED BRASS', 17, 'JUMBO BOX ', 1844.76, 'ual pl');
INSERT INTO public.part VALUES (27493, 'peru tomato magenta medium almond', 'Manufacturer#1           ', 'Brand#12  ', 'MEDIUM BURNISHED TIN', 26, 'MED BOX   ', 1420.49, 'le about the blithe,');
INSERT INTO public.part VALUES (126695, 'cornflower dark lime forest cream', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL POLISHED COPPER', 27, 'LG BOX    ', 1721.69, 'ckages haggl');
INSERT INTO public.part VALUES (162313, 'forest azure thistle pink gainsboro', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM PLATED TIN', 43, 'JUMBO PKG ', 1375.31, 'al dolphi');
INSERT INTO public.part VALUES (8953, 'olive yellow rosy bisque lavender', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO BRUSHED STEEL', 18, 'MED CASE  ', 1861.95, 'sts cajo');
