INSERT INTO public.part VALUES (142540, 'bisque honeydew mint lawn tomato', 'Manufacturer#4           ', 'Brand#41  ', 'STANDARD BURNISHED TIN', 12, 'WRAP PKG  ', 1582.54, 'al dolphin');
INSERT INTO public.part VALUES (79127, 'rose blue ivory orchid brown', 'Manufacturer#1           ', 'Brand#11  ', 'ECONOMY ANODIZED COPPER', 28, 'JUMBO CAN ', 1106.12, 'gular,');
INSERT INTO public.part VALUES (34880, 'dark peach chartreuse thistle goldenrod', 'Manufacturer#1           ', 'Brand#15  ', 'MEDIUM BURNISHED COPPER', 42, 'JUMBO CAN ', 1814.88, 'deposits ');
INSERT INTO public.part VALUES (101631, 'lavender chiffon seashell dodger steel', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO BRUSHED TIN', 36, 'WRAP PKG  ', 1632.63, 'ular excuses. slyl');
INSERT INTO public.part VALUES (172740, 'antique ivory magenta cornsilk almond', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD BRUSHED TIN', 48, 'WRAP JAR  ', 1812.74, 'pending packages. ');
INSERT INTO public.part VALUES (196833, 'lemon green chocolate blue azure', 'Manufacturer#3           ', 'Brand#31  ', 'MEDIUM BURNISHED BRASS', 1, 'LG PACK   ', 1929.83, 'eodolites');
INSERT INTO public.part VALUES (6488, 'puff royal spring firebrick honeydew', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY BURNISHED BRASS', 4, 'LG BOX    ', 1394.48, 'atelet');
INSERT INTO public.part VALUES (114235, 'orchid violet plum frosted tomato', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE ANODIZED TIN', 41, 'WRAP BAG  ', 1249.23, 'osits. slowl');
INSERT INTO public.part VALUES (99259, 'dark brown cream sienna papaya', 'Manufacturer#2           ', 'Brand#22  ', 'STANDARD ANODIZED COPPER', 21, 'JUMBO CAN ', 1258.25, 'nder the furiousl');
INSERT INTO public.part VALUES (133591, 'saddle almond papaya gainsboro chartreuse', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO BRUSHED TIN', 18, 'LG CAN    ', 1624.59, 'lar deposi');
INSERT INTO public.part VALUES (69893, 'sienna spring pale lime blush', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM PLATED STEEL', 4, 'WRAP JAR  ', 1862.89, 'its are according ');
INSERT INTO public.part VALUES (64428, 'rosy thistle goldenrod seashell spring', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE ANODIZED COPPER', 20, 'LG PKG    ', 1392.42, 'side of ');
INSERT INTO public.part VALUES (134750, 'turquoise burnished cornsilk white blanched', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BURNISHED TIN', 27, 'MED PACK  ', 1784.75, 'atelets ma');
INSERT INTO public.part VALUES (23425, 'misty purple floral coral seashell', 'Manufacturer#2           ', 'Brand#25  ', 'SMALL BURNISHED STEEL', 14, 'LG CAN    ', 1348.42, 'ng foxes doubt furiou');
INSERT INTO public.part VALUES (34927, 'seashell indian misty black royal', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD BRUSHED BRASS', 9, 'SM JAR    ', 1861.92, ' ironic deposits use ');
INSERT INTO public.part VALUES (153247, 'chiffon thistle rose coral plum', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD BRUSHED STEEL', 40, 'LG CASE   ', 1300.24, 'es doubt. b');
INSERT INTO public.part VALUES (176452, 'honeydew midnight brown frosted saddle', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO BRUSHED NICKEL', 49, 'WRAP BAG  ', 1528.45, 'the carefully pendin');
INSERT INTO public.part VALUES (142800, 'cornsilk bisque azure rosy plum', 'Manufacturer#4           ', 'Brand#45  ', 'SMALL BURNISHED COPPER', 39, 'WRAP PKG  ', 1842.80, 'thely express theo');
INSERT INTO public.part VALUES (68419, 'forest misty chiffon sandy peru', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD BURNISHED TIN', 19, 'LG PKG    ', 1387.41, 'ly unusual asymp');
INSERT INTO public.part VALUES (70810, 'chocolate turquoise papaya sienna lace', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO BRUSHED NICKEL', 24, 'MED CAN   ', 1780.81, 'ndencies. silent d');
INSERT INTO public.part VALUES (191487, 'khaki lace misty papaya dodger', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO BRUSHED COPPER', 30, 'JUMBO DRUM', 1578.48, 's. quickly final');
INSERT INTO public.part VALUES (104308, 'dim wheat dark cornsilk yellow', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL POLISHED BRASS', 22, 'JUMBO CASE', 1312.30, ', busy instructions');
INSERT INTO public.part VALUES (87047, 'aquamarine azure burlywood green black', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO ANODIZED TIN', 28, 'LG JAR    ', 1034.04, 'onic ');
INSERT INTO public.part VALUES (135167, 'olive seashell chartreuse lime dim', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO PLATED COPPER', 8, 'JUMBO BAG ', 1202.16, 'symptot');
INSERT INTO public.part VALUES (146965, 'moccasin beige dark cornsilk puff', 'Manufacturer#3           ', 'Brand#35  ', 'PROMO ANODIZED TIN', 25, 'LG PACK   ', 2011.96, 'lyly busy ');
INSERT INTO public.part VALUES (57351, 'gainsboro navy magenta cornsilk chiffon', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL PLATED STEEL', 23, 'WRAP CASE ', 1308.35, 'f the furiousl');
INSERT INTO public.part VALUES (46469, 'navy peru drab dim deep', 'Manufacturer#3           ', 'Brand#31  ', 'STANDARD POLISHED NICKEL', 2, 'WRAP CASE ', 1415.46, 'eas ha');
INSERT INTO public.part VALUES (195223, 'cornsilk ivory beige sandy bisque', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD ANODIZED STEEL', 48, 'WRAP BOX  ', 1318.22, 'ts. regular packages');
INSERT INTO public.part VALUES (28873, 'floral deep plum blue red', 'Manufacturer#2           ', 'Brand#25  ', 'SMALL BRUSHED BRASS', 40, 'LG JAR    ', 1801.87, ' the ironic excus');
INSERT INTO public.part VALUES (774, 'wheat chiffon cyan misty moccasin', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD ANODIZED NICKEL', 26, 'WRAP CASE ', 1674.77, 'ly express dependen');
INSERT INTO public.part VALUES (156892, 'green firebrick sienna chartreuse hot', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM ANODIZED NICKEL', 16, 'SM PACK   ', 1948.89, 'ly ruthles');
INSERT INTO public.part VALUES (59816, 'green azure peach orchid maroon', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY ANODIZED BRASS', 21, 'LG DRUM   ', 1775.81, 'ss excu');
INSERT INTO public.part VALUES (181570, 'purple orange green burlywood pale', 'Manufacturer#3           ', 'Brand#31  ', 'STANDARD ANODIZED TIN', 42, 'LG BOX    ', 1651.57, ' haggle furiou');
INSERT INTO public.part VALUES (13022, 'ghost orchid spring mint metallic', 'Manufacturer#5           ', 'Brand#55  ', 'PROMO BRUSHED NICKEL', 46, 'SM BAG    ', 935.02, ' even inst');
INSERT INTO public.part VALUES (60440, 'rosy saddle lawn brown blush', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM ANODIZED STEEL', 47, 'SM BOX    ', 1400.44, ' to the slyly unusu');
INSERT INTO public.part VALUES (115282, 'steel papaya indian burnished smoke', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO PLATED NICKEL', 42, 'WRAP PKG  ', 1297.28, 'r, even decoys doubt.');
INSERT INTO public.part VALUES (13994, 'khaki maroon lavender papaya chocolate', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO POLISHED TIN', 18, 'MED BOX   ', 1907.99, 'the special dolph');
INSERT INTO public.part VALUES (170387, 'tan coral beige cornsilk royal', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BRUSHED BRASS', 46, 'LG DRUM   ', 1457.38, 'se express theodolite');
INSERT INTO public.part VALUES (139677, 'deep cornsilk purple yellow drab', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO ANODIZED STEEL', 41, 'JUMBO BOX ', 1716.67, ' regular plat');
INSERT INTO public.part VALUES (121144, 'indian rose brown lace pale', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO BRUSHED STEEL', 42, 'MED CAN   ', 1165.14, 'oxes. sl');
INSERT INTO public.part VALUES (96384, 'maroon blue brown pink burlywood', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO BRUSHED STEEL', 6, 'JUMBO PKG ', 1380.38, 'r the');
INSERT INTO public.part VALUES (25473, 'sienna almond chocolate azure saddle', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO BRUSHED TIN', 39, 'WRAP BOX  ', 1398.47, ' ironic, express t');
INSERT INTO public.part VALUES (79699, 'powder burnished pale tomato midnight', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD ANODIZED NICKEL', 7, 'WRAP CAN  ', 1678.69, 'es ca');
INSERT INTO public.part VALUES (143677, 'wheat goldenrod plum maroon violet', 'Manufacturer#5           ', 'Brand#53  ', 'MEDIUM PLATED STEEL', 43, 'JUMBO DRUM', 1720.67, 'lar, regular reques');
INSERT INTO public.part VALUES (78818, 'cornflower burlywood orange medium powder', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO PLATED BRASS', 3, 'MED PACK  ', 1796.81, 'nt, special ');
INSERT INTO public.part VALUES (16726, 'lavender tan sandy seashell chiffon', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE POLISHED STEEL', 14, 'JUMBO PACK', 1642.72, ' alongside of');
INSERT INTO public.part VALUES (44013, 'maroon salmon linen green saddle', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO ANODIZED TIN', 31, 'SM PACK   ', 957.01, 's. ironic, bold ');
INSERT INTO public.part VALUES (137418, 'blush rosy sky sandy hot', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO BURNISHED COPPER', 30, 'WRAP JAR  ', 1455.41, 's-- bold, pendin');
INSERT INTO public.part VALUES (100286, 'spring cyan wheat slate lemon', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD ANODIZED BRASS', 42, 'SM CAN    ', 1286.28, 'al patterns cajol');
INSERT INTO public.part VALUES (147640, 'almond misty deep violet pink', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE ANODIZED STEEL', 41, 'MED BAG   ', 1687.64, 'y slyly b');
INSERT INTO public.part VALUES (6023, 'blush chartreuse gainsboro beige maroon', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY BURNISHED BRASS', 43, 'SM PKG    ', 929.02, 'ave packa');
INSERT INTO public.part VALUES (12596, 'turquoise pale plum cream blue', 'Manufacturer#1           ', 'Brand#12  ', 'PROMO PLATED NICKEL', 43, 'LG BOX    ', 1508.59, 'ts. busily regular cou');
INSERT INTO public.part VALUES (194874, 'antique chocolate azure yellow lime', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO POLISHED NICKEL', 40, 'MED JAR   ', 1968.87, 'nst the unus');
INSERT INTO public.part VALUES (4622, 'ivory lavender indian almond thistle', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE POLISHED TIN', 19, 'LG DRUM   ', 1526.62, 's-- ruthless account');
INSERT INTO public.part VALUES (171941, 'dim black pink bisque moccasin', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BURNISHED STEEL', 9, 'JUMBO PKG ', 2012.94, 'account');
INSERT INTO public.part VALUES (71488, 'chartreuse dark spring peru ivory', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL BURNISHED COPPER', 1, 'WRAP JAR  ', 1459.48, 'ts among the furiously');
INSERT INTO public.part VALUES (70002, 'cornflower gainsboro papaya green snow', 'Manufacturer#4           ', 'Brand#43  ', 'SMALL BRUSHED STEEL', 45, 'SM DRUM   ', 972.00, 'ular dependenc');
INSERT INTO public.part VALUES (56723, 'olive dodger forest lemon puff', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD PLATED TIN', 33, 'JUMBO BAG ', 1679.72, 'ic sheaves run sly');
INSERT INTO public.part VALUES (136122, 'royal cyan slate lace burnished', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY BURNISHED COPPER', 19, 'JUMBO DRUM', 1158.12, 'y bold deposits? final');
INSERT INTO public.part VALUES (183005, 'metallic peru cornsilk light sky', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE PLATED STEEL', 32, 'SM BAG    ', 1088.00, 'longside of th');
INSERT INTO public.part VALUES (90410, 'burlywood linen sandy medium yellow', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD BURNISHED NICKEL', 21, 'WRAP DRUM ', 1400.41, 'jole furiously. regula');
INSERT INTO public.part VALUES (12975, 'rosy saddle mint blush lace', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO POLISHED BRASS', 16, 'LG CASE   ', 1887.97, 'kly bo');
INSERT INTO public.part VALUES (165710, 'medium tan chartreuse salmon lavender', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY BURNISHED TIN', 28, 'MED PACK  ', 1775.71, 'packages. e');
INSERT INTO public.part VALUES (194993, 'thistle slate midnight navajo khaki', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO BRUSHED COPPER', 49, 'MED CAN   ', 2087.99, 's. depende');
INSERT INTO public.part VALUES (95543, 'smoke orchid dim light ghost', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM BURNISHED BRASS', 34, 'JUMBO DRUM', 1538.54, 'ckages nag fluffil');
INSERT INTO public.part VALUES (194293, 'blush lime purple magenta white', 'Manufacturer#2           ', 'Brand#25  ', 'SMALL PLATED TIN', 18, 'WRAP CASE ', 1387.29, 'ronic packages.');
INSERT INTO public.part VALUES (80829, 'olive hot lace navy green', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO ANODIZED BRASS', 17, 'JUMBO PACK', 1809.82, 'ajole slyly blithely');
INSERT INTO public.part VALUES (182605, 'forest tomato thistle cream papaya', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM BRUSHED STEEL', 31, 'JUMBO JAR ', 1687.60, 'ously acc');
INSERT INTO public.part VALUES (131496, 'tan linen puff cornflower snow', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO BRUSHED NICKEL', 24, 'JUMBO BOX ', 1527.49, 'haggle quickly');
INSERT INTO public.part VALUES (76181, 'maroon green coral burnished khaki', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE BURNISHED STEEL', 48, 'MED PACK  ', 1157.18, 'ies. regular');
INSERT INTO public.part VALUES (169264, 'black chocolate rosy red forest', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY BURNISHED COPPER', 33, 'JUMBO DRUM', 1333.26, 'iously. blithely ');
INSERT INTO public.part VALUES (5929, 'smoke tomato forest peru violet', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO POLISHED STEEL', 7, 'MED BAG   ', 1834.92, 'ut the regular ide');
INSERT INTO public.part VALUES (123588, 'aquamarine almond purple lawn plum', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL ANODIZED BRASS', 18, 'WRAP PKG  ', 1611.58, 'requests hagg');
INSERT INTO public.part VALUES (162389, 'sandy firebrick green rose moccasin', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE BURNISHED COPPER', 38, 'MED DRUM  ', 1451.38, 'posits. blithely i');
INSERT INTO public.part VALUES (161008, 'khaki drab frosted goldenrod mint', 'Manufacturer#5           ', 'Brand#54  ', 'LARGE POLISHED COPPER', 17, 'LG JAR    ', 1069.00, 'quests nag carefull');
INSERT INTO public.part VALUES (140711, 'magenta blush coral goldenrod frosted', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM ANODIZED COPPER', 35, 'WRAP PKG  ', 1751.71, 'ests ru');
INSERT INTO public.part VALUES (102876, 'lawn papaya floral lime firebrick', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM ANODIZED BRASS', 45, 'JUMBO JAR ', 1878.87, 'tructio');
INSERT INTO public.part VALUES (176546, 'honeydew almond chiffon ivory lime', 'Manufacturer#1           ', 'Brand#11  ', 'STANDARD PLATED STEEL', 23, 'SM DRUM   ', 1622.54, '. furiously i');
INSERT INTO public.part VALUES (136670, 'peru moccasin bisque thistle purple', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE ANODIZED COPPER', 21, 'MED BOX   ', 1706.67, 'ly regu');
INSERT INTO public.part VALUES (170409, 'beige magenta deep midnight indian', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM BRUSHED NICKEL', 32, 'JUMBO BOX ', 1479.40, 'nto beans p');
INSERT INTO public.part VALUES (26899, 'floral blanched thistle midnight wheat', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY ANODIZED COPPER', 24, 'JUMBO DRUM', 1825.89, 's. even, r');
INSERT INTO public.part VALUES (67082, 'medium turquoise almond navajo misty', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL PLATED BRASS', 8, 'LG PKG    ', 1049.08, 'r accounts pri');
INSERT INTO public.part VALUES (4400, 'chartreuse lemon royal peach red', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM POLISHED BRASS', 44, 'WRAP CASE ', 1304.40, 'ut the furiousl');
INSERT INTO public.part VALUES (28576, 'frosted papaya light blanched cyan', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO PLATED NICKEL', 17, 'SM DRUM   ', 1504.57, 'ect even');
INSERT INTO public.part VALUES (35960, 'cornflower yellow antique aquamarine tomato', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO ANODIZED TIN', 44, 'LG BAG    ', 1895.96, 'sual accounts wake car');
INSERT INTO public.part VALUES (123257, 'mint aquamarine blanched green dim', 'Manufacturer#3           ', 'Brand#35  ', 'PROMO PLATED NICKEL', 44, 'WRAP PACK ', 1280.25, 'pinto beans. ');
