INSERT INTO public.part VALUES (89165, 'turquoise antique sandy wheat yellow', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BRUSHED NICKEL', 27, 'JUMBO PKG ', 1154.16, 'ly. sl');
INSERT INTO public.part VALUES (187185, 'violet cornflower saddle navajo floral', 'Manufacturer#2           ', 'Brand#22  ', 'STANDARD ANODIZED NICKEL', 34, 'MED DRUM  ', 1272.18, 'kages cajole quic');
INSERT INTO public.part VALUES (163666, 'antique yellow smoke forest lawn', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO BRUSHED STEEL', 50, 'WRAP PACK ', 1729.66, 'ke. carefully ironic ');
INSERT INTO public.part VALUES (110994, 'ghost saddle magenta cornsilk misty', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BRUSHED COPPER', 33, 'MED DRUM  ', 2004.99, 'e of the regular de');
INSERT INTO public.part VALUES (78421, 'burlywood snow blue deep wheat', 'Manufacturer#2           ', 'Brand#24  ', 'MEDIUM PLATED TIN', 27, 'MED CAN   ', 1399.42, 'silent, u');
INSERT INTO public.part VALUES (121430, 'coral firebrick salmon turquoise lace', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO POLISHED STEEL', 18, 'WRAP BAG  ', 1451.43, 'ly bold c');
INSERT INTO public.part VALUES (66182, 'peru puff dim midnight hot', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO POLISHED BRASS', 37, 'JUMBO BOX ', 1148.18, ' the furiously ');
INSERT INTO public.part VALUES (188465, 'aquamarine drab lawn pale metallic', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD BRUSHED STEEL', 43, 'JUMBO PACK', 1553.46, 'al pinto beans. ironic');
INSERT INTO public.part VALUES (153975, 'chocolate black cornsilk magenta royal', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BURNISHED COPPER', 35, 'WRAP DRUM ', 2028.97, 'ons need');
INSERT INTO public.part VALUES (6166, 'indian orange orchid turquoise blush', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM PLATED NICKEL', 25, 'WRAP PACK ', 1072.16, 'ven pinto b');
INSERT INTO public.part VALUES (87286, 'burlywood medium ivory lavender green', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL PLATED TIN', 10, 'MED DRUM  ', 1273.28, 'ns wak');
INSERT INTO public.part VALUES (89485, 'seashell brown coral lawn tan', 'Manufacturer#1           ', 'Brand#11  ', 'STANDARD POLISHED COPPER', 39, 'WRAP DRUM ', 1474.48, 'efull');
INSERT INTO public.part VALUES (144298, 'orchid thistle aquamarine peach spring', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY BURNISHED NICKEL', 41, 'JUMBO BOX ', 1342.29, 's about the ');
INSERT INTO public.part VALUES (193245, 'smoke black saddle cyan lace', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE POLISHED COPPER', 4, 'SM JAR    ', 1338.24, 's dependencies boo');
INSERT INTO public.part VALUES (38454, 'pale azure spring gainsboro peru', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD ANODIZED STEEL', 16, 'SM CAN    ', 1392.45, 'gainst the even th');
INSERT INTO public.part VALUES (38244, 'honeydew dim hot lemon burlywood', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE PLATED STEEL', 1, 'MED DRUM  ', 1182.24, 'unts are slyly unus');
INSERT INTO public.part VALUES (154408, 'lavender olive metallic steel honeydew', 'Manufacturer#2           ', 'Brand#22  ', 'SMALL BURNISHED STEEL', 34, 'LG BAG    ', 1462.40, 'longside of th');
INSERT INTO public.part VALUES (181644, 'navajo puff chocolate steel thistle', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE BURNISHED BRASS', 14, 'WRAP PKG  ', 1725.64, 'es use furi');
INSERT INTO public.part VALUES (20563, 'chiffon black burlywood cream chocolate', 'Manufacturer#4           ', 'Brand#44  ', 'PROMO PLATED BRASS', 11, 'MED BAG   ', 1483.56, 'ar instruct');
INSERT INTO public.part VALUES (67915, 'lawn sky lime gainsboro antique', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE BURNISHED BRASS', 50, 'SM DRUM   ', 1882.91, 's requ');
INSERT INTO public.part VALUES (128092, 'honeydew ivory grey blue red', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD BURNISHED NICKEL', 44, 'MED CASE  ', 1120.09, 'ake fluffil');
INSERT INTO public.part VALUES (106260, 'red royal olive frosted ivory', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM POLISHED NICKEL', 6, 'MED PKG   ', 1266.26, 'l accounts. exp');
INSERT INTO public.part VALUES (136917, 'metallic peach misty navy frosted', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY POLISHED BRASS', 11, 'SM CAN    ', 1953.91, 'ckly even warho');
INSERT INTO public.part VALUES (75254, 'red purple ghost antique midnight', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD BRUSHED STEEL', 37, 'JUMBO CAN ', 1229.25, 'to beans ag');
INSERT INTO public.part VALUES (155762, 'sandy tan linen smoke magenta', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO ANODIZED NICKEL', 13, 'WRAP BAG  ', 1817.76, 'dle requests sleep sp');
INSERT INTO public.part VALUES (2471, 'green peru hot dodger pink', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE PLATED TIN', 36, 'JUMBO BOX ', 1373.47, 'oxes are idly unt');
INSERT INTO public.part VALUES (25659, 'grey metallic forest pink blanched', 'Manufacturer#1           ', 'Brand#12  ', 'PROMO BRUSHED BRASS', 4, 'SM BAG    ', 1584.65, 'fily. spe');
INSERT INTO public.part VALUES (21127, 'medium misty spring purple drab', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO POLISHED TIN', 49, 'SM CAN    ', 1048.12, 'theodoli');
