INSERT INTO public.part VALUES (2209, 'chocolate misty beige coral forest', 'Manufacturer#2           ', 'Brand#21  ', 'MEDIUM PLATED COPPER', 11, 'SM BOX    ', 1111.20, ' the ironi');
INSERT INTO public.part VALUES (107420, 'lime peach turquoise blanched brown', 'Manufacturer#2           ', 'Brand#23  ', 'PROMO PLATED BRASS', 12, 'SM PACK   ', 1427.42, 'ly express requests');
INSERT INTO public.part VALUES (54640, 'snow firebrick smoke forest moccasin', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY POLISHED STEEL', 25, 'MED PACK  ', 1594.64, 'eep fluffily ');
INSERT INTO public.part VALUES (138179, 'green antique dark steel khaki', 'Manufacturer#2           ', 'Brand#21  ', 'ECONOMY BRUSHED STEEL', 18, 'MED PKG   ', 1217.17, 'e. evenly fi');
INSERT INTO public.part VALUES (25266, 'magenta rosy navajo plum peru', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY POLISHED TIN', 35, 'WRAP DRUM ', 1191.26, 'nstructions haggle ');
INSERT INTO public.part VALUES (161262, 'magenta lawn gainsboro khaki lavender', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL ANODIZED TIN', 40, 'WRAP CAN  ', 1323.26, 'usual theodol');
INSERT INTO public.part VALUES (18334, 'tan navajo azure medium drab', 'Manufacturer#1           ', 'Brand#11  ', 'LARGE BURNISHED BRASS', 11, 'JUMBO DRUM', 1252.33, 'blithely final re');
INSERT INTO public.part VALUES (30616, 'metallic coral cornsilk aquamarine maroon', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM PLATED BRASS', 12, 'SM PKG    ', 1546.61, 'ual acco');
INSERT INTO public.part VALUES (85457, 'wheat almond chiffon blanched drab', 'Manufacturer#4           ', 'Brand#41  ', 'STANDARD ANODIZED TIN', 48, 'WRAP PACK ', 1442.45, 'ar, bold ');
INSERT INTO public.part VALUES (190380, 'chocolate sienna tomato antique linen', 'Manufacturer#4           ', 'Brand#44  ', 'ECONOMY BURNISHED BRASS', 8, 'JUMBO CAN ', 1470.38, 'haggle');
INSERT INTO public.part VALUES (73887, 'metallic black dark saddle thistle', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE ANODIZED NICKEL', 47, 'LG DRUM   ', 1860.88, 'lyly. deposits aga');
INSERT INTO public.part VALUES (28866, 'almond blush black puff chiffon', 'Manufacturer#5           ', 'Brand#54  ', 'ECONOMY ANODIZED NICKEL', 35, 'MED CASE  ', 1794.86, 'are slyly bold d');
INSERT INTO public.part VALUES (158779, 'puff navajo smoke frosted honeydew', 'Manufacturer#4           ', 'Brand#41  ', 'ECONOMY BURNISHED TIN', 29, 'LG CASE   ', 1837.77, 'egular platelets');
INSERT INTO public.part VALUES (185856, 'azure white cream lace lime', 'Manufacturer#1           ', 'Brand#12  ', 'LARGE BRUSHED COPPER', 43, 'LG BAG    ', 1941.85, '! unusual ');
INSERT INTO public.part VALUES (159812, 'pink medium goldenrod aquamarine deep', 'Manufacturer#5           ', 'Brand#55  ', 'MEDIUM BRUSHED STEEL', 36, 'JUMBO JAR ', 1871.81, 'old packag');
INSERT INTO public.part VALUES (180547, 'orchid moccasin brown papaya lavender', 'Manufacturer#2           ', 'Brand#22  ', 'SMALL POLISHED TIN', 17, 'SM BAG    ', 1627.54, 'e. quickl');
INSERT INTO public.part VALUES (128115, 'slate lime peru brown indian', 'Manufacturer#2           ', 'Brand#24  ', 'MEDIUM POLISHED BRASS', 23, 'MED JAR   ', 1143.11, 'fully bold');
INSERT INTO public.part VALUES (36161, 'floral frosted burlywood blush goldenrod', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE ANODIZED STEEL', 1, 'SM PKG    ', 1097.16, 'ffily quickly un');
INSERT INTO public.part VALUES (71550, 'coral red midnight olive light', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM ANODIZED TIN', 27, 'SM BAG    ', 1521.55, 'ular ');
INSERT INTO public.part VALUES (6469, 'turquoise navajo indian olive forest', 'Manufacturer#1           ', 'Brand#14  ', 'MEDIUM ANODIZED STEEL', 8, 'WRAP JAR  ', 1375.46, 'ged req');
INSERT INTO public.part VALUES (161111, 'moccasin ivory white tomato metallic', 'Manufacturer#2           ', 'Brand#22  ', 'SMALL BRUSHED TIN', 24, 'JUMBO DRUM', 1172.11, 'ar theodolite');
INSERT INTO public.part VALUES (78432, 'lawn spring rosy navy magenta', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO POLISHED TIN', 25, 'LG PACK   ', 1410.43, 'ias are. q');
INSERT INTO public.part VALUES (46935, 'orchid brown tan misty lavender', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BURNISHED TIN', 1, 'LG PACK   ', 1881.93, 'hely even accounts: fl');
INSERT INTO public.part VALUES (133850, 'spring sandy green papaya yellow', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO ANODIZED NICKEL', 18, 'LG BAG    ', 1883.85, ' permanently r');
INSERT INTO public.part VALUES (91513, 'navajo puff spring dodger dark', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO BRUSHED COPPER', 19, 'SM CAN    ', 1504.51, 'ven accounts ');
INSERT INTO public.part VALUES (61732, 'wheat tan purple deep chiffon', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM BURNISHED COPPER', 39, 'SM CASE   ', 1693.73, 'against the blithely');
INSERT INTO public.part VALUES (47296, 'smoke midnight purple orange salmon', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO ANODIZED NICKEL', 5, 'MED BAG   ', 1243.29, 'ully ironic foxes cajo');
INSERT INTO public.part VALUES (66259, 'magenta black lawn blush sandy', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM BRUSHED COPPER', 14, 'LG BAG    ', 1225.25, 'ccounts ');
INSERT INTO public.part VALUES (182161, 'red wheat steel blue goldenrod', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BRUSHED BRASS', 26, 'LG CASE   ', 1243.16, 'ect ca');
INSERT INTO public.part VALUES (69799, 'spring mint salmon blue olive', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED STEEL', 49, 'LG CAN    ', 1768.79, 'ly. regular');
INSERT INTO public.part VALUES (130869, 'gainsboro bisque honeydew tomato medium', 'Manufacturer#1           ', 'Brand#12  ', 'MEDIUM POLISHED STEEL', 28, 'LG CASE   ', 1899.86, 'ss pinto b');
INSERT INTO public.part VALUES (143101, 'antique blue aquamarine orange slate', 'Manufacturer#3           ', 'Brand#33  ', 'PROMO PLATED COPPER', 16, 'MED DRUM  ', 1144.10, 'pearls? furiously');
INSERT INTO public.part VALUES (50331, 'tomato burlywood navy peach green', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE BRUSHED NICKEL', 22, 'MED DRUM  ', 1281.33, 'gle furiously al');
INSERT INTO public.part VALUES (6712, 'moccasin burlywood peru dodger smoke', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY ANODIZED COPPER', 41, 'WRAP JAR  ', 1618.71, 'ests hag');
INSERT INTO public.part VALUES (17754, 'saddle turquoise orchid pale lime', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY BURNISHED STEEL', 17, 'MED CAN   ', 1671.75, 'reque');
INSERT INTO public.part VALUES (110560, 'orange deep moccasin drab almond', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY ANODIZED TIN', 30, 'MED CAN   ', 1570.56, 'after ');
INSERT INTO public.part VALUES (60484, 'burnished tan black white sandy', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM ANODIZED TIN', 35, 'LG JAR    ', 1444.48, 'ding ide');
INSERT INTO public.part VALUES (16021, 'orchid sandy blanched magenta navy', 'Manufacturer#5           ', 'Brand#55  ', 'MEDIUM BURNISHED NICKEL', 3, 'WRAP JAR  ', 937.02, 'refully request');
INSERT INTO public.part VALUES (182246, 'almond drab hot azure dodger', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE POLISHED BRASS', 49, 'LG BOX    ', 1328.24, 'deposi');
INSERT INTO public.part VALUES (100936, 'khaki powder sienna seashell salmon', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD POLISHED NICKEL', 50, 'MED JAR   ', 1936.93, 'iously pending packag');
INSERT INTO public.part VALUES (94902, 'steel pink sky honeydew azure', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO ANODIZED COPPER', 37, 'SM PKG    ', 1896.90, 'slyly bold a');
INSERT INTO public.part VALUES (173151, 'navy dark olive violet linen', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL ANODIZED TIN', 19, 'JUMBO BOX ', 1224.15, 'ts wake fluffily un');
INSERT INTO public.part VALUES (125549, 'royal violet beige lace tomato', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY PLATED STEEL', 17, 'SM JAR    ', 1574.54, 'te even dep');
INSERT INTO public.part VALUES (111059, 'ghost lace goldenrod rosy grey', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO PLATED COPPER', 25, 'MED PACK  ', 1070.05, ' ironic, regul');
INSERT INTO public.part VALUES (146085, 'black light violet grey lavender', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY PLATED BRASS', 46, 'MED PACK  ', 1131.08, 'tegrate quickly bo');
INSERT INTO public.part VALUES (191126, 'coral chiffon orange white royal', 'Manufacturer#2           ', 'Brand#23  ', 'MEDIUM BRUSHED COPPER', 35, 'SM CASE   ', 1217.12, 'fily s');
INSERT INTO public.part VALUES (104987, 'blue lemon thistle dim mint', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL PLATED STEEL', 44, 'LG PACK   ', 1991.98, 'cajole fu');
INSERT INTO public.part VALUES (137128, 'ghost yellow chocolate honeydew ivory', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD BRUSHED STEEL', 48, 'MED BAG   ', 1165.12, 'usual pinto bea');
INSERT INTO public.part VALUES (130500, 'slate mint black azure chocolate', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO BURNISHED NICKEL', 45, 'LG BOX    ', 1530.50, 'nic p');
INSERT INTO public.part VALUES (72608, 'spring dodger azure white misty', 'Manufacturer#1           ', 'Brand#15  ', 'STANDARD BURNISHED COPPER', 50, 'LG BOX    ', 1580.60, 'bout the slyly');
INSERT INTO public.part VALUES (168362, 'lemon misty ivory olive steel', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO PLATED TIN', 29, 'SM CASE   ', 1430.36, ' regu');
INSERT INTO public.part VALUES (74445, 'magenta smoke cyan tomato lavender', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO BURNISHED COPPER', 13, 'SM DRUM   ', 1419.44, 'y pending');
INSERT INTO public.part VALUES (42005, 'plum forest metallic bisque cream', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM POLISHED NICKEL', 17, 'MED CASE  ', 947.00, 'the final pinto beans-');
INSERT INTO public.part VALUES (155148, 'almond navy blush sky dark', 'Manufacturer#5           ', 'Brand#55  ', 'PROMO POLISHED NICKEL', 23, 'SM DRUM   ', 1203.14, 'st the fluffily');
INSERT INTO public.part VALUES (32877, 'maroon ghost cyan honeydew olive', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE ANODIZED NICKEL', 46, 'SM BOX    ', 1809.87, 'ronic p');
INSERT INTO public.part VALUES (160758, 'salmon brown beige royal maroon', 'Manufacturer#1           ', 'Brand#13  ', 'SMALL BRUSHED TIN', 17, 'JUMBO DRUM', 1818.75, 'ven asym');
INSERT INTO public.part VALUES (143391, 'azure tomato navajo blush sky', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM PLATED COPPER', 27, 'SM JAR    ', 1434.39, 'ronic, iron');
INSERT INTO public.part VALUES (57672, 'spring midnight pink chartreuse bisque', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BURNISHED STEEL', 3, 'SM PKG    ', 1629.67, 'ackages. carefull');
INSERT INTO public.part VALUES (168311, 'cream honeydew khaki peru grey', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO BURNISHED NICKEL', 6, 'WRAP BOX  ', 1379.31, 'ithely even grouch');
INSERT INTO public.part VALUES (36565, 'peach snow dodger lemon tomato', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL POLISHED COPPER', 11, 'WRAP DRUM ', 1501.56, 'r ideas cajo');
INSERT INTO public.part VALUES (85365, 'magenta dark lime metallic sky', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD PLATED NICKEL', 45, 'LG CASE   ', 1350.36, 'theodo');
INSERT INTO public.part VALUES (3275, 'smoke burlywood wheat lavender slate', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE PLATED BRASS', 19, 'LG CAN    ', 1178.27, 'ly. dogged depe');
INSERT INTO public.part VALUES (99486, 'saddle papaya snow rosy blue', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE POLISHED BRASS', 2, 'WRAP DRUM ', 1485.48, ' ironic sentiments ');
INSERT INTO public.part VALUES (177667, 'black misty ivory chiffon gainsboro', 'Manufacturer#4           ', 'Brand#41  ', 'STANDARD ANODIZED TIN', 22, 'WRAP CASE ', 1744.66, 'dencies are careful');
INSERT INTO public.part VALUES (95111, 'orange sienna tan metallic dim', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL POLISHED NICKEL', 18, 'LG CAN    ', 1106.11, 'es. slyly ');
INSERT INTO public.part VALUES (28867, 'cornsilk blue seashell steel firebrick', 'Manufacturer#4           ', 'Brand#44  ', 'LARGE BRUSHED COPPER', 13, 'JUMBO JAR ', 1795.86, 'sheav');
INSERT INTO public.part VALUES (157068, 'almond ivory navajo burnished saddle', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE POLISHED TIN', 17, 'MED BOX   ', 1125.06, 'nal ideas. slyly ironi');
INSERT INTO public.part VALUES (193332, 'saddle turquoise drab bisque cornsilk', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE POLISHED BRASS', 42, 'WRAP CASE ', 1425.33, 's the blithely reg');
INSERT INTO public.part VALUES (198610, 'goldenrod magenta khaki peru gainsboro', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE POLISHED TIN', 39, 'SM PACK   ', 1708.61, 'e care');
INSERT INTO public.part VALUES (170542, 'chocolate rose chiffon navajo orange', 'Manufacturer#3           ', 'Brand#35  ', 'LARGE PLATED STEEL', 35, 'SM PACK   ', 1612.54, 'warthogs');
INSERT INTO public.part VALUES (128537, 'azure bisque frosted coral aquamarine', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY POLISHED TIN', 36, 'WRAP CAN  ', 1565.53, 'fily pendin');
INSERT INTO public.part VALUES (141211, 'blue linen green magenta smoke', 'Manufacturer#5           ', 'Brand#52  ', 'MEDIUM BRUSHED TIN', 10, 'SM PKG    ', 1252.21, ' across the final, fl');
INSERT INTO public.part VALUES (170166, 'grey navy lawn snow metallic', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY ANODIZED STEEL', 50, 'SM PACK   ', 1236.16, 's final pa');
INSERT INTO public.part VALUES (104085, 'rose light blanched magenta puff', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO POLISHED STEEL', 47, 'WRAP DRUM ', 1089.08, 'egular a');
INSERT INTO public.part VALUES (79984, 'steel tomato lemon pale misty', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM POLISHED NICKEL', 22, 'MED PACK  ', 1963.98, 'refully final th');
INSERT INTO public.part VALUES (85984, 'coral chiffon saddle cornflower rosy', 'Manufacturer#3           ', 'Brand#31  ', 'SMALL ANODIZED TIN', 8, 'WRAP PKG  ', 1969.98, 've pac');
INSERT INTO public.part VALUES (139319, 'cream lawn seashell azure linen', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD BURNISHED STEEL', 11, 'JUMBO JAR ', 1358.31, 'ickly ');
INSERT INTO public.part VALUES (100765, 'dim brown rose cyan burnished', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD BURNISHED STEEL', 44, 'SM JAR    ', 1765.76, 't quickl');
INSERT INTO public.part VALUES (4809, 'grey midnight orange chocolate aquamarine', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM ANODIZED BRASS', 44, 'WRAP CAN  ', 1713.80, 'ccounts acc');
INSERT INTO public.part VALUES (107878, 'lemon plum coral midnight azure', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY ANODIZED COPPER', 47, 'SM DRUM   ', 1885.87, ' use caref');
INSERT INTO public.part VALUES (66699, 'blush light goldenrod pink orange', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY BURNISHED NICKEL', 38, 'JUMBO BOX ', 1665.69, 'blithely. slyly ev');
INSERT INTO public.part VALUES (149929, 'blanched firebrick gainsboro forest antique', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO BURNISHED COPPER', 30, 'WRAP DRUM ', 1978.92, 'rious');
INSERT INTO public.part VALUES (37698, 'turquoise magenta dodger smoke white', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY ANODIZED STEEL', 5, 'JUMBO DRUM', 1635.69, 'sits acr');
INSERT INTO public.part VALUES (173750, 'burnished violet khaki dim wheat', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY POLISHED TIN', 33, 'JUMBO JAR ', 1823.75, ' haggl');
INSERT INTO public.part VALUES (140826, 'grey lavender mint sienna red', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE POLISHED NICKEL', 9, 'JUMBO BOX ', 1866.82, 'ges haggle blit');
INSERT INTO public.part VALUES (189089, 'drab chartreuse turquoise almond dodger', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY BRUSHED STEEL', 43, 'SM PACK   ', 1178.08, 'kly final deposits ');
INSERT INTO public.part VALUES (191755, 'beige midnight azure thistle gainsboro', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD BRUSHED NICKEL', 4, 'LG CASE   ', 1846.75, 'en ideas. slyly expres');
INSERT INTO public.part VALUES (151960, 'red indian bisque snow orange', 'Manufacturer#5           ', 'Brand#52  ', 'MEDIUM BURNISHED TIN', 30, 'SM CAN    ', 2011.96, 'ect about th');
INSERT INTO public.part VALUES (68878, 'pale indian slate grey deep', 'Manufacturer#4           ', 'Brand#41  ', 'STANDARD PLATED COPPER', 7, 'JUMBO BOX ', 1846.87, ' among the final excus');
INSERT INTO public.part VALUES (15044, 'bisque sky goldenrod olive floral', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE POLISHED BRASS', 46, 'MED PKG   ', 959.04, 's. blithely bold re');
INSERT INTO public.part VALUES (90704, 'navajo ghost indian rosy tan', 'Manufacturer#5           ', 'Brand#53  ', 'MEDIUM BRUSHED STEEL', 48, 'WRAP BOX  ', 1694.70, ' instruc');
INSERT INTO public.part VALUES (30546, 'grey deep rose frosted saddle', 'Manufacturer#2           ', 'Brand#22  ', 'STANDARD POLISHED NICKEL', 11, 'SM BOX    ', 1476.54, ' unus');
INSERT INTO public.part VALUES (105983, 'orange peru violet medium blanched', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO PLATED TIN', 22, 'JUMBO CAN ', 1988.98, 'kly sly, final req');
INSERT INTO public.part VALUES (61387, 'plum chiffon smoke olive sky', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM PLATED BRASS', 27, 'JUMBO CAN ', 1348.38, 'ter the exc');
INSERT INTO public.part VALUES (135153, 'lemon forest red beige burnished', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO PLATED STEEL', 31, 'JUMBO DRUM', 1188.15, 'dogged, re');
INSERT INTO public.part VALUES (14854, 'spring green cream honeydew rose', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD PLATED COPPER', 17, 'MED JAR   ', 1768.85, 'uriously. f');
INSERT INTO public.part VALUES (174431, 'purple thistle powder slate grey', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL BURNISHED STEEL', 14, 'LG PACK   ', 1505.43, 'eas sleep against ');
INSERT INTO public.part VALUES (116622, 'chocolate salmon cyan plum papaya', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL ANODIZED COPPER', 34, 'WRAP PKG  ', 1638.62, ' requests x-ray above');
INSERT INTO public.part VALUES (105692, 'moccasin drab cornsilk orange green', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL PLATED NICKEL', 26, 'WRAP PKG  ', 1697.69, 'thely bold');
INSERT INTO public.part VALUES (81161, 'cyan seashell floral linen cornsilk', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD PLATED NICKEL', 37, 'MED JAR   ', 1142.16, 'uffily. p');
INSERT INTO public.part VALUES (110537, 'magenta spring seashell wheat linen', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY PLATED BRASS', 33, 'WRAP CAN  ', 1547.53, 'fily final reques');
INSERT INTO public.part VALUES (94770, 'sienna lime violet ivory turquoise', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE BRUSHED STEEL', 9, 'JUMBO PKG ', 1764.77, 'le across the careful');
INSERT INTO public.part VALUES (74808, 'dodger burnished aquamarine frosted deep', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE POLISHED COPPER', 24, 'SM CAN    ', 1782.80, 'carefully ');
INSERT INTO public.part VALUES (7636, 'hot forest navajo navy steel', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL BURNISHED COPPER', 44, 'SM BAG    ', 1543.63, 'aters haggle quic');
INSERT INTO public.part VALUES (105225, 'light cream plum brown orchid', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO POLISHED COPPER', 5, 'LG CAN    ', 1230.22, 'o the slyly sp');
INSERT INTO public.part VALUES (83724, 'chartreuse orange red floral grey', 'Manufacturer#1           ', 'Brand#13  ', 'SMALL BURNISHED BRASS', 1, 'SM CAN    ', 1707.72, 'eodolites nag bli');
INSERT INTO public.part VALUES (196359, 'chiffon dodger lace misty powder', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO BURNISHED BRASS', 30, 'WRAP JAR  ', 1455.35, 'even, ironic notornis');
INSERT INTO public.part VALUES (41752, 'burnished maroon powder royal brown', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM BURNISHED STEEL', 43, 'WRAP CASE ', 1693.75, 'sual, unusual pearl');
INSERT INTO public.part VALUES (34157, 'cyan slate lace cream indian', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD BRUSHED COPPER', 10, 'SM DRUM   ', 1091.15, 'carefully enticing ex');
INSERT INTO public.part VALUES (77850, 'lavender brown aquamarine burlywood mint', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO BURNISHED STEEL', 31, 'SM CASE   ', 1827.85, ' regular');
INSERT INTO public.part VALUES (27609, 'cornsilk cream misty yellow chartreuse', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE PLATED NICKEL', 34, 'MED DRUM  ', 1536.60, 'packages. furiously b');
INSERT INTO public.part VALUES (15809, 'navy papaya olive antique navajo', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM BURNISHED BRASS', 30, 'MED BOX   ', 1724.80, 'ackages. ironic r');
INSERT INTO public.part VALUES (4272, 'ivory dark tan blush chocolate', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL BRUSHED BRASS', 30, 'MED DRUM  ', 1176.27, 'kages. final frays ru');
INSERT INTO public.part VALUES (89939, 'deep orange green aquamarine bisque', 'Manufacturer#5           ', 'Brand#52  ', 'ECONOMY ANODIZED BRASS', 3, 'JUMBO CASE', 1928.93, 'press theodolite');
INSERT INTO public.part VALUES (98631, 'thistle papaya almond lavender chiffon', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD POLISHED TIN', 5, 'MED CASE  ', 1629.63, 'ic packages according');
INSERT INTO public.part VALUES (82292, 'drab spring slate red pink', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO BURNISHED COPPER', 34, 'LG PKG    ', 1274.29, 'lithely bold acco');
INSERT INTO public.part VALUES (87529, 'azure sky blanched floral maroon', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM POLISHED TIN', 2, 'LG CASE   ', 1516.52, 'quickly unu');
