INSERT INTO public.part VALUES (50776, 'green cream firebrick olive wheat', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM PLATED TIN', 9, 'WRAP BOX  ', 1726.77, 'ts boos');
INSERT INTO public.part VALUES (184205, 'turquoise blue frosted coral navajo', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD PLATED TIN', 37, 'LG CASE   ', 1289.20, 'ic deposits. fi');
INSERT INTO public.part VALUES (123208, 'midnight coral firebrick rose purple', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO BURNISHED BRASS', 7, 'JUMBO PACK', 1231.20, 'fluffily iro');
INSERT INTO public.part VALUES (45315, 'peach white deep almond hot', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM BRUSHED COPPER', 46, 'WRAP JAR  ', 1260.31, 'to the fluffil');
INSERT INTO public.part VALUES (98729, 'smoke sienna powder slate bisque', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY BRUSHED BRASS', 41, 'SM CASE   ', 1727.72, ' inst');
INSERT INTO public.part VALUES (98988, 'forest linen moccasin almond navy', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE POLISHED NICKEL', 13, 'LG PKG    ', 1986.98, ' pending request');
INSERT INTO public.part VALUES (132136, 'pink gainsboro mint purple lemon', 'Manufacturer#3           ', 'Brand#34  ', 'ECONOMY BRUSHED NICKEL', 49, 'JUMBO PACK', 1168.13, 'ons alon');
INSERT INTO public.part VALUES (25308, 'ghost drab spring seashell snow', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD BURNISHED NICKEL', 16, 'WRAP BOX  ', 1233.30, ' even patterns. q');
INSERT INTO public.part VALUES (149804, 'smoke black midnight ivory goldenrod', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE BURNISHED TIN', 45, 'LG CASE   ', 1853.80, '. pendin');
INSERT INTO public.part VALUES (76221, 'rosy forest powder azure snow', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY ANODIZED COPPER', 12, 'LG BAG    ', 1197.22, 'e of the care');
INSERT INTO public.part VALUES (1089, 'slate goldenrod purple peach dim', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE BURNISHED TIN', 26, 'WRAP CASE ', 990.08, 'dolites sleep acros');
INSERT INTO public.part VALUES (16259, 'thistle coral burnished blue dark', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO ANODIZED NICKEL', 24, 'JUMBO BAG ', 1175.25, 'usly fi');
INSERT INTO public.part VALUES (5937, 'navajo metallic gainsboro drab orange', 'Manufacturer#5           ', 'Brand#51  ', 'ECONOMY ANODIZED NICKEL', 23, 'LG CAN    ', 1842.93, 'ackage');
INSERT INTO public.part VALUES (143246, 'rose steel honeydew dark royal', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL PLATED NICKEL', 21, 'LG JAR    ', 1289.24, 'ns. sl');
INSERT INTO public.part VALUES (38726, 'salmon forest spring goldenrod orange', 'Manufacturer#2           ', 'Brand#21  ', 'MEDIUM POLISHED BRASS', 33, 'WRAP PACK ', 1664.72, 'quests nag abou');
INSERT INTO public.part VALUES (149215, 'light beige coral spring magenta', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY POLISHED TIN', 40, 'JUMBO CAN ', 1264.21, 'ains. fluffily ');
INSERT INTO public.part VALUES (167499, 'burnished deep floral forest olive', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD POLISHED BRASS', 29, 'LG BAG    ', 1566.49, 's. furiously caref');
INSERT INTO public.part VALUES (117989, 'dark lavender sienna gainsboro brown', 'Manufacturer#1           ', 'Brand#15  ', 'STANDARD POLISHED NICKEL', 36, 'WRAP BAG  ', 2006.98, ' instruction');
INSERT INTO public.part VALUES (54756, 'powder chiffon linen spring lawn', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE ANODIZED COPPER', 38, 'WRAP PKG  ', 1710.75, 'across the ');
INSERT INTO public.part VALUES (176865, 'lawn beige drab blanched purple', 'Manufacturer#3           ', 'Brand#31  ', 'PROMO POLISHED NICKEL', 32, 'LG DRUM   ', 1941.86, 'o the pending ');
INSERT INTO public.part VALUES (20479, 'chiffon blue rose slate orange', 'Manufacturer#1           ', 'Brand#12  ', 'PROMO POLISHED STEEL', 34, 'SM BOX    ', 1399.47, ' foxes n');
INSERT INTO public.part VALUES (53621, 'navajo gainsboro lemon pale slate', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM ANODIZED BRASS', 26, 'SM DRUM   ', 1574.62, 'slyly iro');
INSERT INTO public.part VALUES (64322, 'thistle deep green blanched frosted', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY PLATED BRASS', 25, 'LG BOX    ', 1286.32, 'ly express p');
INSERT INTO public.part VALUES (106258, 'beige burlywood saddle chiffon tomato', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO POLISHED BRASS', 33, 'LG PKG    ', 1264.25, 'kly f');
INSERT INTO public.part VALUES (120243, 'lemon blush indian white deep', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO BRUSHED STEEL', 28, 'LG PACK   ', 1263.24, 'kages. theodolit');
INSERT INTO public.part VALUES (198539, 'slate linen sienna deep chiffon', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM PLATED NICKEL', 29, 'WRAP JAR  ', 1637.53, 'ages sle');
INSERT INTO public.part VALUES (143477, 'dodger lace lavender plum chocolate', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO ANODIZED BRASS', 17, 'WRAP CAN  ', 1520.47, 'l packages. special ');
INSERT INTO public.part VALUES (75426, 'misty rose smoke pink lawn', 'Manufacturer#1           ', 'Brand#11  ', 'ECONOMY POLISHED STEEL', 27, 'JUMBO JAR ', 1401.42, 'lar e');
INSERT INTO public.part VALUES (52152, 'lawn blush aquamarine beige honeydew', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM BURNISHED NICKEL', 10, 'MED DRUM  ', 1104.15, 'ate carefully among t');
INSERT INTO public.part VALUES (65300, 'sienna frosted lemon blush salmon', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BURNISHED TIN', 36, 'WRAP DRUM ', 1265.30, 'quietly slyly ironic ');
INSERT INTO public.part VALUES (47661, 'green brown cornsilk puff lace', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE BRUSHED BRASS', 19, 'WRAP PKG  ', 1608.66, 'ons. care');
INSERT INTO public.part VALUES (88118, 'brown cornsilk azure saddle salmon', 'Manufacturer#1           ', 'Brand#13  ', 'LARGE ANODIZED NICKEL', 3, 'JUMBO BOX ', 1106.11, 'es. carefully expre');
INSERT INTO public.part VALUES (114017, 'wheat sienna tan aquamarine powder', 'Manufacturer#3           ', 'Brand#34  ', 'STANDARD ANODIZED TIN', 1, 'LG PKG    ', 1031.01, 'blithely bold, sp');
INSERT INTO public.part VALUES (141126, 'burlywood peach black thistle beige', 'Manufacturer#2           ', 'Brand#23  ', 'PROMO BURNISHED STEEL', 21, 'MED PACK  ', 1167.12, 'urious');
INSERT INTO public.part VALUES (51783, 'sienna thistle gainsboro snow tan', 'Manufacturer#5           ', 'Brand#55  ', 'SMALL PLATED STEEL', 36, 'WRAP PACK ', 1734.78, 'are caref');
INSERT INTO public.part VALUES (148612, 'cyan bisque gainsboro misty blush', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL ANODIZED BRASS', 43, 'SM JAR    ', 1660.61, 'haggle re');
INSERT INTO public.part VALUES (19653, 'pink coral rose dim metallic', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY POLISHED NICKEL', 40, 'JUMBO PACK', 1572.65, 'ng the blithely regula');
INSERT INTO public.part VALUES (134974, 'orange green dim spring lime', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL PLATED STEEL', 10, 'LG PKG    ', 2008.97, 'press r');
INSERT INTO public.part VALUES (169959, 'plum tomato grey navajo smoke', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE PLATED STEEL', 9, 'WRAP PKG  ', 2028.95, 'ally. de');
INSERT INTO public.part VALUES (69174, 'blanched gainsboro pink lace white', 'Manufacturer#2           ', 'Brand#22  ', 'ECONOMY BRUSHED COPPER', 35, 'JUMBO BAG ', 1143.17, 'ses haggle al');
INSERT INTO public.part VALUES (136461, 'blanched chartreuse blush beige black', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE BRUSHED STEEL', 24, 'WRAP CAN  ', 1497.46, 'onic ide');
INSERT INTO public.part VALUES (53751, 'dodger pale lemon rosy deep', 'Manufacturer#4           ', 'Brand#44  ', 'MEDIUM BURNISHED NICKEL', 1, 'MED DRUM  ', 1704.75, 'lyly. fu');
INSERT INTO public.part VALUES (116941, 'cyan black olive slate goldenrod', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY POLISHED COPPER', 5, 'JUMBO CAN ', 1957.94, 'ins sleep ');
INSERT INTO public.part VALUES (128645, 'chocolate powder smoke rose olive', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED COPPER', 18, 'SM DRUM   ', 1673.64, 's. packages hagg');
INSERT INTO public.part VALUES (82941, 'ivory slate dodger chiffon black', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL POLISHED BRASS', 2, 'MED JAR   ', 1923.94, 'accounts');
INSERT INTO public.part VALUES (171420, 'mint gainsboro brown honeydew dodger', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE POLISHED TIN', 31, 'MED CASE  ', 1491.42, 'ly express ex');
INSERT INTO public.part VALUES (183160, 'snow orchid grey violet spring', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM BRUSHED BRASS', 27, 'LG CAN    ', 1243.16, 'wake ');
INSERT INTO public.part VALUES (26918, 'maroon lime linen bisque burlywood', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO PLATED STEEL', 34, 'SM PACK   ', 1844.91, 'its lose. quickly ex');
INSERT INTO public.part VALUES (135074, 'grey white red blush khaki', 'Manufacturer#3           ', 'Brand#34  ', 'MEDIUM PLATED COPPER', 43, 'JUMBO DRUM', 1109.07, 'ing dugouts');
INSERT INTO public.part VALUES (104678, 'moccasin sienna royal lemon rosy', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE POLISHED NICKEL', 44, 'WRAP PKG  ', 1682.67, 'nding packages are ');
INSERT INTO public.part VALUES (85807, 'pale misty white linen goldenrod', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO BURNISHED TIN', 27, 'MED CASE  ', 1792.80, 'egular requests. ');
INSERT INTO public.part VALUES (103281, 'puff grey steel sienna plum', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD BRUSHED STEEL', 50, 'LG BOX    ', 1284.28, '. quickly pendi');
INSERT INTO public.part VALUES (166944, 'cornsilk plum metallic ivory azure', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO PLATED TIN', 2, 'SM BOX    ', 2010.94, 'furiously. b');
INSERT INTO public.part VALUES (41786, 'honeydew cornsilk saddle steel plum', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM POLISHED TIN', 46, 'JUMBO BOX ', 1727.78, 'ackages around the ');
INSERT INTO public.part VALUES (57113, 'blanched sandy thistle burlywood blue', 'Manufacturer#2           ', 'Brand#22  ', 'STANDARD PLATED BRASS', 7, 'MED CASE  ', 1070.11, 'uests.');
INSERT INTO public.part VALUES (34257, 'hot blue sienna rosy peach', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD PLATED STEEL', 12, 'JUMBO PKG ', 1191.25, 'quests ');
INSERT INTO public.part VALUES (23527, 'firebrick lime violet orange tomato', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY ANODIZED TIN', 47, 'MED CAN   ', 1450.52, 'egular pint');
INSERT INTO public.part VALUES (4649, 'blanched lemon cornsilk almond midnight', 'Manufacturer#2           ', 'Brand#25  ', 'SMALL POLISHED BRASS', 34, 'JUMBO DRUM', 1553.64, 'ges are slyly a');
INSERT INTO public.part VALUES (70625, 'coral black indian khaki grey', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM BRUSHED STEEL', 46, 'WRAP BAG  ', 1595.62, 'le furiously');
