INSERT INTO public.part VALUES (102359, 'tomato indian almond sienna linen', 'Manufacturer#5           ', 'Brand#53  ', 'MEDIUM BURNISHED BRASS', 33, 'WRAP PACK ', 1361.35, ' instru');
INSERT INTO public.part VALUES (55302, 'royal metallic cornflower rosy lawn', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY ANODIZED TIN', 7, 'JUMBO PACK', 1257.30, 'packages. ');
INSERT INTO public.part VALUES (154387, 'puff wheat blue moccasin coral', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY ANODIZED NICKEL', 38, 'MED BOX   ', 1441.38, 'y quic');
INSERT INTO public.part VALUES (53649, 'floral turquoise dark beige blanched', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO PLATED COPPER', 2, 'JUMBO BOX ', 1602.64, 'e carefully p');
INSERT INTO public.part VALUES (30678, 'aquamarine olive medium cornsilk tan', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO POLISHED TIN', 4, 'MED JAR   ', 1608.67, 'y blithely regul');
INSERT INTO public.part VALUES (32112, 'peach smoke deep gainsboro turquoise', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM BRUSHED BRASS', 49, 'WRAP CASE ', 1044.11, 'ly slyly iro');
INSERT INTO public.part VALUES (84338, 'spring burnished burlywood peach wheat', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BURNISHED TIN', 23, 'MED JAR   ', 1322.33, 'lly a');
INSERT INTO public.part VALUES (147933, 'medium chocolate antique turquoise peru', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE PLATED COPPER', 5, 'WRAP PACK ', 1980.93, 'tiplier');
INSERT INTO public.part VALUES (195136, 'blanched misty black steel lemon', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE BRUSHED TIN', 9, 'SM BOX    ', 1231.13, 'ing reque');
INSERT INTO public.part VALUES (140565, 'lace dodger aquamarine orchid frosted', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL ANODIZED TIN', 33, 'SM BAG    ', 1605.56, 's wake among the s');
INSERT INTO public.part VALUES (184739, 'orange violet medium brown red', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE BRUSHED NICKEL', 46, 'SM CASE   ', 1823.73, 's mold blithel');
INSERT INTO public.part VALUES (105535, 'orange coral linen antique rosy', 'Manufacturer#3           ', 'Brand#33  ', 'PROMO BRUSHED COPPER', 3, 'LG DRUM   ', 1540.53, 'quickly bold deposit');
INSERT INTO public.part VALUES (33232, 'spring bisque green chartreuse cyan', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE ANODIZED TIN', 33, 'WRAP BOX  ', 1165.23, ' the id');
INSERT INTO public.part VALUES (45979, 'tomato burlywood smoke royal violet', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO ANODIZED BRASS', 22, 'LG PKG    ', 1924.97, 'st the quickly ');
INSERT INTO public.part VALUES (179274, 'navajo antique royal drab coral', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE BRUSHED BRASS', 7, 'LG JAR    ', 1353.27, 'express');
INSERT INTO public.part VALUES (517, 'aquamarine rosy violet moccasin snow', 'Manufacturer#3           ', 'Brand#34  ', 'SMALL BURNISHED COPPER', 30, 'WRAP CAN  ', 1417.51, 'uses. ');
INSERT INTO public.part VALUES (44862, 'cyan dark snow bisque lavender', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO ANODIZED COPPER', 34, 'MED CAN   ', 1806.86, ' fluffily ex');
INSERT INTO public.part VALUES (161173, 'yellow firebrick grey antique sienna', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY PLATED BRASS', 13, 'SM PACK   ', 1234.17, 'packages. slyly regula');
INSERT INTO public.part VALUES (22036, 'gainsboro tan medium brown green', 'Manufacturer#3           ', 'Brand#32  ', 'LARGE ANODIZED STEEL', 23, 'MED BOX   ', 958.03, 're sometime');
INSERT INTO public.part VALUES (117264, 'salmon khaki rose drab lavender', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM POLISHED TIN', 15, 'SM BAG    ', 1281.26, 'ly regular, per');
INSERT INTO public.part VALUES (10346, 'sandy rose yellow almond spring', 'Manufacturer#1           ', 'Brand#15  ', 'STANDARD PLATED BRASS', 7, 'JUMBO CAN ', 1256.34, 'nal i');
INSERT INTO public.part VALUES (156715, 'rose chartreuse antique deep maroon', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD BRUSHED BRASS', 44, 'LG PACK   ', 1771.71, 'ep. fluffi');
INSERT INTO public.part VALUES (172902, 'smoke indian chartreuse azure magenta', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE PLATED COPPER', 45, 'JUMBO PKG ', 1974.90, ' sleep acro');
INSERT INTO public.part VALUES (46737, 'smoke violet frosted lavender navajo', 'Manufacturer#5           ', 'Brand#54  ', 'ECONOMY ANODIZED NICKEL', 22, 'JUMBO CAN ', 1683.73, 'the blithely ');
INSERT INTO public.part VALUES (162683, 'medium sandy aquamarine white pale', 'Manufacturer#1           ', 'Brand#12  ', 'LARGE PLATED COPPER', 36, 'MED BOX   ', 1745.68, '. furiously fina');
