INSERT INTO public.part VALUES (67046, 'tan chiffon steel seashell royal', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL BRUSHED TIN', 22, 'SM JAR    ', 1013.04, ' deposits. furi');
INSERT INTO public.part VALUES (26935, 'sky maroon royal misty medium', 'Manufacturer#2           ', 'Brand#23  ', 'PROMO ANODIZED BRASS', 7, 'SM DRUM   ', 1861.93, 'e the foxes. furio');
INSERT INTO public.part VALUES (55469, 'chartreuse papaya indian black cornflower', 'Manufacturer#5           ', 'Brand#54  ', 'SMALL BRUSHED BRASS', 19, 'JUMBO JAR ', 1424.46, 'inal acc');
INSERT INTO public.part VALUES (95312, 'steel tan burlywood black beige', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BRUSHED TIN', 11, 'LG DRUM   ', 1307.31, 'ests. unusual gr');
INSERT INTO public.part VALUES (36420, 'bisque spring royal dodger maroon', 'Manufacturer#1           ', 'Brand#13  ', 'PROMO BURNISHED TIN', 9, 'WRAP DRUM ', 1356.42, '. fluffily regular dep');
INSERT INTO public.part VALUES (70720, 'rose chiffon almond yellow chartreuse', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM BURNISHED COPPER', 21, 'MED DRUM  ', 1690.72, 'nts sleep f');
INSERT INTO public.part VALUES (19441, 'navy burlywood plum turquoise lime', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD ANODIZED BRASS', 45, 'MED CAN   ', 1360.44, 'unusual somas sleep');
INSERT INTO public.part VALUES (55396, 'brown antique gainsboro orchid slate', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL BURNISHED NICKEL', 12, 'LG PACK   ', 1351.39, 'as detect quic');
INSERT INTO public.part VALUES (66788, 'coral yellow deep ghost lemon', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY ANODIZED TIN', 44, 'MED PACK  ', 1754.78, 'xcuses nag the');
INSERT INTO public.part VALUES (40155, 'frosted gainsboro midnight misty black', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE BURNISHED STEEL', 32, 'MED PACK  ', 1095.15, ' are slyly express fox');
INSERT INTO public.part VALUES (181457, 'sky frosted mint blue medium', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY BRUSHED BRASS', 40, 'WRAP DRUM ', 1538.45, 'uffily even pac');
INSERT INTO public.part VALUES (32443, 'black antique snow blanched rosy', 'Manufacturer#4           ', 'Brand#45  ', 'SMALL POLISHED BRASS', 32, 'JUMBO PKG ', 1375.44, 'ly express dep');
INSERT INTO public.part VALUES (93037, 'linen indian firebrick cream pink', 'Manufacturer#1           ', 'Brand#13  ', 'SMALL BRUSHED TIN', 28, 'LG BOX    ', 1030.03, 'ending dependenc');
INSERT INTO public.part VALUES (30226, 'magenta lavender brown goldenrod dodger', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD POLISHED STEEL', 47, 'LG DRUM   ', 1156.22, 'uriously against the ');
INSERT INTO public.part VALUES (89665, 'violet plum dim mint puff', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM PLATED COPPER', 37, 'MED JAR   ', 1654.66, 'fully furiously sp');
INSERT INTO public.part VALUES (183202, 'tan dodger navy burlywood lawn', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE PLATED COPPER', 2, 'LG CAN    ', 1285.20, 'dolphins nag qui');
INSERT INTO public.part VALUES (131289, 'tan lavender royal chocolate dodger', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO BURNISHED TIN', 30, 'LG JAR    ', 1320.28, 'nt packa');
INSERT INTO public.part VALUES (152197, 'magenta salmon lavender snow cyan', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL ANODIZED STEEL', 28, 'SM PKG    ', 1249.19, 'hely regular accou');
INSERT INTO public.part VALUES (129283, 'blush burlywood orange steel mint', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY BRUSHED BRASS', 40, 'LG BOX    ', 1312.28, 'caref');
INSERT INTO public.part VALUES (121307, 'medium cornsilk burnished pale aquamarine', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO POLISHED COPPER', 7, 'JUMBO JAR ', 1328.30, 'efully across t');
INSERT INTO public.part VALUES (83704, 'moccasin burnished blush navy midnight', 'Manufacturer#2           ', 'Brand#25  ', 'MEDIUM ANODIZED TIN', 21, 'SM CAN    ', 1687.70, 'lyly ');
INSERT INTO public.part VALUES (67567, 'wheat magenta sky ivory slate', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD BRUSHED COPPER', 22, 'WRAP DRUM ', 1534.56, 'y instructions. eve');
INSERT INTO public.part VALUES (125601, 'turquoise olive hot tomato moccasin', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO PLATED BRASS', 25, 'JUMBO BAG ', 1626.60, ' slyly final ac');
INSERT INTO public.part VALUES (52732, 'chiffon smoke burnished saddle dark', 'Manufacturer#2           ', 'Brand#22  ', 'SMALL BRUSHED NICKEL', 11, 'JUMBO BAG ', 1684.73, 'ts cajole slyly ');
INSERT INTO public.part VALUES (23240, 'lace cyan blush midnight turquoise', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO POLISHED STEEL', 11, 'LG CAN    ', 1163.24, 'the furiousl');
INSERT INTO public.part VALUES (2439, 'peru slate chartreuse powder maroon', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY ANODIZED STEEL', 49, 'SM BAG    ', 1341.43, 'requests at ');
INSERT INTO public.part VALUES (143701, 'lawn cornsilk blanched dark beige', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO BRUSHED BRASS', 25, 'WRAP PACK ', 1744.70, 'oze d');
INSERT INTO public.part VALUES (29346, 'cream medium coral drab indian', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY BURNISHED BRASS', 44, 'LG JAR    ', 1275.34, ' final instructions. ');
INSERT INTO public.part VALUES (85462, 'maroon pink red aquamarine moccasin', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY POLISHED NICKEL', 23, 'JUMBO BAG ', 1447.46, 'c dependencies doub');
INSERT INTO public.part VALUES (118686, 'cyan indian black seashell lavender', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE BURNISHED COPPER', 39, 'MED BAG   ', 1704.68, 'ggle idly pendin');
INSERT INTO public.part VALUES (82514, 'navajo blush slate cornsilk goldenrod', 'Manufacturer#2           ', 'Brand#22  ', 'ECONOMY BRUSHED STEEL', 49, 'MED CAN   ', 1496.51, 'egular pinto b');
INSERT INTO public.part VALUES (89786, 'sandy white turquoise indian dim', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD POLISHED BRASS', 10, 'MED PACK  ', 1775.78, 'ts wake s');
INSERT INTO public.part VALUES (110462, 'sandy magenta lime khaki cornsilk', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO PLATED STEEL', 19, 'WRAP BAG  ', 1472.46, 'ests. r');
INSERT INTO public.part VALUES (34017, 'green peru antique magenta navy', 'Manufacturer#5           ', 'Brand#53  ', 'ECONOMY BURNISHED NICKEL', 27, 'LG BAG    ', 951.01, 'fluffily sp');
INSERT INTO public.part VALUES (157182, 'lemon mint pink yellow cornsilk', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM BRUSHED NICKEL', 26, 'MED CASE  ', 1239.18, 'unts. fin');
INSERT INTO public.part VALUES (172656, 'spring orange green lace thistle', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO POLISHED COPPER', 42, 'JUMBO PKG ', 1728.65, '. final');
INSERT INTO public.part VALUES (73592, 'dim smoke ivory brown blush', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD POLISHED NICKEL', 36, 'MED BOX   ', 1565.59, 'ular accounts');
INSERT INTO public.part VALUES (30069, 'ghost honeydew saddle yellow plum', 'Manufacturer#5           ', 'Brand#54  ', 'SMALL PLATED BRASS', 32, 'MED BAG   ', 999.06, 'aggle slyly. furi');
INSERT INTO public.part VALUES (47226, 'tomato beige pink ghost magenta', 'Manufacturer#5           ', 'Brand#51  ', 'ECONOMY BURNISHED NICKEL', 14, 'WRAP CAN  ', 1173.22, 'ake regular');
INSERT INTO public.part VALUES (6555, 'brown thistle frosted sienna moccasin', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE ANODIZED STEEL', 23, 'WRAP BAG  ', 1461.55, 'are furiou');
INSERT INTO public.part VALUES (84098, 'drab misty cream navy rosy', 'Manufacturer#5           ', 'Brand#55  ', 'SMALL PLATED STEEL', 18, 'MED CASE  ', 1082.09, 's run furiousl');
INSERT INTO public.part VALUES (153563, 'antique rosy dark sienna peach', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY ANODIZED COPPER', 41, 'SM JAR    ', 1616.56, 'le final, ');
INSERT INTO public.part VALUES (54937, 'firebrick cyan moccasin lawn maroon', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO BURNISHED TIN', 49, 'WRAP CAN  ', 1891.93, 'uld wake finally ');
INSERT INTO public.part VALUES (94900, 'sienna spring red lace pale', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM BRUSHED COPPER', 18, 'SM CASE   ', 1894.90, ' sleep furiously acros');
INSERT INTO public.part VALUES (164231, 'rosy navy metallic drab goldenrod', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD POLISHED NICKEL', 14, 'WRAP CASE ', 1295.23, ' haggle fu');
INSERT INTO public.part VALUES (120142, 'firebrick navajo dim cream sandy', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO ANODIZED COPPER', 26, 'JUMBO CAN ', 1162.14, 'cajole');
INSERT INTO public.part VALUES (60434, 'cyan moccasin chocolate navajo chiffon', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE BRUSHED NICKEL', 43, 'MED BOX   ', 1394.43, 'counts');
INSERT INTO public.part VALUES (53947, 'orange royal steel chiffon lace', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY BRUSHED BRASS', 29, 'MED PACK  ', 1900.94, 'hely re');
INSERT INTO public.part VALUES (158968, 'lemon almond grey dark ghost', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BURNISHED COPPER', 29, 'LG PACK   ', 2026.96, 'ely final requests nag');
INSERT INTO public.part VALUES (132781, 'papaya smoke white azure coral', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL POLISHED BRASS', 39, 'LG BAG    ', 1813.78, 'egular instructions');
INSERT INTO public.part VALUES (169293, 'goldenrod honeydew dodger black slate', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL BRUSHED NICKEL', 39, 'WRAP JAR  ', 1362.29, 'counts. c');
INSERT INTO public.part VALUES (79025, 'sky moccasin dodger hot orchid', 'Manufacturer#5           ', 'Brand#54  ', 'MEDIUM POLISHED NICKEL', 26, 'WRAP CASE ', 1004.02, 'ronic Tiresias after t');
INSERT INTO public.part VALUES (149751, 'firebrick moccasin sky snow powder', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL PLATED STEEL', 5, 'JUMBO PKG ', 1800.75, 'long the unus');
INSERT INTO public.part VALUES (16355, 'rose peach gainsboro tomato spring', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BRUSHED NICKEL', 22, 'LG CASE   ', 1271.35, 'r requests nag care');
INSERT INTO public.part VALUES (171152, 'chartreuse orchid lime coral olive', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BRUSHED STEEL', 14, 'WRAP PACK ', 1223.15, ' regular instructio');
INSERT INTO public.part VALUES (141365, 'saddle papaya cream lemon dark', 'Manufacturer#5           ', 'Brand#53  ', 'MEDIUM PLATED STEEL', 35, 'WRAP CASE ', 1406.36, 's print blith');
INSERT INTO public.part VALUES (181540, 'lace pink slate antique misty', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL ANODIZED COPPER', 41, 'SM PACK   ', 1621.54, 'ully final');
INSERT INTO public.part VALUES (29153, 'gainsboro snow sienna goldenrod drab', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO POLISHED STEEL', 31, 'JUMBO PACK', 1082.15, 'ns use blithely a');
INSERT INTO public.part VALUES (46058, 'olive orchid burnished burlywood dim', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL BRUSHED COPPER', 42, 'SM PKG    ', 1004.05, 'ounts about the fl');
INSERT INTO public.part VALUES (72177, 'ghost blush olive cream goldenrod', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE ANODIZED STEEL', 37, 'JUMBO DRUM', 1149.17, 'ependencies. ev');
INSERT INTO public.part VALUES (13245, 'blush light pale forest frosted', 'Manufacturer#4           ', 'Brand#41  ', 'ECONOMY POLISHED NICKEL', 49, 'JUMBO BAG ', 1158.24, 'eodolit');
INSERT INTO public.part VALUES (77145, 'bisque chocolate metallic lavender beige', 'Manufacturer#3           ', 'Brand#31  ', 'MEDIUM POLISHED STEEL', 45, 'LG BAG    ', 1122.14, 'kly regu');
INSERT INTO public.part VALUES (136674, 'chocolate cornflower metallic cream grey', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO POLISHED BRASS', 35, 'LG PACK   ', 1710.67, 'refull');
INSERT INTO public.part VALUES (193267, 'navajo khaki yellow misty turquoise', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BURNISHED TIN', 6, 'MED PACK  ', 1360.26, 'sleep blithely.');
INSERT INTO public.part VALUES (30642, 'cornflower grey sienna wheat burnished', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL ANODIZED STEEL', 2, 'SM DRUM   ', 1572.64, 'ual plat');
INSERT INTO public.part VALUES (3045, 'rose spring powder almond steel', 'Manufacturer#3           ', 'Brand#34  ', 'MEDIUM POLISHED COPPER', 36, 'MED CAN   ', 948.04, ' regula');
INSERT INTO public.part VALUES (5475, 'powder lemon rose chiffon seashell', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL ANODIZED COPPER', 27, 'SM BAG    ', 1380.47, 'usual fr');
INSERT INTO public.part VALUES (40245, 'lace chiffon green cream sandy', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY BRUSHED COPPER', 44, 'MED CASE  ', 1185.24, 'xes. s');
INSERT INTO public.part VALUES (32748, 'black light aquamarine dark pale', 'Manufacturer#3           ', 'Brand#32  ', 'SMALL PLATED TIN', 45, 'LG PACK   ', 1680.74, 'fily bold request');
INSERT INTO public.part VALUES (28656, 'navajo lemon pale frosted lawn', 'Manufacturer#4           ', 'Brand#44  ', 'LARGE BRUSHED STEEL', 37, 'LG DRUM   ', 1584.65, 'p after th');
INSERT INTO public.part VALUES (33724, 'royal azure grey yellow navy', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD ANODIZED BRASS', 25, 'SM BAG    ', 1657.72, 'of the furiously unus');
INSERT INTO public.part VALUES (33546, 'honeydew burnished saddle cornflower violet', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL BRUSHED BRASS', 9, 'WRAP JAR  ', 1479.54, 'ar packages u');
INSERT INTO public.part VALUES (154129, 'burnished dodger sky olive sandy', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE PLATED NICKEL', 7, 'MED BOX   ', 1183.12, 'e pendi');
INSERT INTO public.part VALUES (6799, 'seashell wheat hot almond rose', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM BURNISHED NICKEL', 1, 'SM DRUM   ', 1705.79, 'requests wake f');
INSERT INTO public.part VALUES (45426, 'khaki rosy thistle violet blanched', 'Manufacturer#1           ', 'Brand#12  ', 'PROMO PLATED STEEL', 35, 'LG JAR    ', 1371.42, 'ep ironic realms.');
INSERT INTO public.part VALUES (6131, 'coral brown forest puff lemon', 'Manufacturer#1           ', 'Brand#11  ', 'ECONOMY POLISHED NICKEL', 1, 'WRAP BAG  ', 1037.13, 'es must nag across the');
INSERT INTO public.part VALUES (80233, 'burnished red purple orange lawn', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO BRUSHED NICKEL', 41, 'WRAP JAR  ', 1213.23, 'y final pinto be');
INSERT INTO public.part VALUES (25770, 'orchid floral wheat gainsboro honeydew', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY PLATED COPPER', 15, 'WRAP BAG  ', 1695.77, 'ts was furiou');
INSERT INTO public.part VALUES (35624, 'firebrick orchid lace lemon powder', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO BRUSHED COPPER', 30, 'JUMBO CASE', 1559.62, 'thely regula');
INSERT INTO public.part VALUES (52574, 'indian burlywood aquamarine gainsboro blanched', 'Manufacturer#3           ', 'Brand#31  ', 'PROMO ANODIZED COPPER', 13, 'WRAP CAN  ', 1526.57, ' close requests integr');
INSERT INTO public.part VALUES (142766, 'moccasin powder black antique pink', 'Manufacturer#5           ', 'Brand#55  ', 'PROMO ANODIZED TIN', 49, 'SM CAN    ', 1808.76, 'ely blithely final p');
INSERT INTO public.part VALUES (190144, 'gainsboro rosy orchid yellow olive', 'Manufacturer#5           ', 'Brand#51  ', 'ECONOMY PLATED TIN', 47, 'SM DRUM   ', 1234.14, 'riously. carefully f');
INSERT INTO public.part VALUES (91214, 'navy dark coral lemon salmon', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY ANODIZED TIN', 10, 'MED JAR   ', 1205.21, 'jole across the s');
INSERT INTO public.part VALUES (6134, 'brown steel magenta blush sky', 'Manufacturer#4           ', 'Brand#42  ', 'LARGE BURNISHED NICKEL', 18, 'MED CAN   ', 1040.13, 'uests dazzle');
INSERT INTO public.part VALUES (64536, 'chocolate seashell plum saddle red', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO ANODIZED NICKEL', 10, 'JUMBO DRUM', 1500.53, 'g the expre');
INSERT INTO public.part VALUES (156475, 'hot black sienna chocolate puff', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL BRUSHED COPPER', 32, 'WRAP CAN  ', 1531.47, 'ding to the regular in');
INSERT INTO public.part VALUES (168637, 'maroon peach steel slate royal', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM BURNISHED COPPER', 9, 'SM CASE   ', 1705.63, 'gular asymptotes. regu');
INSERT INTO public.part VALUES (176396, 'medium orange goldenrod magenta dark', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL ANODIZED NICKEL', 48, 'LG JAR    ', 1472.39, ', regula');
INSERT INTO public.part VALUES (106135, 'cornflower magenta medium papaya burlywood', 'Manufacturer#4           ', 'Brand#43  ', 'PROMO POLISHED STEEL', 35, 'MED PACK  ', 1141.13, 'ests haggle. sly');
INSERT INTO public.part VALUES (174153, 'drab magenta sienna royal yellow', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE POLISHED TIN', 29, 'MED PKG   ', 1227.15, 'ording to the ');
INSERT INTO public.part VALUES (133268, 'burlywood khaki puff sienna tan', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO BURNISHED BRASS', 29, 'LG BOX    ', 1301.26, 'ckages cajole c');
INSERT INTO public.part VALUES (113464, 'grey light orange cornsilk medium', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL ANODIZED TIN', 46, 'WRAP CASE ', 1477.46, 'ly final accounts agai');
INSERT INTO public.part VALUES (93609, 'goldenrod maroon peru honeydew steel', 'Manufacturer#3           ', 'Brand#35  ', 'LARGE BURNISHED STEEL', 2, 'JUMBO PACK', 1602.60, 'ight ');
INSERT INTO public.part VALUES (92675, 'deep pink light papaya green', 'Manufacturer#1           ', 'Brand#11  ', 'MEDIUM PLATED TIN', 2, 'SM CAN    ', 1667.67, 'luffily regu');
INSERT INTO public.part VALUES (100874, 'lawn brown aquamarine dark blue', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD BRUSHED COPPER', 22, 'WRAP BAG  ', 1874.87, 'g to the quickly e');
