INSERT INTO public.part VALUES (180307, 'orange honeydew misty bisque lawn', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL BURNISHED NICKEL', 19, 'SM PKG    ', 1387.30, 'ckages. fluffily expr');
INSERT INTO public.part VALUES (91907, 'red deep lemon maroon goldenrod', 'Manufacturer#2           ', 'Brand#24  ', 'SMALL POLISHED STEEL', 13, 'WRAP CASE ', 1898.90, 'ironic courts. careful');
INSERT INTO public.part VALUES (190157, 'goldenrod violet khaki almond thistle', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED TIN', 35, 'MED CAN   ', 1247.15, 'ronic packages-');
INSERT INTO public.part VALUES (61197, 'powder bisque thistle honeydew firebrick', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO ANODIZED COPPER', 8, 'WRAP JAR  ', 1158.19, 'apade');
INSERT INTO public.part VALUES (6070, 'orange cornsilk khaki salmon snow', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM POLISHED TIN', 35, 'MED CAN   ', 976.07, 's boo');
INSERT INTO public.part VALUES (166401, 'orchid sky ivory plum purple', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD POLISHED STEEL', 5, 'WRAP JAR  ', 1467.40, '. fluffi');
INSERT INTO public.part VALUES (178684, 'lemon spring saddle forest moccasin', 'Manufacturer#4           ', 'Brand#42  ', 'LARGE BURNISHED STEEL', 1, 'JUMBO DRUM', 1762.68, 'owly ');
INSERT INTO public.part VALUES (152976, 'plum smoke saddle seashell gainsboro', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE ANODIZED NICKEL', 23, 'MED PKG   ', 2028.97, 'y express id');
INSERT INTO public.part VALUES (7243, 'ghost rosy cornflower blue wheat', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY ANODIZED TIN', 1, 'WRAP BOX  ', 1150.24, 'ss instructions: i');
INSERT INTO public.part VALUES (34981, 'sienna white moccasin blue burlywood', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM POLISHED NICKEL', 11, 'MED CAN   ', 1915.98, 'ep fluffil');
INSERT INTO public.part VALUES (175208, 'navy grey floral tomato goldenrod', 'Manufacturer#1           ', 'Brand#15  ', 'STANDARD BURNISHED STEEL', 50, 'WRAP PACK ', 1283.20, 'nts about');
INSERT INTO public.part VALUES (67187, 'firebrick aquamarine snow pale tan', 'Manufacturer#2           ', 'Brand#23  ', 'LARGE ANODIZED STEEL', 1, 'WRAP JAR  ', 1154.18, 'xes m');
INSERT INTO public.part VALUES (111495, 'azure brown hot slate lawn', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO POLISHED COPPER', 4, 'MED CASE  ', 1506.49, 'es. blithely silent ac');
INSERT INTO public.part VALUES (173694, 'navajo magenta salmon tomato moccasin', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL PLATED COPPER', 15, 'WRAP BAG  ', 1767.69, ' quickly ');
INSERT INTO public.part VALUES (6672, 'slate dodger pink blanched thistle', 'Manufacturer#3           ', 'Brand#31  ', 'MEDIUM BURNISHED STEEL', 32, 'LG CASE   ', 1578.67, ' pending accou');
INSERT INTO public.part VALUES (133623, 'frosted thistle coral brown moccasin', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO ANODIZED TIN', 27, 'MED PKG   ', 1656.62, 'arefully above th');
INSERT INTO public.part VALUES (19986, 'burnished gainsboro green goldenrod misty', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD BRUSHED BRASS', 23, 'LG BOX    ', 1905.98, 'oost a');
INSERT INTO public.part VALUES (15405, 'firebrick aquamarine ivory cornflower slate', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE PLATED NICKEL', 24, 'JUMBO BAG ', 1320.40, 'ven re');
INSERT INTO public.part VALUES (69687, 'slate frosted salmon wheat linen', 'Manufacturer#1           ', 'Brand#14  ', 'STANDARD PLATED BRASS', 18, 'MED BAG   ', 1656.68, 't bli');
INSERT INTO public.part VALUES (96152, 'black royal magenta forest lace', 'Manufacturer#2           ', 'Brand#21  ', 'MEDIUM BURNISHED STEEL', 44, 'LG BOX    ', 1148.15, 'ven ideas haggle');
INSERT INTO public.part VALUES (52712, 'lace cornflower orange orchid dark', 'Manufacturer#3           ', 'Brand#35  ', 'PROMO BURNISHED BRASS', 6, 'WRAP PKG  ', 1664.71, ' sleep furiously');
INSERT INTO public.part VALUES (49974, 'green sienna pale purple grey', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY ANODIZED STEEL', 42, 'SM BAG    ', 1923.97, 'fily after t');
INSERT INTO public.part VALUES (159514, 'tan blush wheat tomato mint', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE BRUSHED COPPER', 3, 'LG JAR    ', 1573.51, 'inal plate');
INSERT INTO public.part VALUES (20649, 'firebrick blanched chartreuse puff ghost', 'Manufacturer#4           ', 'Brand#45  ', 'STANDARD BURNISHED STEEL', 50, 'SM PACK   ', 1569.64, 'ccounts na');
INSERT INTO public.part VALUES (26217, 'papaya light sienna red pale', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD BURNISHED BRASS', 20, 'WRAP PACK ', 1143.21, 'ully ironic acco');
INSERT INTO public.part VALUES (17088, 'maroon lime blue purple smoke', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL PLATED TIN', 42, 'JUMBO DRUM', 1005.08, ' ironic f');
INSERT INTO public.part VALUES (197531, 'misty rosy hot burnished thistle', 'Manufacturer#2           ', 'Brand#24  ', 'ECONOMY BRUSHED TIN', 32, 'MED CASE  ', 1628.53, 'ongside of th');
INSERT INTO public.part VALUES (41030, 'floral drab aquamarine cream chiffon', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE POLISHED TIN', 8, 'LG PKG    ', 971.03, 'osits.');
INSERT INTO public.part VALUES (167739, 'rosy honeydew mint white grey', 'Manufacturer#2           ', 'Brand#22  ', 'SMALL ANODIZED STEEL', 36, 'LG CASE   ', 1806.73, 'es are by th');
INSERT INTO public.part VALUES (51421, 'turquoise indian deep frosted gainsboro', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY PLATED BRASS', 5, 'SM PKG    ', 1372.42, ' blithely r');
INSERT INTO public.part VALUES (110309, 'lavender maroon turquoise chocolate violet', 'Manufacturer#3           ', 'Brand#34  ', 'PROMO PLATED STEEL', 13, 'LG BOX    ', 1319.30, ' express, do');
INSERT INTO public.part VALUES (96883, 'midnight turquoise navajo khaki sky', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE POLISHED TIN', 8, 'JUMBO DRUM', 1879.88, 'r patterns ');
INSERT INTO public.part VALUES (133170, 'sienna green dodger floral brown', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE BRUSHED STEEL', 38, 'MED PKG   ', 1203.17, 'bove the carefu');
INSERT INTO public.part VALUES (190884, 'powder khaki floral blue goldenrod', 'Manufacturer#5           ', 'Brand#55  ', 'ECONOMY ANODIZED TIN', 4, 'LG DRUM   ', 1974.88, 'onic foxes sl');
INSERT INTO public.part VALUES (111201, 'medium peru brown navy orange', 'Manufacturer#3           ', 'Brand#33  ', 'SMALL BRUSHED BRASS', 23, 'MED BOX   ', 1212.20, '. blithely bold exc');
INSERT INTO public.part VALUES (198953, 'tan indian firebrick papaya lemon', 'Manufacturer#3           ', 'Brand#34  ', 'STANDARD ANODIZED NICKEL', 24, 'SM JAR    ', 2051.95, 'osits. furiously reg');
INSERT INTO public.part VALUES (104316, 'smoke blush ivory light antique', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY BRUSHED NICKEL', 8, 'JUMBO JAR ', 1320.31, ' carefully ev');
INSERT INTO public.part VALUES (180591, 'cornsilk drab thistle peach dodger', 'Manufacturer#3           ', 'Brand#31  ', 'STANDARD PLATED COPPER', 11, 'WRAP DRUM ', 1671.59, 'foxes. final deposits');
INSERT INTO public.part VALUES (183725, 'powder hot firebrick orange chartreuse', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD PLATED STEEL', 18, 'MED BOX   ', 1808.72, ' ideas cajol');
INSERT INTO public.part VALUES (107827, 'peach chiffon chocolate lace royal', 'Manufacturer#5           ', 'Brand#52  ', 'MEDIUM POLISHED NICKEL', 31, 'SM BAG    ', 1834.82, 'quickly ab');
INSERT INTO public.part VALUES (21197, 'green yellow floral ivory rosy', 'Manufacturer#2           ', 'Brand#24  ', 'SMALL BRUSHED TIN', 8, 'WRAP BOX  ', 1118.19, 'e. regular packages c');
INSERT INTO public.part VALUES (114491, 'misty cream lawn medium deep', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BRUSHED STEEL', 5, 'LG PACK   ', 1505.49, 's. doggedly ironic e');
INSERT INTO public.part VALUES (33955, 'black deep drab khaki spring', 'Manufacturer#1           ', 'Brand#12  ', 'LARGE BRUSHED NICKEL', 44, 'LG CAN    ', 1888.95, 'es. special, unu');
INSERT INTO public.part VALUES (99923, 'blue yellow grey lawn almond', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY ANODIZED BRASS', 38, 'MED CASE  ', 1922.92, 'dolites wak');
INSERT INTO public.part VALUES (1675, 'antique orchid burlywood orange lime', 'Manufacturer#3           ', 'Brand#32  ', 'SMALL POLISHED TIN', 45, 'MED PACK  ', 1576.67, 'eans nag across');
INSERT INTO public.part VALUES (76742, 'violet blue navajo almond magenta', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY ANODIZED STEEL', 8, 'MED CAN   ', 1718.74, 'en, pending pin');
INSERT INTO public.part VALUES (120083, 'navy burnished peach dodger firebrick', 'Manufacturer#5           ', 'Brand#55  ', 'STANDARD BRUSHED STEEL', 5, 'MED CASE  ', 1103.08, 'he pl');
INSERT INTO public.part VALUES (155396, 'coral linen khaki cornsilk smoke', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL BURNISHED COPPER', 16, 'SM BOX    ', 1451.39, 'e slyly bold do');
INSERT INTO public.part VALUES (14256, 'pale pink black spring blanched', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM BRUSHED STEEL', 10, 'SM CAN    ', 1170.25, ': carefully');
INSERT INTO public.part VALUES (10908, 'dark purple royal spring steel', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED STEEL', 1, 'SM DRUM   ', 1818.90, 'thely ironic packages');
INSERT INTO public.part VALUES (154782, 'cyan purple navajo lavender pale', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL BRUSHED COPPER', 48, 'WRAP BOX  ', 1836.78, 'ffily iro');
INSERT INTO public.part VALUES (62623, 'midnight coral papaya dodger dim', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE ANODIZED STEEL', 35, 'JUMBO PKG ', 1585.62, 'ly pending ideas. ');
INSERT INTO public.part VALUES (11077, 'burlywood plum cornsilk linen pink', 'Manufacturer#3           ', 'Brand#31  ', 'LARGE POLISHED TIN', 12, 'JUMBO BOX ', 988.07, 'se blit');
INSERT INTO public.part VALUES (145340, 'lavender medium chiffon lemon sandy', 'Manufacturer#2           ', 'Brand#25  ', 'LARGE ANODIZED TIN', 14, 'LG DRUM   ', 1385.34, 'sleep quickly.');
INSERT INTO public.part VALUES (81117, 'coral orange chocolate wheat slate', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO PLATED COPPER', 47, 'MED PACK  ', 1098.11, ' carefully u');
INSERT INTO public.part VALUES (35412, 'khaki turquoise moccasin metallic lace', 'Manufacturer#1           ', 'Brand#11  ', 'MEDIUM PLATED COPPER', 9, 'WRAP JAR  ', 1347.41, 'sly unusual pinto b');
INSERT INTO public.part VALUES (8849, 'medium grey cream pink maroon', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD POLISHED NICKEL', 2, 'WRAP PACK ', 1757.84, 'usly eve');
INSERT INTO public.part VALUES (106584, 'ivory cornflower medium midnight sandy', 'Manufacturer#2           ', 'Brand#21  ', 'PROMO ANODIZED COPPER', 14, 'WRAP BAG  ', 1590.58, 'yly fin');
INSERT INTO public.part VALUES (152049, 'lawn burlywood mint royal turquoise', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BRUSHED COPPER', 50, 'LG CASE   ', 1101.04, 'counts. blit');
INSERT INTO public.part VALUES (17911, 'grey peach tan khaki white', 'Manufacturer#1           ', 'Brand#12  ', 'LARGE ANODIZED STEEL', 24, 'LG DRUM   ', 1828.91, 've th');
