INSERT INTO public.part VALUES (169440, 'dark violet beige lemon cyan', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL BRUSHED TIN', 19, 'SM BAG    ', 1509.44, 'e carefully ');
INSERT INTO public.part VALUES (133918, 'light sky ghost tomato rose', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL PLATED TIN', 27, 'WRAP CASE ', 1951.91, 's dependenc');
INSERT INTO public.part VALUES (66859, 'tomato chiffon tan hot drab', 'Manufacturer#5           ', 'Brand#51  ', 'SMALL POLISHED TIN', 42, 'JUMBO JAR ', 1825.85, 'quickly care');
INSERT INTO public.part VALUES (66888, 'pink blush lime beige thistle', 'Manufacturer#1           ', 'Brand#14  ', 'ECONOMY POLISHED NICKEL', 27, 'LG JAR    ', 1854.88, 'regular fo');
INSERT INTO public.part VALUES (180912, 'frosted cyan lace navajo metallic', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY ANODIZED COPPER', 4, 'SM PACK   ', 1992.91, 'r, regu');
INSERT INTO public.part VALUES (38497, 'green deep sienna powder peach', 'Manufacturer#2           ', 'Brand#23  ', 'PROMO BRUSHED TIN', 10, 'WRAP PKG  ', 1435.49, 'iously even ');
INSERT INTO public.part VALUES (79286, 'maroon chartreuse bisque slate orange', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE POLISHED STEEL', 29, 'WRAP JAR  ', 1265.28, 'is. sp');
INSERT INTO public.part VALUES (120433, 'moccasin brown azure cream seashell', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BRUSHED BRASS', 40, 'WRAP PACK ', 1453.43, 'es cajo');
INSERT INTO public.part VALUES (128681, 'sky khaki lemon firebrick orchid', 'Manufacturer#4           ', 'Brand#42  ', 'ECONOMY ANODIZED TIN', 12, 'JUMBO JAR ', 1709.68, 'counts ');
INSERT INTO public.part VALUES (185934, 'black grey snow midnight bisque', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD POLISHED TIN', 50, 'WRAP JAR  ', 2019.93, 's wak');
INSERT INTO public.part VALUES (40024, 'lace deep lime mint gainsboro', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO ANODIZED NICKEL', 20, 'JUMBO BAG ', 964.02, 'uests boost fu');
INSERT INTO public.part VALUES (163275, 'sky pale tan green lemon', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM POLISHED BRASS', 42, 'SM BAG    ', 1338.27, 's accounts. even depos');
INSERT INTO public.part VALUES (31884, 'linen almond cyan brown violet', 'Manufacturer#5           ', 'Brand#53  ', 'ECONOMY BURNISHED NICKEL', 29, 'WRAP PACK ', 1815.88, 'along the even de');
INSERT INTO public.part VALUES (111010, 'chocolate moccasin indian red dodger', 'Manufacturer#1           ', 'Brand#15  ', 'ECONOMY POLISHED TIN', 19, 'MED PACK  ', 1021.01, 'inal dolphi');
INSERT INTO public.part VALUES (56518, 'cornflower chiffon red peach chocolate', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO POLISHED TIN', 33, 'LG DRUM   ', 1474.51, 'onic p');
INSERT INTO public.part VALUES (101418, 'orange azure burlywood firebrick gainsboro', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE POLISHED NICKEL', 20, 'WRAP PACK ', 1419.41, 'encies. blithely even ');
INSERT INTO public.part VALUES (187669, 'aquamarine grey lace olive pink', 'Manufacturer#5           ', 'Brand#55  ', 'LARGE ANODIZED NICKEL', 50, 'SM PKG    ', 1756.66, 'oxes above the care');
INSERT INTO public.part VALUES (124039, 'midnight mint floral slate pink', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE POLISHED STEEL', 13, 'LG DRUM   ', 1063.03, '. deposits are blit');
INSERT INTO public.part VALUES (2400, 'powder burlywood lace azure salmon', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO POLISHED NICKEL', 47, 'SM PKG    ', 1302.40, 'y. slyly unusual f');
INSERT INTO public.part VALUES (98008, 'purple cornsilk frosted papaya lawn', 'Manufacturer#1           ', 'Brand#14  ', 'SMALL POLISHED NICKEL', 44, 'MED CASE  ', 1006.00, 'kly under the ca');
INSERT INTO public.part VALUES (46783, 'ghost papaya sandy floral navajo', 'Manufacturer#5           ', 'Brand#55  ', 'PROMO ANODIZED COPPER', 32, 'SM PKG    ', 1729.78, 'nooze at the');
INSERT INTO public.part VALUES (48648, 'white dim seashell antique sandy', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD BRUSHED NICKEL', 19, 'SM BAG    ', 1596.64, 'ully. blithely brave');
INSERT INTO public.part VALUES (134109, 'snow navy slate grey dim', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL PLATED STEEL', 14, 'SM BOX    ', 1143.10, ' will have to dete');
INSERT INTO public.part VALUES (61928, 'ghost indian seashell metallic navajo', 'Manufacturer#5           ', 'Brand#55  ', 'LARGE BURNISHED NICKEL', 42, 'LG BOX    ', 1889.92, 'lly qui');
INSERT INTO public.part VALUES (2764, 'drab magenta snow plum powder', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO PLATED COPPER', 6, 'WRAP JAR  ', 1666.76, '. careful');
INSERT INTO public.part VALUES (134652, 'peach rose forest lime magenta', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD ANODIZED STEEL', 32, 'MED PKG   ', 1686.65, 'sleep fluffil');
INSERT INTO public.part VALUES (150879, 'gainsboro pale spring sandy lemon', 'Manufacturer#3           ', 'Brand#33  ', 'LARGE BRUSHED STEEL', 39, 'WRAP JAR  ', 1929.87, 'sits sleep across ');
INSERT INTO public.part VALUES (42658, 'rose orange antique green drab', 'Manufacturer#1           ', 'Brand#11  ', 'STANDARD BRUSHED BRASS', 38, 'MED BAG   ', 1600.65, 'ly. unu');
INSERT INTO public.part VALUES (57028, 'olive burlywood blanched turquoise lawn', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE PLATED TIN', 5, 'LG PKG    ', 985.02, 'ickly special packages');
INSERT INTO public.part VALUES (64282, 'plum dark tomato sandy metallic', 'Manufacturer#3           ', 'Brand#31  ', 'STANDARD BURNISHED COPPER', 38, 'JUMBO BOX ', 1246.28, ' except the unusua');
INSERT INTO public.part VALUES (14111, 'lawn white midnight magenta cyan', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM PLATED STEEL', 43, 'SM CAN    ', 1025.11, 'arefully expres');
INSERT INTO public.part VALUES (147532, 'papaya sienna peru plum bisque', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD POLISHED COPPER', 38, 'MED PKG   ', 1579.53, 'lyly special accoun');
INSERT INTO public.part VALUES (193980, 'plum dodger coral medium salmon', 'Manufacturer#3           ', 'Brand#32  ', 'SMALL BRUSHED NICKEL', 10, 'MED BAG   ', 2073.98, ', pen');
INSERT INTO public.part VALUES (29212, 'firebrick lime light saddle steel', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY POLISHED TIN', 5, 'LG DRUM   ', 1141.21, 'ccounts. furiousl');
INSERT INTO public.part VALUES (56770, 'drab powder azure dim brown', 'Manufacturer#2           ', 'Brand#22  ', 'PROMO ANODIZED STEEL', 22, 'LG PACK   ', 1726.77, 'e furiously silent dep');
INSERT INTO public.part VALUES (129884, 'papaya cornflower light lawn dim', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD ANODIZED TIN', 6, 'JUMBO BAG ', 1913.88, 'ggle qu');
INSERT INTO public.part VALUES (34918, 'orange midnight frosted dark rosy', 'Manufacturer#2           ', 'Brand#24  ', 'ECONOMY POLISHED STEEL', 48, 'SM DRUM   ', 1852.91, 'lly final ideas use');
INSERT INTO public.part VALUES (133330, 'blush thistle dark medium steel', 'Manufacturer#4           ', 'Brand#43  ', 'STANDARD BURNISHED STEEL', 3, 'LG BOX    ', 1363.33, 'pending');
INSERT INTO public.part VALUES (117327, 'white deep snow floral burlywood', 'Manufacturer#4           ', 'Brand#41  ', 'SMALL PLATED BRASS', 46, 'JUMBO PACK', 1344.32, 'ic, even accounts');
INSERT INTO public.part VALUES (5472, 'frosted tomato cornsilk goldenrod bisque', 'Manufacturer#1           ', 'Brand#13  ', 'STANDARD BRUSHED STEEL', 9, 'SM BOX    ', 1377.47, 'iousl');
INSERT INTO public.part VALUES (114148, 'chartreuse lime cornflower medium tomato', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD POLISHED BRASS', 25, 'WRAP BOX  ', 1162.14, 'f the ');
INSERT INTO public.part VALUES (196306, 'cream tomato frosted rosy linen', 'Manufacturer#3           ', 'Brand#35  ', 'ECONOMY PLATED STEEL', 9, 'WRAP PACK ', 1402.30, 'osits boos');
INSERT INTO public.part VALUES (181461, 'cornflower pink wheat red mint', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL PLATED NICKEL', 47, 'SM PACK   ', 1542.46, 'nooze quickly. silent ');
INSERT INTO public.part VALUES (146910, 'dodger puff honeydew sky navajo', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM PLATED COPPER', 12, 'SM BAG    ', 1956.91, ' carefully fi');
INSERT INTO public.part VALUES (121043, 'grey khaki aquamarine burnished pale', 'Manufacturer#2           ', 'Brand#21  ', 'MEDIUM POLISHED STEEL', 18, 'MED CASE  ', 1064.04, 'l pinto beans sle');
INSERT INTO public.part VALUES (10226, 'pink olive orange powder sky', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM BURNISHED BRASS', 12, 'SM CAN    ', 1136.22, 'sts: c');
INSERT INTO public.part VALUES (143207, 'steel burnished sienna pale magenta', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD PLATED NICKEL', 32, 'WRAP PKG  ', 1250.20, 's foxes! quickl');
INSERT INTO public.part VALUES (100405, 'bisque frosted brown rose lavender', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM ANODIZED TIN', 45, 'JUMBO CASE', 1405.40, 'ow packages.');
INSERT INTO public.part VALUES (67269, 'floral chocolate sandy cream aquamarine', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD BURNISHED STEEL', 27, 'WRAP DRUM ', 1236.26, 'sts wa');
INSERT INTO public.part VALUES (162046, 'midnight sienna rosy gainsboro bisque', 'Manufacturer#2           ', 'Brand#22  ', 'STANDARD BRUSHED COPPER', 39, 'LG BAG    ', 1108.04, 'tornis slee');
INSERT INTO public.part VALUES (16839, 'thistle dodger navy chiffon lime', 'Manufacturer#1           ', 'Brand#12  ', 'ECONOMY PLATED BRASS', 17, 'MED JAR   ', 1755.83, 'nticing pinto');
INSERT INTO public.part VALUES (135158, 'seashell dark aquamarine sandy rose', 'Manufacturer#4           ', 'Brand#43  ', 'SMALL PLATED BRASS', 9, 'SM PACK   ', 1193.15, 'unusu');
INSERT INTO public.part VALUES (6807, 'drab wheat snow moccasin saddle', 'Manufacturer#1           ', 'Brand#12  ', 'LARGE PLATED NICKEL', 48, 'JUMBO PACK', 1713.80, ' instructions de');
INSERT INTO public.part VALUES (153428, 'drab steel midnight beige lace', 'Manufacturer#4           ', 'Brand#43  ', 'LARGE BURNISHED TIN', 31, 'WRAP CAN  ', 1481.42, 's instru');
INSERT INTO public.part VALUES (142634, 'papaya peru peach chocolate blush', 'Manufacturer#5           ', 'Brand#51  ', 'PROMO ANODIZED BRASS', 25, 'WRAP JAR  ', 1676.63, 'al accounts are sl');
INSERT INTO public.part VALUES (44823, 'coral peru sky dodger cream', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM BURNISHED BRASS', 27, 'SM BAG    ', 1767.82, ' ironicall');
INSERT INTO public.part VALUES (12574, 'blush antique almond navy burlywood', 'Manufacturer#5           ', 'Brand#55  ', 'LARGE BRUSHED BRASS', 45, 'SM BOX    ', 1486.57, 'old braids since the ');
INSERT INTO public.part VALUES (99386, 'forest firebrick khaki plum lawn', 'Manufacturer#1           ', 'Brand#13  ', 'LARGE POLISHED BRASS', 40, 'LG JAR    ', 1385.38, 'nding instructions');
INSERT INTO public.part VALUES (128333, 'powder cyan lawn forest ivory', 'Manufacturer#1           ', 'Brand#15  ', 'PROMO BRUSHED COPPER', 9, 'SM CAN    ', 1361.33, ' furiously acros');
INSERT INTO public.part VALUES (144944, 'wheat blush ivory moccasin beige', 'Manufacturer#4           ', 'Brand#45  ', 'ECONOMY BURNISHED BRASS', 10, 'MED BAG   ', 1988.94, 'ar packages hang sl');
INSERT INTO public.part VALUES (144691, 'dim smoke mint rosy chocolate', 'Manufacturer#3           ', 'Brand#33  ', 'PROMO BRUSHED TIN', 49, 'MED JAR   ', 1735.69, 'ss requ');
INSERT INTO public.part VALUES (199019, 'thistle slate rosy orchid beige', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BURNISHED STEEL', 21, 'JUMBO PACK', 1118.01, 'c foxes ha');
INSERT INTO public.part VALUES (30357, 'powder wheat antique magenta cornsilk', 'Manufacturer#4           ', 'Brand#43  ', 'ECONOMY ANODIZED COPPER', 28, 'MED BAG   ', 1287.35, 'are furiously final');
INSERT INTO public.part VALUES (130701, 'light midnight steel lawn blanched', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM POLISHED STEEL', 25, 'LG DRUM   ', 1731.70, 'nal pack');
INSERT INTO public.part VALUES (31490, 'chocolate honeydew metallic dim beige', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL PLATED NICKEL', 30, 'SM DRUM   ', 1421.49, 'ickly furious reques');
INSERT INTO public.part VALUES (23049, 'salmon rosy magenta cream purple', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL ANODIZED STEEL', 24, 'JUMBO PKG ', 972.04, 'the final reques');
INSERT INTO public.part VALUES (109098, 'blush red snow purple dim', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD BRUSHED BRASS', 50, 'MED JAR   ', 1107.09, ' to the quickl');
INSERT INTO public.part VALUES (194335, 'seashell ghost metallic orchid blush', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL BURNISHED STEEL', 10, 'MED BAG   ', 1429.33, 'cies. regular depen');
INSERT INTO public.part VALUES (36093, 'honeydew grey peru chiffon beige', 'Manufacturer#4           ', 'Brand#41  ', 'PROMO ANODIZED NICKEL', 26, 'LG PACK   ', 1029.09, 'along');
INSERT INTO public.part VALUES (169948, 'grey aquamarine plum navajo ghost', 'Manufacturer#3           ', 'Brand#35  ', 'STANDARD BURNISHED BRASS', 46, 'WRAP PACK ', 2017.94, '. pendi');
INSERT INTO public.part VALUES (120627, 'navy tan red burlywood blush', 'Manufacturer#2           ', 'Brand#25  ', 'STANDARD ANODIZED STEEL', 47, 'WRAP BOX  ', 1647.62, 'unusual foxes w');
INSERT INTO public.part VALUES (147582, 'peach cornflower purple ivory smoke', 'Manufacturer#4           ', 'Brand#42  ', 'PROMO POLISHED TIN', 46, 'SM PKG    ', 1629.58, 'uriously at t');
INSERT INTO public.part VALUES (130885, 'violet lime sienna pink black', 'Manufacturer#3           ', 'Brand#35  ', 'MEDIUM BURNISHED NICKEL', 49, 'SM CASE   ', 1915.88, 'yly even pinto be');
INSERT INTO public.part VALUES (25974, 'papaya peru puff frosted azure', 'Manufacturer#5           ', 'Brand#52  ', 'SMALL POLISHED BRASS', 15, 'SM BOX    ', 1899.97, 'deposits haggle sl');
INSERT INTO public.part VALUES (183122, 'almond steel papaya puff grey', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD BRUSHED NICKEL', 43, 'SM BAG    ', 1205.12, 'furio');
INSERT INTO public.part VALUES (54772, 'sienna dim violet peach lemon', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY BURNISHED STEEL', 18, 'SM PACK   ', 1726.77, 'y final platelets');
INSERT INTO public.part VALUES (188862, 'seashell white drab powder peach', 'Manufacturer#2           ', 'Brand#24  ', 'PROMO POLISHED BRASS', 49, 'JUMBO DRUM', 1950.86, 'eposits maintain ');
INSERT INTO public.part VALUES (2035, 'blue dim puff aquamarine steel', 'Manufacturer#3           ', 'Brand#35  ', 'PROMO POLISHED TIN', 36, 'JUMBO CAN ', 937.03, 'uffily regu');
INSERT INTO public.part VALUES (176352, 'aquamarine brown bisque lime rosy', 'Manufacturer#1           ', 'Brand#13  ', 'MEDIUM ANODIZED STEEL', 8, 'JUMBO BOX ', 1428.35, 'kly slyly ironic');
INSERT INTO public.part VALUES (22602, 'spring sienna lavender seashell pink', 'Manufacturer#1           ', 'Brand#11  ', 'ECONOMY BURNISHED BRASS', 30, 'LG JAR    ', 1524.60, 'lar reque');
INSERT INTO public.part VALUES (194061, 'brown misty dim salmon saddle', 'Manufacturer#3           ', 'Brand#32  ', 'MEDIUM BRUSHED STEEL', 15, 'JUMBO CASE', 1155.06, 's cajole around the q');
INSERT INTO public.part VALUES (15791, 'navajo khaki powder tan chiffon', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY BURNISHED COPPER', 22, 'JUMBO BAG ', 1706.79, 'ackages. regula');
INSERT INTO public.part VALUES (111797, 'hot blush beige green slate', 'Manufacturer#4           ', 'Brand#45  ', 'LARGE POLISHED TIN', 40, 'JUMBO JAR ', 1808.79, 'furiously a');
INSERT INTO public.part VALUES (114631, 'chiffon azure lemon floral pale', 'Manufacturer#1           ', 'Brand#11  ', 'PROMO BURNISHED COPPER', 43, 'LG PACK   ', 1645.63, 'hely ab');
INSERT INTO public.part VALUES (140451, 'orange olive rose maroon cornflower', 'Manufacturer#3           ', 'Brand#33  ', 'STANDARD BURNISHED COPPER', 34, 'LG JAR    ', 1491.45, 'ily above the carefu');
INSERT INTO public.part VALUES (139665, 'pale midnight blanched yellow slate', 'Manufacturer#2           ', 'Brand#25  ', 'ECONOMY ANODIZED BRASS', 35, 'JUMBO CAN ', 1704.66, 'ual deposits. the');
INSERT INTO public.part VALUES (169148, 'plum chiffon burnished puff lawn', 'Manufacturer#5           ', 'Brand#53  ', 'PROMO ANODIZED COPPER', 43, 'JUMBO DRUM', 1217.14, 'ep slyly accor');
INSERT INTO public.part VALUES (11913, 'magenta hot linen blush sienna', 'Manufacturer#2           ', 'Brand#24  ', 'STANDARD POLISHED COPPER', 6, 'SM DRUM   ', 1824.91, 'kly b');
INSERT INTO public.part VALUES (165174, 'lavender lime dodger pale hot', 'Manufacturer#4           ', 'Brand#45  ', 'PROMO PLATED BRASS', 32, 'JUMBO CASE', 1239.17, 'express, i');
INSERT INTO public.part VALUES (98765, 'tan sky mint bisque drab', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM BRUSHED STEEL', 33, 'MED BAG   ', 1763.76, 'ackages. ');
INSERT INTO public.part VALUES (23237, 'navy cornflower papaya white thistle', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL PLATED BRASS', 40, 'SM PKG    ', 1160.23, 'ng to the r');
INSERT INTO public.part VALUES (106880, 'light seashell blush brown dodger', 'Manufacturer#2           ', 'Brand#23  ', 'SMALL BURNISHED TIN', 15, 'WRAP PACK ', 1886.88, 'ly. slyly regular pa');
INSERT INTO public.part VALUES (103648, 'sienna peru maroon papaya pink', 'Manufacturer#2           ', 'Brand#23  ', 'STANDARD POLISHED TIN', 11, 'SM CASE   ', 1651.64, 'ges sleep');
INSERT INTO public.part VALUES (56260, 'honeydew maroon indian brown cornflower', 'Manufacturer#4           ', 'Brand#43  ', 'SMALL BRUSHED TIN', 41, 'JUMBO BAG ', 1216.26, ' quickly bold plat');
INSERT INTO public.part VALUES (57774, 'white blanched puff moccasin lemon', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BURNISHED BRASS', 40, 'JUMBO JAR ', 1731.77, 'times final');
INSERT INTO public.part VALUES (75211, 'black bisque antique firebrick red', 'Manufacturer#5           ', 'Brand#53  ', 'SMALL BRUSHED TIN', 31, 'SM PACK   ', 1186.21, 'y unusual de');
INSERT INTO public.part VALUES (153764, 'navy lace grey dim rosy', 'Manufacturer#5           ', 'Brand#51  ', 'LARGE PLATED STEEL', 32, 'SM BOX    ', 1817.76, 'r deposits ca');
INSERT INTO public.part VALUES (61620, 'seashell puff mint cyan brown', 'Manufacturer#1           ', 'Brand#14  ', 'PROMO BRUSHED STEEL', 16, 'JUMBO DRUM', 1581.62, 'dependencies boost f');
INSERT INTO public.part VALUES (26813, 'steel seashell plum slate blue', 'Manufacturer#5           ', 'Brand#51  ', 'STANDARD PLATED BRASS', 50, 'WRAP DRUM ', 1739.81, 'osits. carefully ');
INSERT INTO public.part VALUES (193738, 'almond salmon chocolate firebrick dodger', 'Manufacturer#3           ', 'Brand#33  ', 'MEDIUM ANODIZED NICKEL', 13, 'SM BOX    ', 1831.73, 'nts det');
INSERT INTO public.part VALUES (20780, 'royal chartreuse floral thistle burnished', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD BURNISHED TIN', 21, 'WRAP PACK ', 1700.78, 'jole furi');
INSERT INTO public.part VALUES (133992, 'metallic rosy sienna sandy red', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE BURNISHED NICKEL', 15, 'JUMBO CASE', 2025.99, 's. furiously ironic re');
INSERT INTO public.part VALUES (10119, 'slate floral plum aquamarine blush', 'Manufacturer#3           ', 'Brand#32  ', 'PROMO BRUSHED TIN', 34, 'MED BOX   ', 1029.11, 'ss accounts print');
INSERT INTO public.part VALUES (59043, 'coral pale navy navajo hot', 'Manufacturer#1           ', 'Brand#14  ', 'LARGE BRUSHED TIN', 27, 'LG PACK   ', 1002.04, 'd acco');
INSERT INTO public.part VALUES (112502, 'gainsboro white sky maroon papaya', 'Manufacturer#2           ', 'Brand#24  ', 'LARGE POLISHED BRASS', 41, 'SM CAN    ', 1514.50, 'y unusual ');
INSERT INTO public.part VALUES (120173, 'azure burnished tomato mint spring', 'Manufacturer#1           ', 'Brand#12  ', 'SMALL ANODIZED TIN', 2, 'LG DRUM   ', 1193.17, 'le quickly');
INSERT INTO public.part VALUES (51558, 'royal aquamarine wheat tan honeydew', 'Manufacturer#4           ', 'Brand#41  ', 'MEDIUM PLATED NICKEL', 44, 'JUMBO PACK', 1509.55, ' final excuses haggl');
INSERT INTO public.part VALUES (164976, 'yellow black almond bisque purple', 'Manufacturer#1           ', 'Brand#11  ', 'SMALL PLATED COPPER', 35, 'JUMBO JAR ', 2040.97, 'the careful');
INSERT INTO public.part VALUES (32036, 'saddle lavender green chartreuse puff', 'Manufacturer#3           ', 'Brand#32  ', 'STANDARD PLATED TIN', 49, 'WRAP DRUM ', 968.03, 'ckages ');
INSERT INTO public.part VALUES (24499, 'slate midnight linen sky pale', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BURNISHED NICKEL', 21, 'SM PACK   ', 1423.49, '. quickly');
INSERT INTO public.part VALUES (146731, 'wheat almond peru chiffon lime', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY PLATED BRASS', 27, 'SM DRUM   ', 1777.73, 'latelets');
INSERT INTO public.part VALUES (181840, 'violet pale brown steel salmon', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM PLATED TIN', 31, 'WRAP CASE ', 1921.84, 'ckages. st');
INSERT INTO public.part VALUES (171033, 'sky ghost azure saddle almond', 'Manufacturer#2           ', 'Brand#22  ', 'LARGE BURNISHED NICKEL', 49, 'LG BAG    ', 1104.03, 'usly even ideas wake');
INSERT INTO public.part VALUES (105525, 'floral sandy burnished deep orange', 'Manufacturer#2           ', 'Brand#25  ', 'PROMO ANODIZED COPPER', 28, 'LG CAN    ', 1530.52, 'hall have to hagg');
INSERT INTO public.part VALUES (125102, 'tomato rosy cream drab royal', 'Manufacturer#5           ', 'Brand#53  ', 'LARGE BRUSHED NICKEL', 27, 'LG BAG    ', 1127.10, 's believe dolphi');
INSERT INTO public.part VALUES (194576, 'cornsilk indian ivory blue plum', 'Manufacturer#5           ', 'Brand#55  ', 'SMALL BRUSHED TIN', 28, 'WRAP CAN  ', 1670.57, 'carefully silent foxe');
INSERT INTO public.part VALUES (103806, 'gainsboro antique misty sky drab', 'Manufacturer#4           ', 'Brand#42  ', 'SMALL BRUSHED BRASS', 27, 'LG BAG    ', 1809.80, 'lly special');
INSERT INTO public.part VALUES (74199, 'honeydew metallic seashell coral peru', 'Manufacturer#2           ', 'Brand#24  ', 'SMALL BURNISHED COPPER', 21, 'MED DRUM  ', 1173.19, 'yers ');
INSERT INTO public.part VALUES (116768, 'turquoise aquamarine puff sandy tan', 'Manufacturer#3           ', 'Brand#32  ', 'SMALL BURNISHED STEEL', 27, 'JUMBO BOX ', 1784.76, ' platelets ');
INSERT INTO public.part VALUES (75214, 'orange pale spring lime frosted', 'Manufacturer#5           ', 'Brand#53  ', 'MEDIUM POLISHED TIN', 4, 'SM PACK   ', 1189.21, 'kly careful');
INSERT INTO public.part VALUES (91613, 'royal moccasin frosted white almond', 'Manufacturer#5           ', 'Brand#52  ', 'LARGE POLISHED BRASS', 10, 'LG BOX    ', 1604.61, 'ke quickl');
INSERT INTO public.part VALUES (100191, 'khaki burlywood azure thistle blanched', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY BURNISHED TIN', 43, 'JUMBO BAG ', 1191.19, 'ing pi');
INSERT INTO public.part VALUES (131026, 'spring violet burlywood mint royal', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD POLISHED BRASS', 14, 'MED BOX   ', 1057.02, 'al foxes dazzle ca');
INSERT INTO public.part VALUES (89057, 'antique royal thistle green coral', 'Manufacturer#3           ', 'Brand#33  ', 'ECONOMY PLATED BRASS', 26, 'SM DRUM   ', 1046.05, 'uctio');
INSERT INTO public.part VALUES (178773, 'chartreuse ghost brown floral cornflower', 'Manufacturer#5           ', 'Brand#53  ', 'STANDARD BURNISHED STEEL', 5, 'MED CAN   ', 1851.77, ' special asympto');
INSERT INTO public.part VALUES (180651, 'turquoise aquamarine lemon antique lace', 'Manufacturer#1           ', 'Brand#11  ', 'STANDARD POLISHED NICKEL', 28, 'LG BOX    ', 1731.65, 'r blith');
INSERT INTO public.part VALUES (166403, 'misty seashell spring hot lemon', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD ANODIZED TIN', 32, 'WRAP CASE ', 1469.40, '. blith');
INSERT INTO public.part VALUES (40460, 'papaya lace puff sienna olive', 'Manufacturer#3           ', 'Brand#32  ', 'ECONOMY BURNISHED STEEL', 36, 'JUMBO CASE', 1400.46, 'eodol');
INSERT INTO public.part VALUES (72240, 'navy misty mint brown sandy', 'Manufacturer#2           ', 'Brand#22  ', 'MEDIUM PLATED STEEL', 49, 'JUMBO CAN ', 1212.24, 'ess pains use regu');
INSERT INTO public.part VALUES (37539, 'orange tomato navajo smoke peach', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD BRUSHED COPPER', 21, 'SM CASE   ', 1476.53, 'efully fur');
INSERT INTO public.part VALUES (8270, 'dim drab magenta blanched cornsilk', 'Manufacturer#4           ', 'Brand#44  ', 'STANDARD ANODIZED TIN', 36, 'MED JAR   ', 1178.27, 'ests sleep bli');
INSERT INTO public.part VALUES (70674, 'yellow goldenrod blush navajo thistle', 'Manufacturer#4           ', 'Brand#42  ', 'STANDARD BRUSHED BRASS', 38, 'WRAP CASE ', 1644.67, 'express i');
INSERT INTO public.part VALUES (113306, 'lawn firebrick slate metallic black', 'Manufacturer#1           ', 'Brand#13  ', 'ECONOMY BURNISHED STEEL', 15, 'LG CASE   ', 1319.30, 'y ironic foxes. sly');
INSERT INTO public.part VALUES (59635, 'navajo khaki rosy dodger red', 'Manufacturer#2           ', 'Brand#21  ', 'LARGE BRUSHED NICKEL', 33, 'SM PACK   ', 1594.63, 's boost fur');
INSERT INTO public.part VALUES (89460, 'purple chartreuse linen salmon pale', 'Manufacturer#3           ', 'Brand#34  ', 'LARGE PLATED BRASS', 29, 'JUMBO BOX ', 1449.46, 'struct');
INSERT INTO public.part VALUES (131445, 'puff black violet olive royal', 'Manufacturer#4           ', 'Brand#43  ', 'MEDIUM POLISHED NICKEL', 27, 'WRAP PKG  ', 1476.44, 'ses. regular, u');
INSERT INTO public.part VALUES (40418, 'coral olive metallic snow steel', 'Manufacturer#5           ', 'Brand#54  ', 'STANDARD BURNISHED NICKEL', 47, 'SM CASE   ', 1358.41, 'iously ab');
INSERT INTO public.part VALUES (82846, 'ghost blush navajo drab cream', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD BRUSHED TIN', 2, 'JUMBO CASE', 1828.84, 'th the pending accoun');
INSERT INTO public.part VALUES (183711, 'cornsilk blush puff lawn saddle', 'Manufacturer#2           ', 'Brand#21  ', 'SMALL BURNISHED TIN', 26, 'LG DRUM   ', 1794.71, ' hinder slyly bold ');
INSERT INTO public.part VALUES (48895, 'violet coral blush dim forest', 'Manufacturer#5           ', 'Brand#51  ', 'ECONOMY POLISHED BRASS', 34, 'WRAP PKG  ', 1843.89, 't the carefull');
INSERT INTO public.part VALUES (131403, 'pink cornflower chartreuse chocolate green', 'Manufacturer#4           ', 'Brand#44  ', 'SMALL PLATED TIN', 45, 'JUMBO PKG ', 1434.40, 'usly final de');
INSERT INTO public.part VALUES (120470, 'ivory ghost burlywood dim antique', 'Manufacturer#4           ', 'Brand#45  ', 'MEDIUM BRUSHED STEEL', 3, 'WRAP PACK ', 1490.47, 'its are slyly. ');
INSERT INTO public.part VALUES (34666, 'firebrick papaya sienna deep khaki', 'Manufacturer#1           ', 'Brand#12  ', 'STANDARD POLISHED STEEL', 50, 'LG PKG    ', 1600.66, 'ng sa');
INSERT INTO public.part VALUES (125768, 'dodger coral brown smoke thistle', 'Manufacturer#5           ', 'Brand#52  ', 'PROMO POLISHED COPPER', 45, 'MED PKG   ', 1793.76, 'deas use slyl');
INSERT INTO public.part VALUES (35450, 'lime linen blue cornflower sienna', 'Manufacturer#5           ', 'Brand#54  ', 'PROMO ANODIZED NICKEL', 12, 'LG BAG    ', 1385.45, 'ily r');
INSERT INTO public.part VALUES (188890, 'cornsilk rosy chartreuse grey pale', 'Manufacturer#4           ', 'Brand#43  ', 'SMALL PLATED NICKEL', 4, 'JUMBO BOX ', 1978.89, 'tes. even, unusual');
INSERT INTO public.part VALUES (149562, 'azure goldenrod pink honeydew dark', 'Manufacturer#2           ', 'Brand#23  ', 'ECONOMY BRUSHED NICKEL', 12, 'LG PKG    ', 1611.56, ' regular ideas! bold ');
INSERT INTO public.part VALUES (125989, 'blanched white puff khaki blush', 'Manufacturer#3           ', 'Brand#35  ', 'SMALL POLISHED BRASS', 30, 'JUMBO BOX ', 2014.98, 'ests.');
INSERT INTO public.part VALUES (7672, 'magenta coral spring burnished wheat', 'Manufacturer#1           ', 'Brand#15  ', 'SMALL BURNISHED NICKEL', 49, 'JUMBO CAN ', 1579.67, 'sts around t');
INSERT INTO public.part VALUES (182615, 'beige metallic spring forest honeydew', 'Manufacturer#1           ', 'Brand#15  ', 'LARGE POLISHED TIN', 35, 'WRAP JAR  ', 1697.61, 'uctio');
INSERT INTO public.part VALUES (140468, 'goldenrod dim royal purple chocolate', 'Manufacturer#2           ', 'Brand#21  ', 'STANDARD PLATED TIN', 10, 'JUMBO BAG ', 1508.46, 'posits. blithely final');
INSERT INTO public.part VALUES (41788, 'saddle chocolate firebrick turquoise black', 'Manufacturer#5           ', 'Brand#52  ', 'STANDARD POLISHED BRASS', 46, 'MED BAG   ', 1729.78, 'eas. close t');
INSERT INTO public.part VALUES (176786, 'papaya orchid saddle cream dark', 'Manufacturer#3           ', 'Brand#31  ', 'ECONOMY BURNISHED TIN', 30, 'LG BAG    ', 1862.78, 'old foxes. blithely ex');
INSERT INTO public.part VALUES (156501, 'blue drab wheat goldenrod peach', 'Manufacturer#5           ', 'Brand#52  ', 'ECONOMY BRUSHED TIN', 39, 'LG PKG    ', 1557.50, 'y blithely final req');
INSERT INTO public.part VALUES (64486, 'tan chartreuse sienna chocolate rosy', 'Manufacturer#5           ', 'Brand#51  ', 'MEDIUM PLATED TIN', 40, 'MED CASE  ', 1450.48, 'as wake a');
INSERT INTO public.part VALUES (116127, 'turquoise plum almond cornflower gainsboro', 'Manufacturer#5           ', 'Brand#52  ', 'MEDIUM PLATED STEEL', 22, 'MED CAN   ', 1143.12, 'ly per');
