INSERT INTO public.nation VALUES (2, 'BRAZIL                   ', 1, 'y alongside of the pending deposits. carefully special packages are about the ironic forges. slyly special ');
INSERT INTO public.nation VALUES (3, 'CANADA                   ', 1, 'eas hang ironic, silent packages. slyly regular packages are furiously over the tithes. fluffily bold');
INSERT INTO public.nation VALUES (4, 'EGYPT                    ', 4, 'y above the carefully unusual theodolites. final dugouts are quickly across the furiously regular d');
INSERT INTO public.nation VALUES (5, 'ETHIOPIA                 ', 0, 'ven packages wake quickly. regu');
INSERT INTO public.nation VALUES (6, 'FRANCE                   ', 3, 'refully final requests. regular, ironi');
INSERT INTO public.nation VALUES (7, 'GERMANY                  ', 3, 'l platelets. regular accounts x-ray: unusual, regular acco');
INSERT INTO public.nation VALUES (8, 'INDIA                    ', 2, 'ss excuses cajole slyly across the packages. deposits print aroun');
INSERT INTO public.nation VALUES (9, 'INDONESIA                ', 2, ' slyly express asymptotes. regular deposits haggle slyly. carefully ironic hockey players sleep blithely. carefull');
INSERT INTO public.nation VALUES (10, 'IRAN                     ', 4, 'efully alongside of the slyly final dependencies. ');
INSERT INTO public.nation VALUES (11, 'IRAQ                     ', 4, 'nic deposits boost atop the quickly final requests? quickly regula');
INSERT INTO public.nation VALUES (12, 'JAPAN                    ', 2, 'ously. final, express gifts cajole a');
INSERT INTO public.nation VALUES (13, 'JORDAN                   ', 4, 'ic deposits are blithely about the carefully regular pa');
INSERT INTO public.nation VALUES (14, 'KENYA                    ', 0, ' pending excuses haggle furiously deposits. pending, express pinto beans wake fluffily past t');
INSERT INTO public.nation VALUES (15, 'MOROCCO                  ', 0, 'rns. blithely bold courts among the closely regular packages use furiously bold platelets?');
INSERT INTO public.nation VALUES (16, 'MOZAMBIQUE               ', 0, 's. ironic, unusual asymptotes wake blithely r');
INSERT INTO public.nation VALUES (17, 'PERU                     ', 1, 'platelets. blithely pending dependencies use fluffily across the even pinto beans. carefully silent accoun');
INSERT INTO public.nation VALUES (18, 'CHINA                    ', 2, 'c dependencies. furiously express notornis sleep slyly regular accounts. ideas sleep. depos');
INSERT INTO public.nation VALUES (19, 'ROMANIA                  ', 3, 'ular asymptotes are about the furious multipliers. express dependencies nag above the ironically ironic account');
INSERT INTO public.nation VALUES (20, 'SAUDI ARABIA             ', 4, 'ts. silent requests haggle. closely express packages sleep across the blithely');
